-- | GENERATED by tools/sync-deck.mjs - do not edit.
-- |
-- | Source: data/de-1000.csv (1005 words, a course vocabulary list, A1 then A2, so rank is curriculum position rather than frequency).
module Flashcards.Data.Deck.German
  ( deck
  , fingerprint
  )
  where

import Flashcards.Types.Card (Card, Rank(..))

-- | Content hash of what each rank means. Progress is keyed by rank, so a deck
-- | whose rows were renumbered is a different deck as far as saved progress is
-- | concerned.
fingerprint :: String
fingerprint = "8e5a5452be8f"

-- | The index into this deck is meaningful: it is the order cards are
-- | introduced in.
deck :: Array Card
deck =
  [
  { rank: Rank 1, english: "on (days/times)", word: "am" }
  ,
  { rank: Rank 2, english: "article", word: "der Artikel" }
  ,
  { rank: Rank 3, english: "Goodbye!", word: "Auf Wiedersehen!" }
  ,
  { rank: Rank 4, english: "from, out of", word: "aus" }
  ,
  { rank: Rank 5, english: "machine, vending machine", word: "der Automat" }
  ,
  { rank: Rank 6, english: "ATM", word: "der Bankautomat" }
  ,
  { rank: Rank 7, english: "picture, image", word: "das Bild" }
  ,
  { rank: Rank 8, english: "book", word: "das Buch" }
  ,
  { rank: Rank 9, english: "letter (of the alphabet)", word: "der Buchstabe" }
  ,
  { rank: Rank 10, english: "to spell", word: "buchstabieren" }
  ,
  { rank: Rank 11, english: "computer", word: "der Computer" }
  ,
  { rank: Rank 12, english: "German", word: "deutsch" }
  ,
  { rank: Rank 13, english: "Germany", word: "Deutschland" }
  ,
  { rank: Rank 14, english: "Tuesday", word: "der Dienstag" }
  ,
  { rank: Rank 15, english: "Thursday", word: "der Donnerstag" }
  ,
  { rank: Rank 16, english: "family", word: "die Familie" }
  ,
  { rank: Rank 17, english: "feminine", word: "feminin" }
  ,
  { rank: Rank 18, english: "question", word: "die Frage" }
  ,
  { rank: Rank 19, english: "to ask", word: "fragen" }
  ,
  { rank: Rank 20, english: "Friday", word: "der Freitag" }
  ,
  { rank: Rank 21, english: "to believe", word: "glauben" }
  ,
  { rank: Rank 22, english: "Good day!", word: "Guten Tag!" }
  ,
  { rank: Rank 23, english: "Hello!", word: "Hallo!" }
  ,
  { rank: Rank 24, english: "notebook, exercise book", word: "das Heft" }
  ,
  { rank: Rank 25, english: "to be called", word: "heißen" }
  ,
  { rank: Rank 26, english: "conjugation", word: "die Konjugation" }
  ,
  { rank: Rank 27, english: "ballpoint pen", word: "der Kuli" }
  ,
  { rank: Rank 28, english: "easy, light", word: "leicht" }
  ,
  { rank: Rank 29, english: "to learn", word: "lernen" }
  ,
  { rank: Rank 30, english: "masculine", word: "maskulin" }
  ,
  { rank: Rank 31, english: "person, human being", word: "der Mensch" }
  ,
  { rank: Rank 32, english: "Wednesday", word: "der Mittwoch" }
  ,
  { rank: Rank 33, english: "Monday", word: "der Montag" }
  ,
  { rank: Rank 34, english: "no", word: "nein" }
  ,
  { rank: Rank 35, english: "neuter", word: "neutral" }
  ,
  { rank: Rank 36, english: "still, yet", word: "noch" }
  ,
  { rank: Rank 37, english: "noun", word: "das Nomen" }
  ,
  { rank: Rank 38, english: "paper", word: "das Papier" }
  ,
  { rank: Rank 39, english: "person", word: "die Person" }
  ,
  { rank: Rank 40, english: "radio", word: "das Radio" }
  ,
  { rank: Rank 41, english: "Saturday", word: "der Samstag" }
  ,
  { rank: Rank 42, english: "sentence", word: "der Satz" }
  ,
  { rank: Rank 43, english: "to write", word: "schreiben" }
  ,
  { rank: Rank 44, english: "Sunday", word: "der Sonntag" }
  ,
  { rank: Rank 45, english: "to speak", word: "sprechen" }
  ,
  { rank: Rank 46, english: "pen, pencil", word: "der Stift" }
  ,
  { rank: Rank 47, english: "super, great", word: "super" }
  ,
  { rank: Rank 48, english: "blackboard", word: "die Tafel" }
  ,
  { rank: Rank 49, english: "bag", word: "die Tasche" }
  ,
  { rank: Rank 50, english: "clock, watch", word: "die Uhr" }
  ,
  { rank: Rank 51, english: "verb", word: "das Verb" }
  ,
  { rank: Rank 52, english: "late morning", word: "der Vormittag" }
  ,
  { rank: Rank 53, english: "when", word: "wann" }
  ,
  { rank: Rank 54, english: "who", word: "wer" }
  ,
  { rank: Rank 55, english: "how", word: "wie" }
  ,
  { rank: Rank 56, english: "welcome", word: "willkommen" }
  ,
  { rank: Rank 57, english: "where from", word: "woher" }
  ,
  { rank: Rank 58, english: "word order", word: "die Wortstellung" }
  ,
  { rank: Rank 59, english: "alone", word: "allein" }
  ,
  { rank: Rank 60, english: "answer", word: "die Antwort" }
  ,
  { rank: Rank 61, english: "to work", word: "arbeiten" }
  ,
  { rank: Rank 62, english: "architect (male)", word: "der Architekt" }
  ,
  { rank: Rank 63, english: "architect (female)", word: "die Architektin" }
  ,
  { rank: Rank 64, english: "also, too", word: "auch" }
  ,
  { rank: Rank 65, english: "abroad, foreign country", word: "das Ausland" }
  ,
  { rank: Rank 66, english: "brother", word: "der Bruder" }
  ,
  { rank: Rank 67, english: "cousin (male)", word: "der Cousin" }
  ,
  { rank: Rank 68, english: "cousin (female)", word: "die Cousine" }
  ,
  { rank: Rank 69, english: "then", word: "dann" }
  ,
  { rank: Rank 70, english: "your (informal)", word: "dein" }
  ,
  { rank: Rank 71, english: "designer (male)", word: "der Designer" }
  ,
  { rank: Rank 72, english: "designer (female)", word: "die Designerin" }
  ,
  { rank: Rank 73, english: "yes (contradicting), but", word: "doch" }
  ,
  { rank: Rank 74, english: "thirty", word: "dreißig" }
  ,
  { rank: Rank 75, english: "one", word: "eins / ein" }
  ,
  { rank: Rank 76, english: "only child", word: "das Einzelkind" }
  ,
  { rank: Rank 77, english: "parents", word: "die Eltern" }
  ,
  { rank: Rank 78, english: "your (plural informal)", word: "euer" }
  ,
  { rank: Rank 79, english: "photo", word: "das Foto" }
  ,
  { rank: Rank 80, english: "photographer", word: "der Fotograf" }
  ,
  { rank: Rank 81, english: "woman", word: "die Frau" }
  ,
  { rank: Rank 82, english: "friend", word: "der Freund" }
  ,
  { rank: Rank 83, english: "friend (female)", word: "die Freundin" }
  ,
  { rank: Rank 84, english: "to play football", word: "Fußball (spielen)" }
  ,
  { rank: Rank 85, english: "gladly, with pleasure", word: "gern" }
  ,
  { rank: Rank 86, english: "divorced", word: "geschieden" }
  ,
  { rank: Rank 87, english: "siblings", word: "die Geschwister" }
  ,
  { rank: Rank 88, english: "grandparents", word: "die Großeltern" }
  ,
  { rank: Rank 89, english: "grandmother", word: "die Großmutter" }
  ,
  { rank: Rank 90, english: "grandfather", word: "der Großvater" }
  ,
  { rank: Rank 91, english: "good", word: "gut" }
  ,
  { rank: Rank 92, english: "to hear", word: "hören" }
  ,
  { rank: Rank 93, english: "hundred", word: "hundert" }
  ,
  { rank: Rank 94, english: "their", word: "ihr (Pl.)" }
  ,
  { rank: Rank 95, english: "IT specialist (male)", word: "der Informatiker" }
  ,
  { rank: Rank 96, english: "IT specialist (female)", word: "die Informatikerin" }
  ,
  { rank: Rank 97, english: "engineer (male)", word: "der Ingenieur" }
  ,
  { rank: Rank 98, english: "engineer (female)", word: "die Ingenieurin" }
  ,
  { rank: Rank 99, english: "international", word: "international" }
  ,
  { rank: Rank 100, english: "yes", word: "ja" }
  ,
  { rank: Rank 101, english: "now", word: "jetzt" }
  ,
  { rank: Rank 102, english: "child", word: "das Kind" }
  ,
  { rank: Rank 103, english: "small", word: "klein" }
  ,
  { rank: Rank 104, english: "cook, chef (male)", word: "der Koch" }
  ,
  { rank: Rank 105, english: "to cook", word: "kochen" }
  ,
  { rank: Rank 106, english: "cook, chef (female)", word: "die Köchin" }
  ,
  { rank: Rank 107, english: "colleague (male)", word: "der Kollege" }
  ,
  { rank: Rank 108, english: "colleague (female)", word: "die Kollegin" }
  ,
  { rank: Rank 109, english: "country, land", word: "das Land" }
  ,
  { rank: Rank 110, english: "life", word: "das Leben" }
  ,
  { rank: Rank 111, english: "single (unmarried)", word: "ledig" }
  ,
  { rank: Rank 112, english: "teacher", word: "der Lehrer" }
  ,
  { rank: Rank 113, english: "love", word: "die Liebe" }
  ,
  { rank: Rank 114, english: "favorite topic", word: "das Lieblingsthema" }
  ,
  { rank: Rank 115, english: "mom", word: "das Mam" }
  ,
  { rank: Rank 116, english: "one (impersonal pronoun)", word: "man" }
  ,
  { rank: Rank 117, english: "manager (male)", word: "der Manager" }
  ,
  { rank: Rank 118, english: "manager (female)", word: "die Managerin" }
  ,
  { rank: Rank 119, english: "man", word: "der Mann" }
  ,
  { rank: Rank 120, english: "my", word: "mein" }
  ,
  { rank: Rank 121, english: "to mean/think", word: "meinen" }
  ,
  { rank: Rank 122, english: "musician (male)", word: "der Musiker" }
  ,
  { rank: Rank 123, english: "musician (female)", word: "die Musikerin" }
  ,
  { rank: Rank 124, english: "mother", word: "die Mutter" }
  ,
  { rank: Rank 125, english: "not", word: "nicht" }
  ,
  { rank: Rank 126, english: "the Netherlands", word: "die Niederlande" }
  ,
  { rank: Rank 127, english: "zero", word: "null" }
  ,
  { rank: Rank 128, english: "opera", word: "die Oper" }
  ,
  { rank: Rank 129, english: "Austria", word: "Österreich" }
  ,
  { rank: Rank 130, english: "partner", word: "der Partner" }
  ,
  { rank: Rank 131, english: "plural", word: "der Plural" }
  ,
  { rank: Rank 132, english: "puzzle", word: "das Puzzle" }
  ,
  { rank: Rank 133, english: "ship", word: "das Schiff" }
  ,
  { rank: Rank 134, english: "beautiful", word: "schön" }
  ,
  { rank: Rank 135, english: "sister", word: "die Schwester" }
  ,
  { rank: Rank 136, english: "to swim", word: "schwimmen" }
  ,
  { rank: Rank 137, english: "very", word: "sehr" }
  ,
  { rank: Rank 138, english: "to be", word: "sein" }
  ,
  { rank: Rank 139, english: "independent, self-employed", word: "selbständig" }
  ,
  { rank: Rank 140, english: "singular", word: "der Singular" }
  ,
  { rank: Rank 141, english: "son", word: "der Sohn" }
  ,
  { rank: Rank 142, english: "to play", word: "spielen" }
  ,
  { rank: Rank 143, english: "flight attendant (male)", word: "der Steward" }
  ,
  { rank: Rank 144, english: "flight attendant (female)", word: "die Stewardess" }
  ,
  { rank: Rank 145, english: "day", word: "der Tag" }
  ,
  { rank: Rank 146, english: "dance", word: "der Tanz" }
  ,
  { rank: Rank 147, english: "to dance", word: "tanzen" }
  ,
  { rank: Rank 148, english: "to play tennis", word: "Tennis (spielen)" }
  ,
  { rank: Rank 149, english: "topic, subject", word: "das Thema" }
  ,
  { rank: Rank 150, english: "daughter", word: "die Tochter" }
  ,
  { rank: Rank 151, english: "great, awesome", word: "toll" }
  ,
  { rank: Rank 152, english: "Turkey", word: "die Türkei" }
  ,
  { rank: Rank 153, english: "Ukraine", word: "die Ukraine" }
  ,
  { rank: Rank 154, english: "our", word: "unser" }
  ,
  { rank: Rank 155, english: "father", word: "der Vater" }
  ,
  { rank: Rank 156, english: "married", word: "verheiratet" }
  ,
  { rank: Rank 157, english: "because", word: "weil" }
  ,
  { rank: Rank 158, english: "week", word: "die Woche" }
  ,
  { rank: Rank 159, english: "number", word: "die Zahl" }
  ,
  { rank: Rank 160, english: "to draw", word: "zeichnen" }
  ,
  { rank: Rank 161, english: "twenty", word: "zwanzig" }
  ,
  { rank: Rank 162, english: "evening", word: "der Abend" }
  ,
  { rank: Rank 163, english: "apple", word: "der Apfel" }
  ,
  { rank: Rank 164, english: "to order", word: "bestellen" }
  ,
  { rank: Rank 165, english: "beer", word: "das Bier" }
  ,
  { rank: Rank 166, english: "organic", word: "bio" }
  ,
  { rank: Rank 167, english: "bread", word: "das Brot" }
  ,
  { rank: Rank 168, english: "butter", word: "die Butter" }
  ,
  { rank: Rank 169, english: "thirst", word: "der Durst" }
  ,
  { rank: Rank 170, english: "to be thirsty", word: "Durst haben" }
  ,
  { rank: Rank 171, english: "egg", word: "das Ei" }
  ,
  { rank: Rank 172, english: "a/an (indefinite article)", word: "ein / eine / einen" }
  ,
  { rank: Rank 173, english: "to eat", word: "essen" }
  ,
  { rank: Rank 174, english: "fish", word: "der Fisch" }
  ,
  { rank: Rank 175, english: "meat", word: "das Fleisch" }
  ,
  { rank: Rank 176, english: "vegetables", word: "das Gemüse" }
  ,
  { rank: Rank 177, english: "open (of a shop/restaurant)", word: "geöffnet" }
  ,
  { rank: Rank 178, english: "closed", word: "geschlossen" }
  ,
  { rank: Rank 179, english: "drink, beverage", word: "das Getränk" }
  ,
  { rank: Rank 180, english: "separately (paying)", word: "getrennt" }
  ,
  { rank: Rank 181, english: "main course", word: "die Hauptspeise" }
  ,
  { rank: Rank 182, english: "hunger", word: "der Hunger" }
  ,
  { rank: Rank 183, english: "to be hungry", word: "Hunger haben" }
  ,
  { rank: Rank 184, english: "potato", word: "die Kartoffel" }
  ,
  { rank: Rank 185, english: "cheese", word: "der Käse" }
  ,
  { rank: Rank 186, english: "to buy", word: "kaufen" }
  ,
  { rank: Rank 187, english: "no, not a", word: "kein / keine" }
  ,
  { rank: Rank 188, english: "delicious, tasty", word: "lecker" }
  ,
  { rank: Rank 189, english: "to read", word: "lesen" }
  ,
  { rank: Rank 190, english: "set menu / menu", word: "das Menü" }
  ,
  { rank: Rank 191, english: "minute", word: "die Minute" }
  ,
  { rank: Rank 192, english: "noon, midday", word: "der Mittag" }
  ,
  { rank: Rank 193, english: "at midday, at lunchtime", word: "mittags" }
  ,
  { rank: Rank 194, english: "to like (general preference)", word: "mögen" }
  ,
  { rank: Rank 195, english: "morning", word: "der Morgen" }
  ,
  { rank: Rank 196, english: "dessert", word: "der Nachtisch" }
  ,
  { rank: Rank 197, english: "to take", word: "nehmen" }
  ,
  { rank: Rank 198, english: "not really (like)", word: "nicht so gern" }
  ,
  { rank: Rank 199, english: "fruit", word: "das Obst" }
  ,
  { rank: Rank 200, english: "pasta", word: "die Pasta" }
  ,
  { rank: Rank 201, english: "pizza", word: "die Pizza" }
  ,
  { rank: Rank 202, english: "juice", word: "der Saft" }
  ,
  { rank: Rank 203, english: "salad / lettuce", word: "der Salat" }
  ,
  { rank: Rank 204, english: "schnitzel (breaded meat cutlet)", word: "das Schnitzel" }
  ,
  { rank: Rank 205, english: "dish, food item", word: "die Speise" }
  ,
  { rank: Rank 206, english: "hour", word: "die Stunde" }
  ,
  { rank: Rank 207, english: "soup", word: "die Suppe" }
  ,
  { rank: Rank 208, english: "tea", word: "der Tee" }
  ,
  { rank: Rank 209, english: "tomato", word: "die Tomate" }
  ,
  { rank: Rank 210, english: "to meet", word: "treffen" }
  ,
  { rank: Rank 211, english: "to drink", word: "trinken" }
  ,
  { rank: Rank 212, english: "time (clock time)", word: "die Uhrzeit" }
  ,
  { rank: Rank 213, english: "at (clock time)", word: "um" }
  ,
  { rank: Rank 214, english: "from ... to", word: "von ... bis" }
  ,
  { rank: Rank 215, english: "water", word: "das Wasser" }
  ,
  { rank: Rank 216, english: "wine", word: "der Wein" }
  ,
  { rank: Rank 217, english: "important", word: "wichtig" }
  ,
  { rank: Rank 218, english: "sausage / cold cuts", word: "die Wurst" }
  ,
  { rank: Rank 219, english: "together", word: "zusammen" }
  ,
  { rank: Rank 220, english: "battery (device)", word: "der Akku" }
  ,
  { rank: Rank 221, english: "to get dressed, to put on", word: "anziehen" }
  ,
  { rank: Rank 222, english: "work", word: "die Arbeit" }
  ,
  { rank: Rank 223, english: "to open", word: "aufmachen" }
  ,
  { rank: Rank 224, english: "to tidy up", word: "aufräumen" }
  ,
  { rank: Rank 225, english: "to get up", word: "aufstehen" }
  ,
  { rank: Rank 226, english: "meeting", word: "die Besprechung" }
  ,
  { rank: Rank 227, english: "office", word: "das Büro" }
  ,
  { rank: Rank 228, english: "boss, manager (male)", word: "der Chef" }
  ,
  { rank: Rank 229, english: "boss, manager (female)", word: "die Chefin" }
  ,
  { rank: Rank 230, english: "to download", word: "downloaden" }
  ,
  { rank: Rank 231, english: "to go shopping", word: "einkaufen" }
  ,
  { rank: Rank 232, english: "allowed, permitted", word: "erlaubt" }
  ,
  { rank: Rank 233, english: "early", word: "früh" }
  ,
  { rank: Rank 234, english: "frustrated", word: "frustriert" }
  ,
  { rank: Rank 235, english: "to work, to function", word: "funktionieren" }
  ,
  { rank: Rank 236, english: "house rules", word: "die Hausordnung" }
  ,
  { rank: Rank 237, english: "pet", word: "das Haustier" }
  ,
  { rank: Rank 238, english: "to help", word: "helfen" }
  ,
  { rank: Rank 239, english: "today", word: "heute" }
  ,
  { rank: Rank 240, english: "always", word: "immer" }
  ,
  { rank: Rank 241, english: "can/be able to", word: "können" }
  ,
  { rank: Rank 242, english: "to charge / to load", word: "laden" }
  ,
  { rank: Rank 243, english: "laptop", word: "das Laptop" }
  ,
  { rank: Rank 244, english: "loud, noisy", word: "laut" }
  ,
  { rank: Rank 245, english: "would like (polite request)", word: "möchten" }
  ,
  { rank: Rank 246, english: "tomorrow", word: "morgen" }
  ,
  { rank: Rank 247, english: "tired", word: "müde" }
  ,
  { rank: Rank 248, english: "must/have to", word: "müssen" }
  ,
  { rank: Rank 249, english: "nervous", word: "nervös" }
  ,
  { rank: Rank 250, english: "normally, usually", word: "normalerweise" }
  ,
  { rank: Rank 251, english: "to park", word: "parken" }
  ,
  { rank: Rank 252, english: "password", word: "das Passwort" }
  ,
  { rank: Rank 253, english: "problem", word: "das Problem" }
  ,
  { rank: Rank 254, english: "to smoke", word: "rauchen" }
  ,
  { rank: Rank 255, english: "rule", word: "die Regel" }
  ,
  { rank: Rank 256, english: "sentence bracket (grammar term)", word: "die Satzklammer" }
  ,
  { rank: Rank 257, english: "late", word: "spät" }
  ,
  { rank: Rank 258, english: "to surf (internet)", word: "surfen" }
  ,
  { rank: Rank 259, english: "tablet", word: "das Tablet" }
  ,
  { rank: Rank 260, english: "daily routine", word: "der Tagesablauf" }
  ,
  { rank: Rank 261, english: "forbidden, not allowed", word: "verboten" }
  ,
  { rank: Rank 262, english: "laundry, washing", word: "die Wäsche" }
  ,
  { rank: Rank 263, english: "to wash", word: "waschen" }
  ,
  { rank: Rank 264, english: "WiFi connection", word: "die WLAN-Verbindung" }
  ,
  { rank: Rank 265, english: "to want", word: "wollen" }
  ,
  { rank: Rank 266, english: "angry", word: "wütend" }
  ,
  { rank: Rank 267, english: "content, satisfied", word: "zufrieden" }
  ,
  { rank: Rank 268, english: "to close", word: "zumachen" }
  ,
  { rank: Rank 269, english: "to turn (direction)", word: "abbiegen" }
  ,
  { rank: Rank 270, english: "bank", word: "die Bank" }
  ,
  { rank: Rank 271, english: "bed", word: "das Bett" }
  ,
  { rank: Rank 272, english: "library", word: "die Bibliothek" }
  ,
  { rank: Rank 273, english: "to need", word: "brauchen" }
  ,
  { rank: Rank 274, english: "café", word: "das Café" }
  ,
  { rank: Rank 275, english: "because (coord. conjunction)", word: "denn" }
  ,
  { rank: Rank 276, english: "you (accusative, informal)", word: "dich" }
  ,
  { rank: Rank 277, english: "there", word: "dort" }
  ,
  { rank: Rank 278, english: "corner", word: "die Ecke" }
  ,
  { rank: Rank 279, english: "along", word: "entlang" }
  ,
  { rank: Rank 280, english: "it", word: "es" }
  ,
  { rank: Rank 281, english: "window", word: "das Fenster" }
  ,
  { rank: Rank 282, english: "to find", word: "finden" }
  ,
  { rank: Rank 283, english: "for", word: "für" }
  ,
  { rank: Rank 284, english: "opposite, across from", word: "gegenüber" }
  ,
  { rank: Rank 285, english: "straight ahead", word: "geradeaus" }
  ,
  { rank: Rank 286, english: "gift, present", word: "das Geschenk" }
  ,
  { rank: Rank 287, english: "here", word: "hier" }
  ,
  { rank: Rank 288, english: "him (accusative)", word: "ihn" }
  ,
  { rank: Rank 289, english: "nearby, in the vicinity", word: "in der Nähe" }
  ,
  { rank: Rank 290, english: "hospital", word: "das Krankenhaus" }
  ,
  { rank: Rank 291, english: "to lie (position)", word: "liegen" }
  ,
  { rank: Rank 292, english: "left", word: "links" }
  ,
  { rank: Rank 293, english: "me (accusative)", word: "mich" }
  ,
  { rank: Rank 294, english: "not far", word: "nicht weit" }
  ,
  { rank: Rank 295, english: "park", word: "der Park" }
  ,
  { rank: Rank 296, english: "square, plaza", word: "der Platz" }
  ,
  { rank: Rank 297, english: "post office", word: "die Post" }
  ,
  { rank: Rank 298, english: "city hall", word: "das Rathaus" }
  ,
  { rank: Rank 299, english: "right", word: "rechts" }
  ,
  { rank: Rank 300, english: "she", word: "sie" }
  ,
  { rank: Rank 301, english: "city map", word: "der Stadtplan" }
  ,
  { rank: Rank 302, english: "street", word: "die Straße" }
  ,
  { rank: Rank 303, english: "chair", word: "der Stuhl" }
  ,
  { rank: Rank 304, english: "to search", word: "suchen" }
  ,
  { rank: Rank 305, english: "supermarket", word: "der Supermarkt" }
  ,
  { rank: Rank 306, english: "table", word: "der Tisch" }
  ,
  { rank: Rank 307, english: "door", word: "die Tür" }
  ,
  { rank: Rank 308, english: "to know (fact)", word: "wissen" }
  ,
  { rank: Rank 309, english: "where (location)", word: "wo" }
  ,
  { rank: Rank 310, english: "eye", word: "das Auge" }
  ,
  { rank: Rank 311, english: "better", word: "besser" }
  ,
  { rank: Rank 312, english: "blue", word: "blau" }
  ,
  { rank: Rank 313, english: "brown", word: "braun" }
  ,
  { rank: Rank 314, english: "doctor (informal title)", word: "der Doktor" }
  ,
  { rank: Rank 315, english: "a/an (dative, masc./neut.)", word: "einem" }
  ,
  { rank: Rank 316, english: "having a cold", word: "erkältet" }
  ,
  { rank: Rank 317, english: "the first (ordinal)", word: "erste" }
  ,
  { rank: Rank 318, english: "yellow", word: "gelb" }
  ,
  { rank: Rank 319, english: "yesterday", word: "gestern" }
  ,
  { rank: Rank 320, english: "grey", word: "grau" }
  ,
  { rank: Rank 321, english: "green", word: "grün" }
  ,
  { rank: Rank 322, english: "hand", word: "die Hand" }
  ,
  { rank: Rank 323, english: "cough", word: "der Husten" }
  ,
  { rank: Rank 324, english: "no (dative, masc./neut.)", word: "keinem" }
  ,
  { rank: Rank 325, english: "head", word: "der Kopf" }
  ,
  { rank: Rank 326, english: "headache", word: "Kopfschmerzen (Pl.)" }
  ,
  { rank: Rank 327, english: "last week", word: "letzte Woche" }
  ,
  { rank: Rank 328, english: "last month", word: "letzten Monat" }
  ,
  { rank: Rank 329, english: "purple / lilac", word: "lila" }
  ,
  { rank: Rank 330, english: "my (dative, masc./neut.)", word: "meinem" }
  ,
  { rank: Rank 331, english: "orange", word: "orange" }
  ,
  { rank: Rank 332, english: "doctor's office / practice", word: "die Praxis" }
  ,
  { rank: Rank 333, english: "red", word: "rot" }
  ,
  { rank: Rank 334, english: "rest, quiet", word: "die Ruhe" }
  ,
  { rank: Rank 335, english: "bad, terrible", word: "schlimm" }
  ,
  { rank: Rank 336, english: "pain", word: "Schmerzen (Pl.)" }
  ,
  { rank: Rank 337, english: "black", word: "schwarz" }
  ,
  { rank: Rank 338, english: "bandage", word: "der Verband" }
  ,
  { rank: Rank 339, english: "from, of (+ dative)", word: "von + Dativ" }
  ,
  { rank: Rank 340, english: "the day before yesterday", word: "vorgestern" }
  ,
  { rank: Rank 341, english: "white", word: "weiß" }
  ,
  { rank: Rank 342, english: "tooth", word: "der Zahn" }
  ,
  { rank: Rank 343, english: "old town", word: "die Altstadt" }
  ,
  { rank: Rank 344, english: "to the (lake/sea/river)", word: "an den" }
  ,
  { rank: Rank 345, english: "to the (mountain)", word: "auf den" }
  ,
  { rank: Rank 346, english: "train station", word: "der Bahnhof" }
  ,
  { rank: Rank 347, english: "fantastic", word: "fantastisch" }
  ,
  { rank: Rank 348, english: "degree", word: "der Grad" }
  ,
  { rank: Rank 349, english: "to have", word: "haben" }
  ,
  { rank: Rank 350, english: "to the (feminine countries)", word: "in die" }
  ,
  { rank: Rank 351, english: "into the", word: "ins" }
  ,
  { rank: Rank 352, english: "coffee", word: "der Kaffee" }
  ,
  { rank: Rank 353, english: "cool", word: "kühl" }
  ,
  { rank: Rank 354, english: "kind regards, love from", word: "liebe Grüße" }
  ,
  { rank: Rank 355, english: "to (cities, most countries)", word: "nach" }
  ,
  { rank: Rank 356, english: "night", word: "die Nacht" }
  ,
  { rank: Rank 357, english: "to reserve", word: "reservieren" }
  ,
  { rank: Rank 358, english: "reception, front desk", word: "die Rezeption" }
  ,
  { rank: Rank 359, english: "castle, palace", word: "das Schloss" }
  ,
  { rank: Rank 360, english: "key", word: "der Schlüssel" }
  ,
  { rank: Rank 361, english: "sun", word: "die Sonne" }
  ,
  { rank: Rank 362, english: "many greetings from", word: "viele Grüße" }
  ,
  { rank: Rank 363, english: "wonderful, gorgeous", word: "wunderschön" }
  ,
  { rank: Rank 364, english: "train", word: "der Zug" }
  ,
  { rank: Rank 365, english: "to wake up", word: "aufwachen" }
  ,
  { rank: Rank 366, english: "to stay/remain", word: "bleiben" }
  ,
  { rank: Rank 367, english: "this (demonstrative article)", word: "dieser" }
  ,
  { rank: Rank 368, english: "you (dative, informal)", word: "dir" }
  ,
  { rank: Rank 369, english: "to fall asleep", word: "einschlafen" }
  ,
  { rank: Rank 370, english: "you all (accusative)", word: "euch" }
  ,
  { rank: Rank 371, english: "to drive/travel", word: "fahren" }
  ,
  { rank: Rank 372, english: "film, movie", word: "der Film" }
  ,
  { rank: Rank 373, english: "to fly", word: "fliegen" }
  ,
  { rank: Rank 374, english: "to please/like", word: "gefallen" }
  ,
  { rank: Rank 375, english: "to go/walk", word: "gehen" }
  ,
  { rank: Rank 376, english: "gloves (plural)", word: "die Handschuhe" }
  ,
  { rank: Rank 377, english: "him (dative)", word: "ihm" }
  ,
  { rank: Rank 378, english: "them (dative)", word: "ihnen" }
  ,
  { rank: Rank 379, english: "you (plural)", word: "ihr" }
  ,
  { rank: Rank 380, english: "Carnival / Mardi Gras", word: "der Karneval" }
  ,
  { rank: Rank 381, english: "to come", word: "kommen" }
  ,
  { rank: Rank 382, english: "to run", word: "laufen" }
  ,
  { rank: Rank 383, english: "me (dative)", word: "mir" }
  ,
  { rank: Rank 384, english: "hat, woolly hat", word: "die Mütze" }
  ,
  { rank: Rank 385, english: "news (always plural)", word: "die Nachrichten" }
  ,
  { rank: Rank 386, english: "Oktoberfest", word: "das Oktoberfest" }
  ,
  { rank: Rank 387, english: "online", word: "online" }
  ,
  { rank: Rank 388, english: "to happen", word: "passieren" }
  ,
  { rank: Rank 389, english: "podcast", word: "der Podcast" }
  ,
  { rank: Rank 390, english: "scarf", word: "der Schal" }
  ,
  { rank: Rank 391, english: "to taste (good/bad)", word: "schmecken" }
  ,
  { rank: Rank 392, english: "already", word: "schon" }
  ,
  { rank: Rank 393, english: "TV series", word: "die Serie" }
  ,
  { rank: Rank 394, english: "to stand", word: "stehen" }
  ,
  { rank: Rank 395, english: "us (accusative)", word: "uns" }
  ,
  { rank: Rank 396, english: "why", word: "warum" }
  ,
  { rank: Rank 397, english: "Christmas market", word: "der Weihnachtsmarkt" }
  ,
  { rank: Rank 398, english: "which (question word for nouns)", word: "welcher" }
  ,
  { rank: Rank 399, english: "magazine", word: "die Zeitschrift" }
  ,
  { rank: Rank 400, english: "newspaper", word: "die Zeitung" }
  ,
  { rank: Rank 401, english: "abbreviation", word: "die Abkürzung" }
  ,
  { rank: Rank 402, english: "cancellation, decline", word: "die Absage" }
  ,
  { rank: Rank 403, english: "to cancel, decline", word: "absagen" }
  ,
  { rank: Rank 404, english: "to begin, to start", word: "anfangen" }
  ,
  { rank: Rank 405, english: "to call (phone)", word: "anrufen" }
  ,
  { rank: Rank 406, english: "announcement, outgoing message", word: "die Ansage" }
  ,
  { rank: Rank 407, english: "app", word: "die App" }
  ,
  { rank: Rank 408, english: "to stop, to cease", word: "aufhören" }
  ,
  { rank: Rank 409, english: "to receive, to get", word: "bekommen" }
  ,
  { rank: Rank 410, english: "to insult", word: "beleidigen" }
  ,
  { rank: Rank 411, english: "to use", word: "benutzen" }
  ,
  { rank: Rank 412, english: "letter", word: "der Brief" }
  ,
  { rank: Rank 413, english: "chat", word: "der Chat" }
  ,
  { rank: Rank 414, english: "to chat", word: "chatten" }
  ,
  { rank: Rank 415, english: "cyberbullying", word: "das Cybermobbing" }
  ,
  { rank: Rank 416, english: "that (conjunction)", word: "dass" }
  ,
  { rank: Rank 417, english: "to discuss", word: "diskutieren" }
  ,
  { rank: Rank 418, english: "urgent", word: "dringend" }
  ,
  { rank: Rank 419, english: "email", word: "die E-Mail" }
  ,
  { rank: Rank 420, english: "to invite", word: "einladen" }
  ,
  { rank: Rank 421, english: "to develop", word: "entwickeln" }
  ,
  { rank: Rank 422, english: "to invent", word: "erfinden" }
  ,
  { rank: Rank 423, english: "invention", word: "die Erfindung" }
  ,
  { rank: Rank 424, english: "celebration, party", word: "die Feier" }
  ,
  { rank: Rank 425, english: "to celebrate", word: "feiern" }
  ,
  { rank: Rank 426, english: "celebration, party, festival", word: "das Fest" }
  ,
  { rank: Rank 427, english: "formal", word: "formell" }
  ,
  { rank: Rank 428, english: "in the past, formerly", word: "früher" }
  ,
  { rank: Rank 429, english: "history / story", word: "die Geschichte" }
  ,
  { rank: Rank 430, english: "mobile phone", word: "das Handy" }
  ,
  { rank: Rank 431, english: "main clause", word: "der Hauptsatz" }
  ,
  { rank: Rank 432, english: "heartfelt, warm", word: "herzlich" }
  ,
  { rank: Rank 433, english: "nowadays", word: "heutzutage" }
  ,
  { rank: Rank 434, english: "to stay in contact", word: "in Kontakt bleiben" }
  ,
  { rank: Rank 435, english: "indirect", word: "indirekt" }
  ,
  { rank: Rank 436, english: "informal", word: "informell" }
  ,
  { rank: Rank 437, english: "internet", word: "das Internet" }
  ,
  { rank: Rank 438, english: "century", word: "das Jahrhundert" }
  ,
  { rank: Rank 439, english: "every day", word: "jeden Tag" }
  ,
  { rank: Rank 440, english: "communication", word: "die Kommunikation" }
  ,
  { rank: Rank 441, english: "voicemail / mailbox", word: "die Mailbox" }
  ,
  { rank: Rank 442, english: "sometimes", word: "manchmal" }
  ,
  { rank: Rank 443, english: "to bring along", word: "mitbringen" }
  ,
  { rank: Rank 444, english: "to inform, communicate", word: "mitteilen" }
  ,
  { rank: Rank 445, english: "message", word: "die Nachricht" }
  ,
  { rank: Rank 446, english: "subordinate clause", word: "der Nebensatz" }
  ,
  { rank: Rank 447, english: "never", word: "nie" }
  ,
  { rank: Rank 448, english: "whether, if", word: "ob" }
  ,
  { rank: Rank 449, english: "often", word: "oft" }
  ,
  { rank: Rank 450, english: "past participle", word: "das Partizip II" }
  ,
  { rank: Rank 451, english: "since, for (time)", word: "seit" }
  ,
  { rank: Rank 452, english: "rarely", word: "selten" }
  ,
  { rank: Rank 453, english: "smartphone", word: "das Smartphone" }
  ,
  { rank: Rank 454, english: "smiley, emoji", word: "der Smiley" }
  ,
  { rank: Rank 455, english: "text message", word: "die SMS" }
  ,
  { rank: Rank 456, english: "technology", word: "die Technologie" }
  ,
  { rank: Rank 457, english: "telephone", word: "das Telefon" }
  ,
  { rank: Rank 458, english: "separable (prefix)", word: "trennbar" }
  ,
  { rank: Rank 459, english: "approximately", word: "ungefähr" }
  ,
  { rank: Rank 460, english: "impolite, rude", word: "unhöflich" }
  ,
  { rank: Rank 461, english: "inseparable (prefix)", word: "untrennbar" }
  ,
  { rank: Rank 462, english: "video", word: "das Video" }
  ,
  { rank: Rank 463, english: "to call back", word: "zurückrufen" }
  ,
  { rank: Rank 464, english: "acceptance (of an invitation)", word: "die Zusage" }
  ,
  { rank: Rank 465, english: "to accept (invitation)", word: "zusagen" }
  ,
  { rank: Rank 466, english: "suit", word: "der Anzug" }
  ,
  { rank: Rank 467, english: "to look, to appear", word: "aussehen" }
  ,
  { rank: Rank 468, english: "appearance / looks", word: "das Aussehen" }
  ,
  { rank: Rank 469, english: "blog", word: "der Blog" }
  ,
  { rank: Rank 470, english: "blouse", word: "die Bluse" }
  ,
  { rank: Rank 471, english: "to be in favour", word: "dafür sein" }
  ,
  { rank: Rank 472, english: "to be against", word: "dagegen sein" }
  ,
  { rank: Rank 473, english: "demonstrative pronoun", word: "das Demonstrativpronomen" }
  ,
  { rank: Rank 474, english: "energetic", word: "energisch" }
  ,
  { rank: Rank 475, english: "tight / narrow", word: "eng" }
  ,
  { rank: Rank 476, english: "first impression", word: "erste Eindruck" }
  ,
  { rank: Rank 477, english: "gladly → preferably → most", word: "gern → lieber → am liebsten" }
  ,
  { rank: Rank 478, english: "size", word: "die Größe" }
  ,
  { rank: Rank 479, english: "good → better → best", word: "gut → besser → am besten" }
  ,
  { rank: Rank 480, english: "handbag", word: "die Handtasche" }
  ,
  { rank: Rank 481, english: "shirt", word: "das Hemd" }
  ,
  { rank: Rank 482, english: "trousers / pants", word: "die Hose" }
  ,
  { rank: Rank 483, english: "pretty / good-looking", word: "hübsch" }
  ,
  { rank: Rank 484, english: "hat", word: "der Hut" }
  ,
  { rank: Rank 485, english: "intelligent", word: "intelligent" }
  ,
  { rank: Rank 486, english: "jacket", word: "die Jacke" }
  ,
  { rank: Rank 487, english: "jeans", word: "die Jeans" }
  ,
  { rank: Rank 488, english: "young", word: "jung" }
  ,
  { rank: Rank 489, english: "dress", word: "das Kleid" }
  ,
  { rank: Rank 490, english: "comparative", word: "der Komparativ" }
  ,
  { rank: Rank 491, english: "subjunctive II (polite)", word: "der Konjunktiv II" }
  ,
  { rank: Rank 492, english: "short", word: "kurz" }
  ,
  { rank: Rank 493, english: "long", word: "lang" }
  ,
  { rank: Rank 494, english: "coat", word: "der Mantel" }
  ,
  { rank: Rank 495, english: "opinion", word: "die Meinung" }
  ,
  { rank: Rank 496, english: "operation", word: "die Operation" }
  ,
  { rank: Rank 497, english: "optimistic", word: "optimistisch" }
  ,
  { rank: Rank 498, english: "to fit", word: "passen" }
  ,
  { rank: Rank 499, english: "pessimistic", word: "pessimistisch" }
  ,
  { rank: Rank 500, english: "to try (on)", word: "probieren" }
  ,
  { rank: Rank 501, english: "pullover / jumper", word: "der Pullover" }
  ,
  { rank: Rank 502, english: "discount", word: "der Rabatt" }
  ,
  { rank: Rank 503, english: "smoking ban", word: "das Rauchverbot" }
  ,
  { rank: Rank 504, english: "to be right", word: "recht haben" }
  ,
  { rank: Rank 505, english: "skirt", word: "der Rock" }
  ,
  { rank: Rank 506, english: "calm / quiet", word: "ruhig" }
  ,
  { rank: Rank 507, english: "seamstress / tailor (female)", word: "die Schneiderin" }
  ,
  { rank: Rank 508, english: "cosmetic surgeon", word: "der Schönheitschirurg" }
  ,
  { rank: Rank 509, english: "cosmetic surgery", word: "die Schönheitsoperation" }
  ,
  { rank: Rank 510, english: "shoes", word: "die Schuhe" }
  ,
  { rank: Rank 511, english: "as ... as", word: "so ... wie" }
  ,
  { rank: Rank 512, english: "immediately / right away", word: "sofort" }
  ,
  { rank: Rank 513, english: "special offer", word: "das Sonderangebot" }
  ,
  { rank: Rank 514, english: "sporty / athletic", word: "sportlich" }
  ,
  { rank: Rank 515, english: "boots", word: "die Stiefel" }
  ,
  { rank: Rank 516, english: "voice", word: "die Stimme" }
  ,
  { rank: Rank 517, english: "superlative", word: "der Superlativ" }
  ,
  { rank: Rank 518, english: "T-shirt", word: "das T-Shirt" }
  ,
  { rank: Rank 519, english: "changing room / fitting room", word: "die Umkleidekabine" }
  ,
  { rank: Rank 520, english: "not dangerous / safe", word: "ungefährlich" }
  ,
  { rank: Rank 521, english: "unpleasant / unlikeable", word: "unsympathisch" }
  ,
  { rank: Rank 522, english: "salesman", word: "der Verkäufer" }
  ,
  { rank: Rank 523, english: "much → more → most", word: "viel → mehr → am meisten" }
  ,
  { rank: Rank 524, english: "wide / loose", word: "weit" }
  ,
  { rank: Rank 525, english: "too big / too small", word: "zu groß / zu klein" }
  ,
  { rank: Rank 526, english: "to depart", word: "abfahren" }
  ,
  { rank: Rank 527, english: "to arrive", word: "ankommen" }
  ,
  { rank: Rank 528, english: "day trip, excursion", word: "der Ausflug" }
  ,
  { rank: Rank 529, english: "mountain", word: "der Berg" }
  ,
  { rank: Rank 530, english: "to visit, to sightsee", word: "besichtigen" }
  ,
  { rank: Rank 531, english: "cloudy", word: "bewölkt" }
  ,
  { rank: Rank 532, english: "flight", word: "der Flug" }
  ,
  { rank: Rank 533, english: "to photograph", word: "fotografieren" }
  ,
  { rank: Rank 534, english: "to enjoy", word: "genießen" }
  ,
  { rank: Rank 535, english: "thunderstorm", word: "das Gewitter" }
  ,
  { rank: Rank 536, english: "hot", word: "heiß" }
  ,
  { rank: Rank 537, english: "hostel", word: "das Hostel" }
  ,
  { rank: Rank 538, english: "cold", word: "kalt" }
  ,
  { rank: Rank 539, english: "camera", word: "die Kamera" }
  ,
  { rank: Rank 540, english: "church", word: "die Kirche" }
  ,
  { rank: Rank 541, english: "last summer", word: "letzten Sommer" }
  ,
  { rank: Rank 542, english: "market", word: "der Markt" }
  ,
  { rank: Rank 543, english: "fog", word: "der Nebel" }
  ,
  { rank: Rank 544, english: "to pack", word: "packen" }
  ,
  { rank: Rank 545, english: "passport", word: "der Pass" }
  ,
  { rank: Rank 546, english: "postcard", word: "die Postkarte" }
  ,
  { rank: Rank 547, english: "rain", word: "der Regen" }
  ,
  { rank: Rank 548, english: "rainy", word: "regnerisch" }
  ,
  { rank: Rank 549, english: "to travel", word: "reisen" }
  ,
  { rank: Rank 550, english: "reservation", word: "die Reservierung" }
  ,
  { rank: Rank 551, english: "snow", word: "der Schnee" }
  ,
  { rank: Rank 552, english: "to have nice weather", word: "schönes Wetter haben" }
  ,
  { rank: Rank 553, english: "sight, tourist attraction", word: "die Sehenswürdigkeit" }
  ,
  { rank: Rank 554, english: "sunny", word: "sonnig" }
  ,
  { rank: Rank 555, english: "souvenir", word: "das Souvenir" }
  ,
  { rank: Rank 556, english: "stem (of a verb)", word: "der Stamm" }
  ,
  { rank: Rank 557, english: "taxi", word: "das Taxi" }
  ,
  { rank: Rank 558, english: "ticket", word: "das Ticket" }
  ,
  { rank: Rank 559, english: "tourist", word: "der Tourist" }
  ,
  { rank: Rank 560, english: "tourist information office", word: "die Touristeninformation" }
  ,
  { rank: Rank 561, english: "to stay overnight", word: "übernachten" }
  ,
  { rank: Rank 562, english: "irregular", word: "unregelmäßig" }
  ,
  { rank: Rank 563, english: "a year ago", word: "vor einem Jahr" }
  ,
  { rank: Rank 564, english: "narrative past", word: "die Vorvergangenheit" }
  ,
  { rank: Rank 565, english: "forest", word: "der Wald" }
  ,
  { rank: Rank 566, english: "to hike", word: "wandern" }
  ,
  { rank: Rank 567, english: "warm", word: "warm" }
  ,
  { rank: Rank 568, english: "weather", word: "das Wetter" }
  ,
  { rank: Rank 569, english: "wind", word: "der Wind" }
  ,
  { rank: Rank 570, english: "for the first time", word: "zum ersten Mal" }
  ,
  { rank: Rank 571, english: "allergy", word: "die Allergie" }
  ,
  { rank: Rank 572, english: "arm", word: "der Arm" }
  ,
  { rank: Rank 573, english: "aspirin", word: "das Aspirin" }
  ,
  { rank: Rank 574, english: "sufficiently", word: "ausreichend" }
  ,
  { rank: Rank 575, english: "belly, stomach", word: "der Bauch" }
  ,
  { rank: Rank 576, english: "leg", word: "das Bein" }
  ,
  { rank: Rank 577, english: "please", word: "Bitte" }
  ,
  { rank: Rank 578, english: "chest, breast", word: "die Brust" }
  ,
  { rank: Rank 579, english: "may, to be allowed to", word: "dürfen" }
  ,
  { rank: Rank 580, english: "Get well!", word: "Erhol dich!" }
  ,
  { rank: Rank 581, english: "fever", word: "das Fieber" }
  ,
  { rank: Rank 582, english: "finger", word: "der Finger" }
  ,
  { rank: Rank 583, english: "foot", word: "der Fuß" }
  ,
  { rank: Rank 584, english: "flu", word: "die Grippe" }
  ,
  { rank: Rank 585, english: "neck, throat", word: "der Hals" }
  ,
  { rank: Rank 586, english: "sore throat", word: "Halsschmerzen (Pl.)" }
  ,
  { rank: Rank 587, english: "imperative (grammar)", word: "der Imperativ" }
  ,
  { rank: Rank 588, english: "knee", word: "das Knie" }
  ,
  { rank: Rank 589, english: "headache", word: "der Kopfschmerz" }
  ,
  { rank: Rank 590, english: "sick, ill", word: "krank" }
  ,
  { rank: Rank 591, english: "health insurance", word: "die Krankenkasse" }
  ,
  { rank: Rank 592, english: "health insurance", word: "die Krankenversicherung" }
  ,
  { rank: Rank 593, english: "mouth", word: "der Mund" }
  ,
  { rank: Rank 594, english: "nose", word: "die Nase" }
  ,
  { rank: Rank 595, english: "ear", word: "das Ohr" }
  ,
  { rank: Rank 596, english: "patient (male)", word: "der Patient" }
  ,
  { rank: Rank 597, english: "patient (female)", word: "die Patientin" }
  ,
  { rank: Rank 598, english: "advice", word: "der Rat" }
  ,
  { rank: Rank 599, english: "reflexive pronoun", word: "das Reflexivpronomen" }
  ,
  { rank: Rank 600, english: "back", word: "der Rücken" }
  ,
  { rank: Rank 601, english: "Get some rest!", word: "Ruh dich aus!" }
  ,
  { rank: Rank 602, english: "to rest", word: "ruhen" }
  ,
  { rank: Rank 603, english: "to swallow", word: "schlucken" }
  ,
  { rank: Rank 604, english: "to have pain", word: "Schmerzen haben" }
  ,
  { rank: Rank 605, english: "shoulder", word: "die Schulter" }
  ,
  { rank: Rank 606, english: "to rest, to relax", word: "sich ausruhen" }
  ,
  { rank: Rank 607, english: "to move, to exercise", word: "sich bewegen" }
  ,
  { rank: Rank 608, english: "to recover", word: "sich erholen" }
  ,
  { rank: Rank 609, english: "to catch a cold", word: "sich erkälten" }
  ,
  { rank: Rank 610, english: "to eat, to nourish oneself", word: "sich ernähren" }
  ,
  { rank: Rank 611, english: "to feel", word: "sich fühlen" }
  ,
  { rank: Rank 612, english: "to worry", word: "sich Sorgen machen" }
  ,
  { rank: Rank 613, english: "should, ought to", word: "sollen" }
  ,
  { rank: Rank 614, english: "consultation hours", word: "die Sprechstunde" }
  ,
  { rank: Rank 615, english: "symptom", word: "das Symptom" }
  ,
  { rank: Rank 616, english: "daily", word: "täglich" }
  ,
  { rank: Rank 617, english: "appointment", word: "der Termin" }
  ,
  { rank: Rank 618, english: "to examine", word: "untersuchen" }
  ,
  { rank: Rank 619, english: "to hurt", word: "wehtun" }
  ,
  { rank: Rank 620, english: "when / whenever", word: "wenn" }
  ,
  { rank: Rank 621, english: "most of all / best of all", word: "am liebsten" }
  ,
  { rank: Rank 622, english: "at, on (vertical)", word: "an" }
  ,
  { rank: Rank 623, english: "apartment", word: "das Apartment" }
  ,
  { rank: Rank 624, english: "on (horizontal)", word: "auf" }
  ,
  { rank: Rank 625, english: "bathroom", word: "das Badezimmer" }
  ,
  { rank: Rank 626, english: "to build", word: "bauen" }
  ,
  { rank: Rank 627, english: "floor", word: "der Boden" }
  ,
  { rank: Rank 628, english: "bookshelf", word: "das Bücherregal" }
  ,
  { rank: Rank 629, english: "dark", word: "dunkel" }
  ,
  { rank: Rank 630, english: "to move in", word: "einziehen" }
  ,
  { rank: Rank 631, english: "colour / paint", word: "die Farbe" }
  ,
  { rank: Rank 632, english: "finished / ready", word: "fertig" }
  ,
  { rank: Rank 633, english: "hallway", word: "der Flur" }
  ,
  { rank: Rank 634, english: "dish / meal", word: "das Gericht" }
  ,
  { rank: Rank 635, english: "cheap / good value", word: "günstig" }
  ,
  { rank: Rank 636, english: "craftsman / tradesman", word: "der Handwerker" }
  ,
  { rank: Rank 637, english: "to hang", word: "hängen" }
  ,
  { rank: Rank 638, english: "main course", word: "das Hauptgericht" }
  ,
  { rank: Rank 639, english: "bright / light", word: "hell" }
  ,
  { rank: Rank 640, english: "behind", word: "hinter" }
  ,
  { rank: Rank 641, english: "ideal", word: "ideal" }
  ,
  { rank: Rank 642, english: "in, into", word: "in" }
  ,
  { rank: Rank 643, english: "broken", word: "kaputt" }
  ,
  { rank: Rank 644, english: "waiter", word: "der Kellner" }
  ,
  { rank: Rank 645, english: "waitress", word: "die Kellnerin" }
  ,
  { rank: Rank 646, english: "cushion / pillow", word: "das Kissen" }
  ,
  { rank: Rank 647, english: "kitchen", word: "die Küche" }
  ,
  { rank: Rank 648, english: "lamp", word: "die Lampe" }
  ,
  { rank: Rank 649, english: "to lay, to put (flat)", word: "legen" }
  ,
  { rank: Rank 650, english: "rather / preferably", word: "lieber" }
  ,
  { rank: Rank 651, english: "painter (decorator)", word: "der Maler" }
  ,
  { rank: Rank 652, english: "rent", word: "die Miete" }
  ,
  { rank: Rank 653, english: "furniture", word: "die Möbel" }
  ,
  { rank: Rank 654, english: "modern", word: "modern" }
  ,
  { rank: Rank 655, english: "dessert", word: "die Nachspeise" }
  ,
  { rank: Rank 656, english: "next to", word: "neben" }
  ,
  { rank: Rank 657, english: "parquet (flooring)", word: "das Parkett" }
  ,
  { rank: Rank 658, english: "square metre", word: "der Quadratmeter (m²)" }
  ,
  { rank: Rank 659, english: "bill", word: "die Rechnung" }
  ,
  { rank: Rank 660, english: "shelf / bookcase", word: "das Regal" }
  ,
  { rank: Rank 661, english: "to renovate", word: "renovieren" }
  ,
  { rank: Rank 662, english: "renovation", word: "die Renovierung" }
  ,
  { rank: Rank 663, english: "to repair", word: "reparieren" }
  ,
  { rank: Rank 664, english: "restaurant", word: "das Restaurant" }
  ,
  { rank: Rank 665, english: "bedroom", word: "das Schlafzimmer" }
  ,
  { rank: Rank 666, english: "wardrobe / cupboard", word: "der Schrank" }
  ,
  { rank: Rank 667, english: "armchair", word: "der Sessel" }
  ,
  { rank: Rank 668, english: "sofa", word: "das Sofa" }
  ,
  { rank: Rank 669, english: "menu", word: "die Speisekarte" }
  ,
  { rank: Rank 670, english: "to paint (walls)", word: "streichen" }
  ,
  { rank: Rank 671, english: "studio (flat)", word: "das Studio" }
  ,
  { rank: Rank 672, english: "rug / carpet", word: "der Teppich" }
  ,
  { rank: Rank 673, english: "expensive", word: "teuer" }
  ,
  { rank: Rank 674, english: "over, above", word: "über" }
  ,
  { rank: Rank 675, english: "to move (house)", word: "umziehen" }
  ,
  { rank: Rank 676, english: "under", word: "unter" }
  ,
  { rank: Rank 677, english: "landlord", word: "der Vermieter" }
  ,
  { rank: Rank 678, english: "landlady", word: "die Vermieterin" }
  ,
  { rank: Rank 679, english: "in front of", word: "vor" }
  ,
  { rank: Rank 680, english: "starter", word: "die Vorspeise" }
  ,
  { rank: Rank 681, english: "wall", word: "die Wand" }
  ,
  { rank: Rank 682, english: "to become", word: "werden" }
  ,
  { rank: Rank 683, english: "flat / apartment", word: "die Wohnung" }
  ,
  { rank: Rank 684, english: "living room", word: "das Wohnzimmer" }
  ,
  { rank: Rank 685, english: "wish", word: "der Wunsch" }
  ,
  { rank: Rank 686, english: "room", word: "das Zimmer" }
  ,
  { rank: Rank 687, english: "between", word: "zwischen" }
  ,
  { rank: Rank 688, english: "school-leaving exam (D)", word: "das Abitur" }
  ,
  { rank: Rank 689, english: "graduation, degree", word: "der Abschluss" }
  ,
  { rank: Rank 690, english: "than (in comparisons)", word: "als" }
  ,
  { rank: Rank 691, english: "if I were you", word: "an deiner Stelle" }
  ,
  { rank: Rank 692, english: "in your position (formal)", word: "an Ihrer Stelle" }
  ,
  { rank: Rank 693, english: "doctor (male)", word: "der Arzt" }
  ,
  { rank: Rank 694, english: "doctor (female)", word: "die Ärztin" }
  ,
  { rank: Rank 695, english: "astronaut (male)", word: "der Astronaut" }
  ,
  { rank: Rank 696, english: "vocational training", word: "die Ausbildung" }
  ,
  { rank: Rank 697, english: "profession, job", word: "der Beruf" }
  ,
  { rank: Rank 698, english: "vocational school", word: "die Berufsschule" }
  ,
  { rank: Rank 699, english: "job application", word: "die Bewerbung" }
  ,
  { rank: Rank 700, english: "therefore, that's why", word: "deshalb" }
  ,
  { rank: Rank 701, english: "mission, operation, deployment", word: "der Einsatz" }
  ,
  { rank: Rank 702, english: "fire", word: "das Feuer" }
  ,
  { rank: Rank 703, english: "firefighter (female)", word: "die Feuerwehrfrau" }
  ,
  { rank: Rank 704, english: "firefighter (male)", word: "der Feuerwehrmann" }
  ,
  { rank: Rank 705, english: "danger", word: "die Gefahr" }
  ,
  { rank: Rank 706, english: "contrast, opposite", word: "der Gegensatz" }
  ,
  { rank: Rank 707, english: "primary school", word: "die Grundschule" }
  ,
  { rank: Rank 708, english: "academic secondary school", word: "das Gymnasium" }
  ,
  { rank: Rank 709, english: "lower secondary school (D)", word: "die Hauptschule" }
  ,
  { rank: Rank 710, english: "in (temporal, with dative)", word: "in + Dativ (zeitlich)" }
  ,
  { rank: Rank 711, english: "in one year", word: "in einem Jahr" }
  ,
  { rank: Rank 712, english: "in two weeks", word: "in zwei Wochen" }
  ,
  { rank: Rank 713, english: "every, each", word: "jeder / jedes / jede" }
  ,
  { rank: Rank 714, english: "physical", word: "körperlich" }
  ,
  { rank: Rank 715, english: "CV, résumé", word: "der Lebenslauf" }
  ,
  { rank: Rank 716, english: "to extinguish", word: "löschen" }
  ,
  { rank: Rank 717, english: "school-leaving exam (A/CH)", word: "die Matura" }
  ,
  { rank: Rank 718, english: "disadvantage", word: "der Nachteil" }
  ,
  { rank: Rank 719, english: "although, even though", word: "obwohl" }
  ,
  { rank: Rank 720, english: "pilot (male)", word: "der Pilot" }
  ,
  { rank: Rank 721, english: "pilot (female)", word: "die Pilotin" }
  ,
  { rank: Rank 722, english: "police officer (male)", word: "der Polizist" }
  ,
  { rank: Rank 723, english: "police officer (female)", word: "die Polizistin" }
  ,
  { rank: Rank 724, english: "psychological, mental", word: "psychisch" }
  ,
  { rank: Rank 725, english: "career change, lateral entry", word: "der Quereinstieg" }
  ,
  { rank: Rank 726, english: "piece of advice", word: "der Ratschlag" }
  ,
  { rank: Rank 727, english: "intermediate secondary school", word: "die Realschule" }
  ,
  { rank: Rank 728, english: "to save, to rescue", word: "retten" }
  ,
  { rank: Rank 729, english: "risky", word: "riskant" }
  ,
  { rank: Rank 730, english: "to apply (for a job)", word: "sich bewerben" }
  ,
  { rank: Rank 731, english: "exciting, thrilling", word: "spannend" }
  ,
  { rank: Rank 732, english: "stress", word: "der Stress" }
  ,
  { rank: Rank 733, english: "university studies", word: "das Studium" }
  ,
  { rank: Rank 734, english: "dream job", word: "der Traumberuf" }
  ,
  { rank: Rank 735, english: "nevertheless, still, anyway", word: "trotzdem" }
  ,
  { rank: Rank 736, english: "to consider, to think about", word: "überlegen" }
  ,
  { rank: Rank 737, english: "around", word: "um ... herum" }
  ,
  { rank: Rank 738, english: "university", word: "die Universität" }
  ,
  { rank: Rank 739, english: "advantage", word: "der Vorteil" }
  ,
  { rank: Rank 740, english: "to change, to switch", word: "wechseln" }
  ,
  { rank: Rank 741, english: "government office", word: "das Amt" }
  ,
  { rank: Rank 742, english: "exchange", word: "der Austausch" }
  ,
  { rank: Rank 743, english: "ID card", word: "der Ausweis" }
  ,
  { rank: Rank 744, english: "relationship", word: "die Beziehung" }
  ,
  { rank: Rank 745, english: "blind date", word: "das Blind Date" }
  ,
  { rank: Rank 746, english: "charm", word: "der Charme" }
  ,
  { rank: Rank 747, english: "dating show", word: "die Dating-Show" }
  ,
  { rank: Rank 748, english: "honest", word: "ehrlich" }
  ,
  { rank: Rank 749, english: "honesty", word: "die Ehrlichkeit" }
  ,
  { rank: Rank 750, english: "characteristic, quality", word: "die Eigenschaft" }
  ,
  { rank: Rank 751, english: "residents' registration office", word: "das Einwohnermeldeamt" }
  ,
  { rank: Rank 752, english: "form (document)", word: "das Formular" }
  ,
  { rank: Rank 753, english: "free time, leisure", word: "die Freizeit" }
  ,
  { rank: Rank 754, english: "fresh", word: "frisch" }
  ,
  { rank: Rank 755, english: "patience", word: "die Geduld" }
  ,
  { rank: Rank 756, english: "patient", word: "geduldig" }
  ,
  { rank: Rank 757, english: "stressed", word: "gestresst" }
  ,
  { rank: Rank 758, english: "hobby", word: "das Hobby" }
  ,
  { rank: Rank 759, english: "humour", word: "der Humor" }
  ,
  { rank: Rank 760, english: "boring", word: "langweilig" }
  ,
  { rank: Rank 761, english: "funny", word: "lustig" }
  ,
  { rank: Rank 762, english: "native speaker", word: "der Muttersprachler" }
  ,
  { rank: Rank 763, english: "nice, kind", word: "nett" }
  ,
  { rank: Rank 764, english: "curious, inquisitive", word: "neugierig" }
  ,
  { rank: Rank 765, english: "open, open-minded", word: "offen" }
  ,
  { rank: Rank 766, english: "personality", word: "die Persönlichkeit" }
  ,
  { rank: Rank 767, english: "profile", word: "das Profil" }
  ,
  { rank: Rank 768, english: "romantic", word: "romantisch" }
  ,
  { rank: Rank 769, english: "queue / snake", word: "die Schlange" }
  ,
  { rank: Rank 770, english: "to register", word: "sich anmelden" }
  ,
  { rank: Rank 771, english: "to hurry", word: "sich beeilen" }
  ,
  { rank: Rank 772, english: "to complain", word: "sich beschweren" }
  ,
  { rank: Rank 773, english: "to shower", word: "sich duschen" }
  ,
  { rank: Rank 774, english: "to relax", word: "sich entspannen" }
  ,
  { rank: Rank 775, english: "to comb (hair)", word: "sich kämmen" }
  ,
  { rank: Rank 776, english: "to get to know each other", word: "sich kennenlernen" }
  ,
  { rank: Rank 777, english: "to sit down", word: "sich setzen" }
  ,
  { rank: Rank 778, english: "to meet up", word: "sich treffen" }
  ,
  { rank: Rank 779, english: "to fall in love with", word: "sich verlieben" }
  ,
  { rank: Rank 780, english: "to get along", word: "sich verstehen" }
  ,
  { rank: Rank 781, english: "to introduce oneself", word: "sich vorstellen" }
  ,
  { rank: Rank 782, english: "to feel comfortable", word: "sich wohlfühlen" }
  ,
  { rank: Rank 783, english: "to wish for", word: "sich wünschen" }
  ,
  { rank: Rank 784, english: "language", word: "die Sprache" }
  ,
  { rank: Rank 785, english: "likeable / pleasant", word: "sympathisch" }
  ,
  { rank: Rank 786, english: "language exchange partner", word: "das Tandem" }
  ,
  { rank: Rank 787, english: "impatient", word: "ungeduldig" }
  ,
  { rank: Rank 788, english: "queue number", word: "die Wartenummer" }
  ,
  { rank: Rank 789, english: "reliable", word: "zuverlässig" }
  ,
  { rank: Rank 790, english: "in the evenings", word: "abends" }
  ,
  { rank: Rank 791, english: "balcony", word: "der Balkon" }
  ,
  { rank: Rank 792, english: "mountains", word: "die Berge" }
  ,
  { rank: Rank 793, english: "to describe", word: "beschreiben" }
  ,
  { rank: Rank 794, english: "width", word: "die Breite" }
  ,
  { rank: Rank 795, english: "to book", word: "buchen" }
  ,
  { rank: Rank 796, english: "camping", word: "das Camping" }
  ,
  { rank: Rank 797, english: "campsite", word: "der Campingplatz" }
  ,
  { rank: Rank 798, english: "of the father / of the mother", word: "des Vaters / der Mutter" }
  ,
  { rank: Rank 799, english: "double room", word: "das Doppelzimmer" }
  ,
  { rank: Rank 800, english: "single room", word: "das Einzelzimmer" }
  ,
  { rank: Rank 801, english: "memory, souvenir", word: "die Erinnerung" }
  ,
  { rank: Rank 802, english: "breakfast", word: "das Frühstück" }
  ,
  { rank: Rank 803, english: "lost property office", word: "das Fundbüro" }
  ,
  { rank: Rank 804, english: "genitive case", word: "der Genitiv" }
  ,
  { rank: Rank 805, english: "here (motion toward speaker)", word: "her" }
  ,
  { rank: Rank 806, english: "to come from", word: "herkommen" }
  ,
  { rank: Rank 807, english: "there (away from speaker)", word: "hin" }
  ,
  { rank: Rank 808, english: "to put down", word: "hinlegen" }
  ,
  { rank: Rank 809, english: "height", word: "die Höhe" }
  ,
  { rank: Rank 810, english: "hotel", word: "das Hotel" }
  ,
  { rank: Rank 811, english: "inclusive, included", word: "inklusive" }
  ,
  { rank: Rank 812, english: "island", word: "die Insel" }
  ,
  { rank: Rank 813, english: "youth hostel", word: "die Jugendherberge" }
  ,
  { rank: Rank 814, english: "childhood", word: "die Kindheit" }
  ,
  { rank: Rank 815, english: "suitcase", word: "der Koffer" }
  ,
  { rank: Rank 816, english: "coast", word: "die Küste" }
  ,
  { rank: Rank 817, english: "length", word: "die Länge" }
  ,
  { rank: Rank 818, english: "sea", word: "das Meer" }
  ,
  { rank: Rank 819, english: "to measure", word: "messen" }
  ,
  { rank: Rank 820, english: "on Mondays", word: "montags" }
  ,
  { rank: Rank 821, english: "in the mornings", word: "morgens" }
  ,
  { rank: Rank 822, english: "wallet, purse", word: "das Portemonnaie" }
  ,
  { rank: Rank 823, english: "umbrella", word: "der Regenschirm" }
  ,
  { rank: Rank 824, english: "trip, journey", word: "die Reise" }
  ,
  { rank: Rank 825, english: "record", word: "das Rekord" }
  ,
  { rank: Rank 826, english: "relative clause", word: "der Relativsatz" }
  ,
  { rank: Rank 827, english: "backpack", word: "der Rucksack" }
  ,
  { rank: Rank 828, english: "lake", word: "der See" }
  ,
  { rank: Rank 829, english: "sunglasses", word: "die Sonnenbrille" }
  ,
  { rank: Rank 830, english: "beach", word: "der Strand" }
  ,
  { rank: Rank 831, english: "overnight stay", word: "die Übernachtung" }
  ,
  { rank: Rank 832, english: "accommodation", word: "die Unterkunft" }
  ,
  { rank: Rank 833, english: "unforgettable", word: "unvergesslich" }
  ,
  { rank: Rank 834, english: "vacation, holiday", word: "der Urlaub" }
  ,
  { rank: Rank 835, english: "to spend (time)", word: "verbringen" }
  ,
  { rank: Rank 836, english: "to lose", word: "verlieren" }
  ,
  { rank: Rank 837, english: "world record", word: "der Weltrekord" }
  ,
  { rank: Rank 838, english: "tent", word: "das Zelt" }
  ,
  { rank: Rank 839, english: "to write down", word: "aufschreiben" }
  ,
  { rank: Rank 840, english: "impressive", word: "beeindruckend" }
  ,
  { rank: Rank 841, english: "cache (hidden object)", word: "der Cache" }
  ,
  { rank: Rank 842, english: "for that / for what", word: "dafür / wofür" }
  ,
  { rank: Rank 843, english: "about that / about what", word: "darüber / worüber" }
  ,
  { rank: Rank 844, english: "of/from that / of/from what", word: "davon / wovon" }
  ,
  { rank: Rank 845, english: "to agree, be in agreement", word: "einverstanden sein" }
  ,
  { rank: Rank 846, english: "festival", word: "das Festival" }
  ,
  { rank: Rank 847, english: "flash mob", word: "der Flash Mob" }
  ,
  { rank: Rank 848, english: "geocaching", word: "das Geocaching" }
  ,
  { rank: Rank 849, english: "interesting", word: "interessant" }
  ,
  { rank: Rank 850, english: "flashcard", word: "die Karteikarte" }
  ,
  { rank: Rank 851, english: "no problem", word: "kein Problem" }
  ,
  { rank: Rank 852, english: "cinema", word: "das Kino" }
  ,
  { rank: Rank 853, english: "to work out, to go as planned", word: "klappen" }
  ,
  { rank: Rank 854, english: "concert", word: "das Konzert" }
  ,
  { rank: Rank 855, english: "culture", word: "die Kultur" }
  ,
  { rank: Rank 856, english: "cultural", word: "kulturell" }
  ,
  { rank: Rank 857, english: "art", word: "die Kunst" }
  ,
  { rank: Rank 858, english: "unfortunately", word: "leider" }
  ,
  { rank: Rank 859, english: "to participate", word: "mitmachen" }
  ,
  { rank: Rank 860, english: "museum", word: "das Museum" }
  ,
  { rank: Rank 861, english: "music", word: "die Musik" }
  ,
  { rank: Rank 862, english: "to think about", word: "nachdenken" }
  ,
  { rank: Rank 863, english: "public", word: "öffentlich" }
  ,
  { rank: Rank 864, english: "to organize", word: "organisieren" }
  ,
  { rank: Rank 865, english: "regular", word: "regelmäßig" }
  ,
  { rank: Rank 866, english: "to be enthusiastic about", word: "sich begeistern" }
  ,
  { rank: Rank 867, english: "to look forward to", word: "sich freuen auf" }
  ,
  { rank: Rank 868, english: "to be happy about", word: "sich freuen über" }
  ,
  { rank: Rank 869, english: "to be interested in", word: "sich interessieren" }
  ,
  { rank: Rank 870, english: "to arrange to meet", word: "sich verabreden" }
  ,
  { rank: Rank 871, english: "language learning app", word: "das Sprachlernapp" }
  ,
  { rank: Rank 872, english: "strategy", word: "die Strategie" }
  ,
  { rank: Rank 873, english: "theatre", word: "das Theater" }
  ,
  { rank: Rank 874, english: "tip, piece of advice", word: "der Tipp" }
  ,
  { rank: Rank 875, english: "to dream of", word: "träumen" }
  ,
  { rank: Rank 876, english: "meeting point", word: "der Treffpunkt" }
  ,
  { rank: Rank 877, english: "date, appointment (informal)", word: "die Verabredung" }
  ,
  { rank: Rank 878, english: "vocabulary word", word: "die Vokabel" }
  ,
  { rank: Rank 879, english: "to intend, to plan", word: "vorhaben" }
  ,
  { rank: Rank 880, english: "suggestion, proposal", word: "der Vorschlag" }
  ,
  { rank: Rank 881, english: "to suggest", word: "vorschlagen" }
  ,
  { rank: Rank 882, english: "to repeat", word: "wiederholen" }
  ,
  { rank: Rank 883, english: "aggressive", word: "aggressiv" }
  ,
  { rank: Rank 884, english: "traffic light", word: "die Ampel" }
  ,
  { rank: Rank 885, english: "pharmacy", word: "die Apotheke" }
  ,
  { rank: Rank 886, english: "annoyance, anger", word: "der Ärger" }
  ,
  { rank: Rank 887, english: "to annoy, to anger", word: "ärgern" }
  ,
  { rank: Rank 888, english: "exciting", word: "aufregend" }
  ,
  { rank: Rank 889, english: "endurance, stamina", word: "die Ausdauer" }
  ,
  { rank: Rank 890, english: "car driver (male)", word: "der Autofahrer" }
  ,
  { rank: Rank 891, english: "car driver (female)", word: "die Autofahrerin" }
  ,
  { rank: Rank 892, english: "to brake", word: "bremsen" }
  ,
  { rank: Rank 893, english: "dosage", word: "die Dosierung" }
  ,
  { rank: Rank 894, english: "one (of them)", word: "einer" }
  ,
  { rank: Rank 895, english: "invitation", word: "die Einladung" }
  ,
  { rank: Rank 896, english: "to recommend", word: "empfehlen" }
  ,
  { rank: Rank 897, english: "to relax", word: "entspannen" }
  ,
  { rank: Rank 898, english: "inflammation, infection", word: "die Entzündung" }
  ,
  { rank: Rank 899, english: "cold (illness)", word: "die Erkältung" }
  ,
  { rank: Rank 900, english: "to explain", word: "erklären" }
  ,
  { rank: Rank 901, english: "explanation", word: "die Erklärung" }
  ,
  { rank: Rank 902, english: "extreme sport", word: "das Extremsport" }
  ,
  { rank: Rank 903, english: "driver (male)", word: "der Fahrer" }
  ,
  { rank: Rank 904, english: "driver (female)", word: "die Fahrerin" }
  ,
  { rank: Rank 905, english: "bicycle", word: "das Fahrrad" }
  ,
  { rank: Rank 906, english: "fit, in shape", word: "fit" }
  ,
  { rank: Rank 907, english: "gym, fitness studio", word: "das Fitnessstudio" }
  ,
  { rank: Rank 908, english: "pedestrian (male)", word: "der Fußgänger" }
  ,
  { rank: Rank 909, english: "dangerous", word: "gefährlich" }
  ,
  { rank: Rank 910, english: "pavement, sidewalk", word: "der Gehweg" }
  ,
  { rank: Rank 911, english: "healthy", word: "gesund" }
  ,
  { rank: Rank 912, english: "health", word: "die Gesundheit" }
  ,
  { rank: Rank 913, english: "action, plot", word: "die Handlung" }
  ,
  { rank: Rank 914, english: "helmet", word: "der Helm" }
  ,
  { rank: Rank 915, english: "to honk, to beep", word: "hupen" }
  ,
  { rank: Rank 916, english: "cough syrup", word: "der Hustensaft" }
  ,
  { rank: Rank 917, english: "none, no one", word: "keiner" }
  ,
  { rank: Rank 918, english: "to climb", word: "klettern" }
  ,
  { rank: Rank 919, english: "climbing (as activity noun)", word: "das Klettern" }
  ,
  { rank: Rank 920, english: "intersection, crossroads", word: "die Kreuzung" }
  ,
  { rank: Rank 921, english: "teacher (female)", word: "die Lehrerin" }
  ,
  { rank: Rank 922, english: "to lend", word: "leihen" }
  ,
  { rank: Rank 923, english: "medication, medicine", word: "das Medikament" }
  ,
  { rank: Rank 924, english: "mine", word: "meiner" }
  ,
  { rank: Rank 925, english: "courage", word: "der Mut" }
  ,
  { rank: Rank 926, english: "brave, courageous", word: "mutig" }
  ,
  { rank: Rank 927, english: "plaster, band-aid", word: "das Pflaster" }
  ,
  { rank: Rank 928, english: "suddenly", word: "plötzlich" }
  ,
  { rank: Rank 929, english: "cyclist (male)", word: "der Radfahrer" }
  ,
  { rank: Rank 930, english: "cyclist (female)", word: "die Radfahrerin" }
  ,
  { rank: Rank 931, english: "prescription", word: "das Rezept" }
  ,
  { rank: Rank 932, english: "prescription-only", word: "rezeptpflichtig" }
  ,
  { rank: Rank 933, english: "risk", word: "das Risiko" }
  ,
  { rank: Rank 934, english: "ointment, cream", word: "die Salbe" }
  ,
  { rank: Rank 935, english: "to be annoyed about", word: "sich ärgern" }
  ,
  { rank: Rank 936, english: "situation", word: "die Situation" }
  ,
  { rank: Rank 937, english: "skydiving", word: "das Skydiving" }
  ,
  { rank: Rank 938, english: "sport", word: "der Sport" }
  ,
  { rank: Rank 939, english: "athlete (male)", word: "der Sportler" }
  ,
  { rank: Rank 940, english: "athlete (female)", word: "die Sportlerin" }
  ,
  { rank: Rank 941, english: "traffic jam", word: "der Stau" }
  ,
  { rank: Rank 942, english: "surfing (as activity noun)", word: "das Surfen" }
  ,
  { rank: Rank 943, english: "tablet, pill", word: "die Tablette" }
  ,
  { rank: Rank 944, english: "to train, to exercise", word: "trainieren" }
  ,
  { rank: Rank 945, english: "to overtake", word: "überholen" }
  ,
  { rank: Rank 946, english: "exercise, practice", word: "die Übung" }
  ,
  { rank: Rank 947, english: "unhealthy", word: "ungesund" }
  ,
  { rank: Rank 948, english: "examination, investigation", word: "die Untersuchung" }
  ,
  { rank: Rank 949, english: "injury", word: "die Verletzung" }
  ,
  { rank: Rank 950, english: "to prescribe", word: "verschreiben" }
  ,
  { rank: Rank 951, english: "vitamin", word: "das Vitamin" }
  ,
  { rank: Rank 952, english: "word formation", word: "die Wortbildung" }
  ,
  { rank: Rank 953, english: "to wish", word: "wünschen" }
  ,
  { rank: Rank 954, english: "old", word: "alt" }
  ,
  { rank: Rank 955, english: "offered", word: "angeboten" }
  ,
  { rank: Rank 956, english: "stop", word: "anhalten" }
  ,
  { rank: Rank 957, english: "turn on", word: "anmachen" }
  ,
  { rank: Rank 958, english: "look at / regard", word: "ansehen" }
  ,
  { rank: Rank 959, english: "to answer", word: "antworten" }
  ,
  { rank: Rank 960, english: "workplace", word: "der Arbeitsplatz" }
  ,
  { rank: Rank 961, english: "exit", word: "der Ausgang" }
  ,
  { rank: Rank 962, english: "spend / issue", word: "ausgeben" }
  ,
  { rank: Rank 963, english: "go out / assume / run out", word: "ausgehen" }
  ,
  { rank: Rank 964, english: "except", word: "ausgenommen" }
  ,
  { rank: Rank 965, english: "pronunciation", word: "die Aussprache" }
  ,
  { rank: Rank 966, english: "take off / move out", word: "ausziehen" }
  ,
  { rank: Rank 967, english: "car", word: "das Auto" }
  ,
  { rank: Rank 968, english: "to mean", word: "bedeuten" }
  ,
  { rank: Rank 969, english: "to begin", word: "beginnen" }
  ,
  { rank: Rank 970, english: "to bite", word: "beißen" }
  ,
  { rank: Rank 971, english: "known / familiar", word: "bekannt" }
  ,
  { rank: Rank 972, english: "to visit", word: "besuchen" }
  ,
  { rank: Rank 973, english: "to pay", word: "bezahlen" }
  ,
  { rank: Rank 974, english: "to offer", word: "bieten" }
  ,
  { rank: Rank 975, english: "to ask, request", word: "bitten" }
  ,
  { rank: Rank 976, english: "to blow", word: "blasen" }
  ,
  { rank: Rank 977, english: "flower", word: "die Blume" }
  ,
  { rank: Rank 978, english: "to roast, fry", word: "braten" }
  ,
  { rank: Rank 979, english: "to break", word: "brechen" }
  ,
  { rank: Rank 980, english: "to burn", word: "brennen" }
  ,
  { rank: Rank 981, english: "to bring", word: "bringen" }
  ,
  { rank: Rank 982, english: "to think", word: "denken" }
  ,
  { rank: Rank 983, english: "you (informal)", word: "du" }
  ,
  { rank: Rank 984, english: "thirsty", word: "durstig" }
  ,
  { rank: Rank 985, english: "entrance", word: "der Eingang" }
  ,
  { rank: Rank 986, english: "shopping / purchase", word: "der Einkauf" }
  ,
  { rank: Rank 987, english: "income", word: "das Einkommen" }
  ,
  { rank: Rank 988, english: "to excuse/apologize", word: "entschuldigen" }
  ,
  { rank: Rank 989, english: "he", word: "er" }
  ,
  { rank: Rank 990, english: "to recognize", word: "erkennen" }
  ,
  { rank: Rank 991, english: "to allow", word: "erlauben" }
  ,
  { rank: Rank 992, english: "to reach", word: "erreichen" }
  ,
  { rank: Rank 993, english: "to expect", word: "erwarten" }
  ,
  { rank: Rank 994, english: "to tell/narrate", word: "erzählen" }
  ,
  { rank: Rank 995, english: "ticket", word: "die Fahrkarte" }
  ,
  { rank: Rank 996, english: "timetable", word: "der Fahrplan" }
  ,
  { rank: Rank 997, english: "trip", word: "die Fahrt" }
  ,
  { rank: Rank 998, english: "vehicle", word: "das Fahrzeug" }
  ,
  { rank: Rank 999, english: "to fall", word: "fallen" }
  ,
  { rank: Rank 1000, english: "to catch", word: "fangen" }
  ,
  { rank: Rank 1001, english: "thanks, thank you", word: "danke" }
  ,
  { rank: Rank 1002, english: "bye", word: "tschüss" }
  ,
  { rank: Rank 1003, english: "maybe, perhaps", word: "vielleicht" }
  ,
  { rank: Rank 1004, english: "of course, naturally", word: "natürlich" }
  ,
  { rank: Rank 1005, english: "once; softens a request", word: "mal" }
  ]
