-- | GENERATED by tools/sync-deck.mjs - do not edit.
-- |
-- | Source: data/es-1000.csv (1000 words, ordered by frequency, most common first).
module Flashcards.Data.Deck.Spanish
  ( deck
  , fingerprint
  )
  where

import Flashcards.Types.Card (Card, Rank(..))

-- | Content hash of what each rank means. Progress is keyed by rank, so a deck
-- | whose rows were renumbered is a different deck as far as saved progress is
-- | concerned.
fingerprint :: String
fingerprint = "654958a3f958"

-- | The index into this deck is meaningful: it is the order cards are
-- | introduced in.
deck :: Array Card
deck =
  [
  { rank: Rank 1, english: "I", word: "yo" }
  ,
  { rank: Rank 2, english: "to want", word: "querer" }
  ,
  { rank: Rank 3, english: "this", word: "este" }
  ,
  { rank: Rank 4, english: "yes", word: "sí" }
  ,
  { rank: Rank 5, english: "no", word: "no" }
  ,
  { rank: Rank 6, english: "to be able to", word: "poder" }
  ,
  { rank: Rank 7, english: "to speak", word: "hablar" }
  ,
  { rank: Rank 8, english: "to find", word: "encontrar" }
  ,
  { rank: Rank 9, english: "to have (own)", word: "tener" }
  ,
  { rank: Rank 10, english: "to need", word: "necesitar" }
  ,
  { rank: Rank 11, english: "where (the place that)", word: "donde" }
  ,
  { rank: Rank 12, english: "that (linking clauses)", word: "que" }
  ,
  { rank: Rank 13, english: "the", word: "el / la" }
  ,
  { rank: Rank 14, english: "place", word: "lugar" }
  ,
  { rank: Rank 15, english: "home", word: "casa" }
  ,
  { rank: Rank 16, english: "something", word: "algo" }
  ,
  { rank: Rank 17, english: "that (near you)", word: "ese" }
  ,
  { rank: Rank 18, english: "and", word: "y" }
  ,
  { rank: Rank 19, english: "to see", word: "ver" }
  ,
  { rank: Rank 20, english: "but", word: "pero" }
  ,
  { rank: Rank 21, english: "to go (go away/leave)", word: "ir(se)" }
  ,
  { rank: Rank 22, english: "to, at", word: "a" }
  ,
  { rank: Rank 23, english: "to say", word: "decir" }
  ,
  { rank: Rank 24, english: "or", word: "o" }
  ,
  { rank: Rank 25, english: "a", word: "un" }
  ,
  { rank: Rank 26, english: "more", word: "más" }
  ,
  { rank: Rank 27, english: "as, like", word: "como" }
  ,
  { rank: Rank 28, english: "is, oneself", word: "se" }
  ,
  { rank: Rank 29, english: "to come", word: "venir" }
  ,
  { rank: Rank 30, english: "my", word: "mi" }
  ,
  { rank: Rank 31, english: "to be (what it is)", word: "ser" }
  ,
  { rank: Rank 32, english: "to be (how or where it is)", word: "estar" }
  ,
  { rank: Rank 33, english: "to live", word: "vivir" }
  ,
  { rank: Rank 34, english: "to pass", word: "pasar" }
  ,
  { rank: Rank 35, english: "day", word: "día" }
  ,
  { rank: Rank 36, english: "year", word: "año" }
  ,
  { rank: Rank 37, english: "week", word: "semana" }
  ,
  { rank: Rank 38, english: "month", word: "mes" }
  ,
  { rank: Rank 39, english: "each", word: "cada" }
  ,
  { rank: Rank 40, english: "time (duration)", word: "tiempo" }
  ,
  { rank: Rank 41, english: "to know", word: "saber" }
  ,
  { rank: Rank 42, english: "to know (be familiar with)", word: "conocer" }
  ,
  { rank: Rank 43, english: "to do", word: "hacer" }
  ,
  { rank: Rank 44, english: "to practice", word: "practicar" }
  ,
  { rank: Rank 45, english: "to arrive", word: "llegar" }
  ,
  { rank: Rank 46, english: "too, also", word: "también" }
  ,
  { rank: Rank 47, english: "when", word: "cuando" }
  ,
  { rank: Rank 48, english: "until", word: "hasta" }
  ,
  { rank: Rank 49, english: "morning", word: "mañana" }
  ,
  { rank: Rank 50, english: "he / she", word: "él / ella" }
  ,
  { rank: Rank 51, english: "is pleasing to (to like)", word: "gustar" }
  ,
  { rank: Rank 52, english: "me", word: "me" }
  ,
  { rank: Rank 53, english: "you (one person, object)", word: "te" }
  ,
  { rank: Rank 54, english: "you, him, her", word: "le" }
  ,
  { rank: Rank 55, english: "us (object)", word: "nos" }
  ,
  { rank: Rank 56, english: "them", word: "les" }
  ,
  { rank: Rank 57, english: "friend", word: "amigo" }
  ,
  { rank: Rank 58, english: "food", word: "comida" }
  ,
  { rank: Rank 59, english: "other", word: "otro" }
  ,
  { rank: Rank 60, english: "work (job)", word: "trabajo" }
  ,
  { rank: Rank 61, english: "for, through", word: "por" }
  ,
  { rank: Rank 62, english: "for, in order to", word: "para" }
  ,
  { rank: Rank 63, english: "example", word: "ejemplo" }
  ,
  { rank: Rank 64, english: "of", word: "de" }
  ,
  { rank: Rank 65, english: "in, on", word: "en" }
  ,
  { rank: Rank 66, english: "with", word: "con" }
  ,
  { rank: Rank 67, english: "to give", word: "dar" }
  ,
  { rank: Rank 68, english: "country", word: "país" }
  ,
  { rank: Rank 69, english: "man", word: "hombre" }
  ,
  { rank: Rank 70, english: "woman", word: "mujer" }
  ,
  { rank: Rank 71, english: "to have (done something)", word: "haber" }
  ,
  { rank: Rank 72, english: "very", word: "muy" }
  ,
  { rank: Rank 73, english: "much", word: "mucho" }
  ,
  { rank: Rank 74, english: "large", word: "grande" }
  ,
  { rank: Rank 75, english: "less", word: "menos" }
  ,
  { rank: Rank 76, english: "little", word: "poco" }
  ,
  { rank: Rank 77, english: "thing", word: "cosa" }
  ,
  { rank: Rank 78, english: "if", word: "si" }
  ,
  { rank: Rank 79, english: "our", word: "nuestro" }
  ,
  { rank: Rank 80, english: "always", word: "siempre" }
  ,
  { rank: Rank 81, english: "life", word: "vida" }
  ,
  { rank: Rank 82, english: "afterwards", word: "después" }
  ,
  { rank: Rank 83, english: "then", word: "entonces" }
  ,
  { rank: Rank 84, english: "to put, place", word: "poner" }
  ,
  { rank: Rank 85, english: "should, must, to owe", word: "deber" }
  ,
  { rank: Rank 86, english: "well (properly)", word: "bien" }
  ,
  { rank: Rank 87, english: "between", word: "entre" }
  ,
  { rank: Rank 88, english: "word", word: "palabra" }
  ,
  { rank: Rank 89, english: "now", word: "ahora" }
  ,
  { rank: Rank 90, english: "to learn", word: "aprender" }
  ,
  { rank: Rank 91, english: "your", word: "tu" }
  ,
  { rank: Rank 92, english: "to believe", word: "creer" }
  ,
  { rank: Rank 93, english: "is seeming to (to seem)", word: "parecer" }
  ,
  { rank: Rank 94, english: "nothing", word: "nada" }
  ,
  { rank: Rank 95, english: "all", word: "todo" }
  ,
  { rank: Rank 96, english: "because", word: "porque" }
  ,
  { rank: Rank 97, english: "to help", word: "ayudar" }
  ,
  { rank: Rank 98, english: "to ask for, to request", word: "pedir" }
  ,
  { rank: Rank 99, english: "to ask (a question)", word: "preguntar" }
  ,
  { rank: Rank 100, english: "what", word: "qué" }
  ,
  { rank: Rank 101, english: "it, the, him", word: "lo" }
  ,
  { rank: Rank 102, english: "his, her, their", word: "su" }
  ,
  { rank: Rank 103, english: "here", word: "aquí" }
  ,
  { rank: Rank 104, english: "already", word: "ya" }
  ,
  { rank: Rank 105, english: "without", word: "sin" }
  ,
  { rank: Rank 106, english: "time (an occasion)", word: "vez" }
  ,
  { rank: Rank 107, english: "there is, there are", word: "hay" }
  ,
  { rank: Rank 108, english: "on, about", word: "sobre" }
  ,
  { rank: Rank 109, english: "you (informal)", word: "tú" }
  ,
  { rank: Rank 110, english: "any, some", word: "alguno" }
  ,
  { rank: Rank 111, english: "same", word: "mismo" }
  ,
  { rank: Rank 112, english: "like that, so", word: "así" }
  ,
  { rank: Rank 113, english: "how", word: "cómo" }
  ,
  { rank: Rank 114, english: "two", word: "dos" }
  ,
  { rank: Rank 115, english: "only (pre-2010 spelling)", word: "sólo" }
  ,
  { rank: Rank 116, english: "first", word: "primero" }
  ,
  { rank: Rank 117, english: "from", word: "desde" }
  ,
  { rank: Rank 118, english: "nor", word: "ni" }
  ,
  { rank: Rank 119, english: "thanks", word: "gracias" }
  ,
  { rank: Rank 120, english: "good", word: "bueno" }
  ,
  { rank: Rank 121, english: "one", word: "uno" }
  ,
  { rank: Rank 122, english: "you (formal)", word: "usted" }
  ,
  { rank: Rank 123, english: "so many, so much", word: "tanto" }
  ,
  { rank: Rank 124, english: "Mr.", word: "señor" }
  ,
  { rank: Rank 125, english: "such, as, so", word: "tan" }
  ,
  { rank: Rank 126, english: "who", word: "quién" }
  ,
  { rank: Rank 127, english: "part", word: "parte" }
  ,
  { rank: Rank 128, english: "is remaining to (to stay)", word: "quedar" }
  ,
  { rank: Rank 129, english: "please", word: "por favor" }
  ,
  { rank: Rank 130, english: "where? (asking)", word: "dónde" }
  ,
  { rank: Rank 131, english: "never", word: "nunca" }
  ,
  { rank: Rank 132, english: "to lead", word: "llevar" }
  ,
  { rank: Rank 133, english: "to leave behind, to let", word: "dejar" }
  ,
  { rank: Rank 134, english: "truth", word: "verdad" }
  ,
  { rank: Rank 135, english: "to follow", word: "seguir" }
  ,
  { rank: Rank 136, english: "new", word: "nuevo" }
  ,
  { rank: Rank 137, english: "so, then", word: "pues" }
  ,
  { rank: Rank 138, english: "to call (be called/name)", word: "llamar(se)" }
  ,
  { rank: Rank 139, english: "best", word: "mejor" }
  ,
  { rank: Rank 140, english: "to think", word: "pensar" }
  ,
  { rank: Rank 141, english: "that (over there)", word: "aquel" }
  ,
  { rank: Rank 142, english: "moment", word: "momento" }
  ,
  { rank: Rank 143, english: "god", word: "dios" }
  ,
  { rank: Rank 144, english: "but, rather", word: "sino" }
  ,
  { rank: Rank 145, english: "to go out, to leave", word: "salir" }
  ,
  { rank: Rank 146, english: "to return", word: "volver" }
  ,
  { rank: Rank 147, english: "form", word: "forma" }
  ,
  { rank: Rank 148, english: "before (in time)", word: "antes" }
  ,
  { rank: Rank 149, english: "although", word: "aunque" }
  ,
  { rank: Rank 150, english: "world", word: "mundo" }
  ,
  { rank: Rank 151, english: "three", word: "tres" }
  ,
  { rank: Rank 152, english: "such", word: "tal" }
  ,
  { rank: Rank 153, english: "there", word: "ahí" }
  ,
  { rank: Rank 154, english: "to take, to drink", word: "tomar" }
  ,
  { rank: Rank 155, english: "certain", word: "cierto" }
  ,
  { rank: Rank 156, english: "to, towards", word: "hacia" }
  ,
  { rank: Rank 157, english: "case", word: "caso" }
  ,
  { rank: Rank 158, english: "night", word: "noche" }
  ,
  { rank: Rank 159, english: "to feel", word: "sentir" }
  ,
  { rank: Rank 160, english: "then, later", word: "luego" }
  ,
  { rank: Rank 161, english: "someone", word: "alguien" }
  ,
  { rank: Rank 162, english: "to treat, deal with", word: "tratar" }
  ,
  { rank: Rank 163, english: "person", word: "persona" }
  ,
  { rank: Rank 164, english: "higher", word: "mayor" }
  ,
  { rank: Rank 165, english: "last", word: "último" }
  ,
  { rank: Rank 166, english: "single", word: "solo" }
  ,
  { rank: Rank 167, english: "own", word: "propio" }
  ,
  { rank: Rank 168, english: "no one", word: "nadie" }
  ,
  { rank: Rank 169, english: "whoever", word: "quien" }
  ,
  { rank: Rank 170, english: "we", word: "nosotros" }
  ,
  { rank: Rank 171, english: "to look", word: "mirar" }
  ,
  { rank: Rank 172, english: "father", word: "padre" }
  ,
  { rank: Rank 173, english: "time, hour", word: "hora" }
  ,
  { rank: Rank 174, english: "people", word: "gente" }
  ,
  { rank: Rank 175, english: "none", word: "ninguno" }
  ,
  { rank: Rank 176, english: "money", word: "dinero" }
  ,
  { rank: Rank 177, english: "almost", word: "casi" }
  ,
  { rank: Rank 178, english: "point", word: "punto" }
  ,
  { rank: Rank 179, english: "done", word: "hecho" }
  ,
  { rank: Rank 180, english: "during", word: "durante" }
  ,
  { rank: Rank 181, english: "any", word: "cualquier" }
  ,
  { rank: Rank 182, english: "hand", word: "mano" }
  ,
  { rank: Rank 183, english: "way", word: "manera" }
  ,
  { rank: Rank 184, english: "which", word: "cual" }
  ,
  { rank: Rank 185, english: "while", word: "mientras" }
  ,
  { rank: Rank 186, english: "to count", word: "contar" }
  ,
  { rank: Rank 187, english: "end", word: "fin" }
  ,
  { rank: Rank 188, english: "type", word: "tipo" }
  ,
  { rank: Rank 189, english: "clear", word: "claro" }
  ,
  { rank: Rank 190, english: "also, besides", word: "además" }
  ,
  { rank: Rank 191, english: "to start", word: "empezar" }
  ,
  { rank: Rank 192, english: "to wait", word: "esperar" }
  ,
  { rank: Rank 193, english: "today", word: "hoy" }
  ,
  { rank: Rank 194, english: "side", word: "lado" }
  ,
  { rank: Rank 195, english: "son", word: "hijo" }
  ,
  { rank: Rank 196, english: "there", word: "allí" }
  ,
  { rank: Rank 197, english: "this one (pre-2010 spelling)", word: "éste" }
  ,
  { rank: Rank 198, english: "problem", word: "problema" }
  ,
  { rank: Rank 199, english: "agreement", word: "acuerdo" }
  ,
  { rank: Rank 200, english: "account", word: "cuenta" }
  ,
  { rank: Rank 201, english: "medium", word: "medio" }
  ,
  { rank: Rank 202, english: "against", word: "contra" }
  ,
  { rank: Rank 203, english: "out", word: "fuera" }
  ,
  { rank: Rank 204, english: "to search", word: "buscar" }
  ,
  { rank: Rank 205, english: "within", word: "dentro" }
  ,
  { rank: Rank 206, english: "long", word: "largo" }
  ,
  { rank: Rank 207, english: "safe, secure", word: "seguro" }
  ,
  { rank: Rank 208, english: "to exist", word: "existir" }
  ,
  { rank: Rank 209, english: "child", word: "niño" }
  ,
  { rank: Rank 210, english: "to enter", word: "entrar" }
  ,
  { rank: Rank 211, english: "mother", word: "madre" }
  ,
  { rank: Rank 212, english: "however", word: "sin embargo" }
  ,
  { rank: Rank 213, english: "only one, unique", word: "único" }
  ,
  { rank: Rank 214, english: "to work", word: "trabajar" }
  ,
  { rank: Rank 215, english: "small", word: "pequeño" }
  ,
  { rank: Rank 216, english: "high", word: "alto" }
  ,
  { rank: Rank 217, english: "change", word: "cambio" }
  ,
  { rank: Rank 218, english: "to write", word: "escribir" }
  ,
  { rank: Rank 219, english: "four", word: "cuatro" }
  ,
  { rank: Rank 220, english: "to lose", word: "perder" }
  ,
  { rank: Rank 221, english: "history", word: "historia" }
  ,
  { rank: Rank 222, english: "wait", word: "espera" }
  ,
  { rank: Rank 223, english: "idea", word: "idea" }
  ,
  { rank: Rank 224, english: "water", word: "agua" }
  ,
  { rank: Rank 225, english: "to produce", word: "producir" }
  ,
  { rank: Rank 226, english: "city", word: "ciudad" }
  ,
  { rank: Rank 227, english: "state", word: "estado" }
  ,
  { rank: Rank 228, english: "mode", word: "modo" }
  ,
  { rank: Rank 229, english: "name", word: "nombre" }
  ,
  { rank: Rank 230, english: "to occur", word: "ocurrir" }
  ,
  { rank: Rank 231, english: "family", word: "familia" }
  ,
  { rank: Rank 232, english: "reality", word: "realidad" }
  ,
  { rank: Rank 233, english: "to understand", word: "entender" }
  ,
  { rank: Rank 234, english: "to receive", word: "recibir" }
  ,
  { rank: Rank 235, english: "work (of art)", word: "obra" }
  ,
  { rank: Rank 236, english: "important", word: "importante" }
  ,
  { rank: Rank 237, english: "with me", word: "conmigo" }
  ,
  { rank: Rank 238, english: "wrong", word: "mal" }
  ,
  { rank: Rank 239, english: "yet", word: "todavía" }
  ,
  { rank: Rank 240, english: "reason", word: "razón" }
  ,
  { rank: Rank 241, english: "as much as", word: "cuanto" }
  ,
  { rank: Rank 242, english: "low; under", word: "bajo" }
  ,
  { rank: Rank 243, english: "to remember", word: "recordar" }
  ,
  { rank: Rank 244, english: "group", word: "grupo" }
  ,
  { rank: Rank 245, english: "love", word: "amor" }
  ,
  { rank: Rank 246, english: "thousand", word: "mil" }
  ,
  { rank: Rank 247, english: "mine", word: "mío" }
  ,
  { rank: Rank 248, english: "human", word: "humano" }
  ,
  { rank: Rank 249, english: "to finish, to end", word: "terminar" }
  ,
  { rank: Rank 250, english: "to allow", word: "permitir" }
  ,
  { rank: Rank 251, english: "to appear", word: "aparecer" }
  ,
  { rank: Rank 252, english: "to get", word: "conseguir" }
  ,
  { rank: Rank 253, english: "afternoon", word: "tarde" }
  ,
  { rank: Rank 254, english: "to start", word: "comenzar" }
  ,
  { rank: Rank 255, english: "several", word: "varios" }
  ,
  { rank: Rank 256, english: "possible", word: "posible" }
  ,
  { rank: Rank 257, english: "yet", word: "aún" }
  ,
  { rank: Rank 258, english: "to serve", word: "servir" }
  ,
  { rank: Rank 259, english: "general", word: "general" }
  ,
  { rank: Rank 260, english: "to take out", word: "sacar" }
  ,
  { rank: Rank 261, english: "relationship", word: "relación" }
  ,
  { rank: Rank 262, english: "five", word: "cinco" }
  ,
  { rank: Rank 263, english: "body", word: "cuerpo" }
  ,
  { rank: Rank 264, english: "with you", word: "contigo" }
  ,
  { rank: Rank 265, english: "to maintain", word: "mantener" }
  ,
  { rank: Rank 266, english: "faced with", word: "ante" }
  ,
  { rank: Rank 267, english: "principle", word: "principio" }
  ,
  { rank: Rank 268, english: "to result", word: "resultar" }
  ,
  { rank: Rank 269, english: "equal", word: "igual" }
  ,
  { rank: Rank 270, english: "too", word: "demasiado" }
  ,
  { rank: Rank 271, english: "town", word: "pueblo" }
  ,
  { rank: Rank 272, english: "second", word: "segundo" }
  ,
  { rank: Rank 273, english: "to read", word: "leer" }
  ,
  { rank: Rank 274, english: "to fall", word: "caer" }
  ,
  { rank: Rank 275, english: "to change", word: "cambiar" }
  ,
  { rank: Rank 276, english: "eye", word: "ojo" }
  ,
  { rank: Rank 277, english: "goodbye", word: "adiós" }
  ,
  { rank: Rank 278, english: "street", word: "calle" }
  ,
  { rank: Rank 279, english: "to present", word: "presentar" }
  ,
  { rank: Rank 280, english: "white", word: "blanco" }
  ,
  { rank: Rank 281, english: "to create", word: "crear" }
  ,
  { rank: Rank 282, english: "to open", word: "abrir" }
  ,
  { rank: Rank 283, english: "book", word: "libro" }
  ,
  { rank: Rank 284, english: "different", word: "distinto" }
  ,
  { rank: Rank 285, english: "force", word: "fuerza" }
  ,
  { rank: Rank 286, english: "light", word: "luz" }
  ,
  { rank: Rank 287, english: "according to", word: "según" }
  ,
  { rank: Rank 288, english: "saint", word: "santo" }
  ,
  { rank: Rank 289, english: "front", word: "frente" }
  ,
  { rank: Rank 290, english: "to consider", word: "considerar" }
  ,
  { rank: Rank 291, english: "really", word: "realmente" }
  ,
  { rank: Rank 292, english: "police", word: "policía" }
  ,
  { rank: Rank 293, english: "to hear", word: "oír" }
  ,
  { rank: Rank 294, english: "whose", word: "cuyo" }
  ,
  { rank: Rank 295, english: "sense", word: "sentido" }
  ,
  { rank: Rank 296, english: "to have just done; to finish", word: "acabar" }
  ,
  { rank: Rank 297, english: "step", word: "paso" }
  ,
  { rank: Rank 298, english: "situation", word: "situación" }
  ,
  { rank: Rank 299, english: "serious (person)", word: "serio" }
  ,
  { rank: Rank 300, english: "head", word: "cabeza" }
  ,
  { rank: Rank 301, english: "quite", word: "bastante" }
  ,
  { rank: Rank 302, english: "brother", word: "hermano" }
  ,
  { rank: Rank 303, english: "to convert", word: "convertir" }
  ,
  { rank: Rank 304, english: "grace", word: "gracia" }
  ,
  { rank: Rank 305, english: "century", word: "siglo" }
  ,
  { rank: Rank 306, english: "last, past", word: "pasado" }
  ,
  { rank: Rank 307, english: "bad", word: "malo" }
  ,
  { rank: Rank 308, english: "land", word: "tierra" }
  ,
  { rank: Rank 309, english: "paper", word: "papel" }
  ,
  { rank: Rank 310, english: "affection", word: "cariño" }
  ,
  { rank: Rank 311, english: "valid, voucher", word: "vale" }
  ,
  { rank: Rank 312, english: "neither", word: "tampoco" }
  ,
  { rank: Rank 313, english: "social", word: "social" }
  ,
  { rank: Rank 314, english: "old (aged)", word: "viejo" }
  ,
  { rank: Rank 315, english: "Mrs.", word: "señora" }
  ,
  { rank: Rank 316, english: "topic", word: "tema" }
  ,
  { rank: Rank 317, english: "political", word: "político" }
  ,
  { rank: Rank 318, english: "Spanish", word: "Español" }
  ,
  { rank: Rank 319, english: "dead", word: "muerto" }
  ,
  { rank: Rank 320, english: "to win", word: "ganar" }
  ,
  { rank: Rank 321, english: "to form", word: "formar" }
  ,
  { rank: Rank 322, english: "class", word: "clase" }
  ,
  { rank: Rank 323, english: "fast", word: "rápido" }
  ,
  { rank: Rank 324, english: "to bring", word: "traer" }
  ,
  { rank: Rank 325, english: "to start from, to divide", word: "partir" }
  ,
  { rank: Rank 326, english: "to die", word: "morir" }
  ,
  { rank: Rank 327, english: "even", word: "incluso" }
  ,
  { rank: Rank 328, english: "luck", word: "suerte" }
  ,
  { rank: Rank 329, english: "field, country", word: "campo" }
  ,
  { rank: Rank 330, english: "care", word: "cuidado" }
  ,
  { rank: Rank 331, english: "to accept", word: "aceptar" }
  ,
  { rank: Rank 332, english: "perhaps", word: "quizás" }
  ,
  { rank: Rank 333, english: "to perform", word: "realizar" }
  ,
  { rank: Rank 334, english: "hundred", word: "ciento" }
  ,
  { rank: Rank 335, english: "fear", word: "miedo" }
  ,
  { rank: Rank 336, english: "order", word: "orden" }
  ,
  { rank: Rank 337, english: "door", word: "puerta" }
  ,
  { rank: Rank 338, english: "soon", word: "pronto" }
  ,
  { rank: Rank 339, english: "to suppose", word: "suponer" }
  ,
  { rank: Rank 340, english: "to understand", word: "comprender" }
  ,
  { rank: Rank 341, english: "final", word: "final" }
  ,
  { rank: Rank 342, english: "interest", word: "interés" }
  ,
  { rank: Rank 343, english: "following", word: "siguiente" }
  ,
  { rank: Rank 344, english: "view", word: "vista" }
  ,
  { rank: Rank 345, english: "to achieve", word: "lograr" }
  ,
  { rank: Rank 346, english: "other, the rest", word: "demás" }
  ,
  { rank: Rank 347, english: "you (several people, object)", word: "os" }
  ,
  { rank: Rank 348, english: "boy", word: "chico" }
  ,
  { rank: Rank 349, english: "difficult", word: "difícil" }
  ,
  { rank: Rank 350, english: "how much", word: "cuánto" }
  ,
  { rank: Rank 351, english: "number", word: "número" }
  ,
  { rank: Rank 352, english: "to explain", word: "explicar" }
  ,
  { rank: Rank 353, english: "come", word: "venga" }
  ,
  { rank: Rank 354, english: "black", word: "negro" }
  ,
  { rank: Rank 355, english: "road", word: "camino" }
  ,
  { rank: Rank 356, english: "background", word: "fondo" }
  ,
  { rank: Rank 357, english: "voice", word: "voz" }
  ,
  { rank: Rank 358, english: "study", word: "estudio" }
  ,
  { rank: Rank 359, english: "necessary", word: "necesario" }
  ,
  { rank: Rank 360, english: "there", word: "allá" }
  ,
  { rank: Rank 361, english: "to touch", word: "tocar" }
  ,
  { rank: Rank 362, english: "value", word: "valor" }
  ,
  { rank: Rank 363, english: "to recognize", word: "reconocer" }
  ,
  { rank: Rank 364, english: "to study", word: "estudiar" }
  ,
  { rank: Rank 365, english: "to reach", word: "alcanzar" }
  ,
  { rank: Rank 366, english: "to be born", word: "nacer" }
  ,
  { rank: Rank 367, english: "to direct", word: "dirigir" }
  ,
  { rank: Rank 368, english: "to run", word: "correr" }
  ,
  { rank: Rank 369, english: "happy", word: "feliz" }
  ,
  { rank: Rank 370, english: "measure", word: "medida" }
  ,
  { rank: Rank 371, english: "lesser, younger", word: "menor" }
  ,
  { rank: Rank 372, english: "war", word: "guerra" }
  ,
  { rank: Rank 373, english: "only", word: "solamente" }
  ,
  { rank: Rank 374, english: "wife", word: "esposa" }
  ,
  { rank: Rank 375, english: "to use", word: "utilizar" }
  ,
  { rank: Rank 376, english: "forward", word: "adelante" }
  ,
  { rank: Rank 377, english: "center", word: "centro" }
  ,
  { rank: Rank 378, english: "which one", word: "cuál" }
  ,
  { rank: Rank 379, english: "need", word: "necesidad" }
  ,
  { rank: Rank 380, english: "condition", word: "condición" }
  ,
  { rank: Rank 381, english: "to pay", word: "pagar" }
  ,
  { rank: Rank 382, english: "it", word: "ello" }
  ,
  { rank: Rank 383, english: "lack", word: "falta" }
  ,
  { rank: Rank 384, english: "death", word: "muerte" }
  ,
  { rank: Rank 385, english: "ten", word: "diez" }
  ,
  { rank: Rank 386, english: "through, across", word: "través" }
  ,
  { rank: Rank 387, english: "ancient, former", word: "antiguo" }
  ,
  { rank: Rank 388, english: "supposed", word: "supuesto" }
  ,
  { rank: Rank 389, english: "age", word: "edad" }
  ,
  { rank: Rank 390, english: "to play", word: "jugar" }
  ,
  { rank: Rank 391, english: "heart", word: "corazón" }
  ,
  { rank: Rank 392, english: "face", word: "cara" }
  ,
  { rank: Rank 393, english: "boss, chief", word: "jefe" }
  ,
  { rank: Rank 394, english: "era, time", word: "época" }
  ,
  { rank: Rank 395, english: "color", word: "color" }
  ,
  { rank: Rank 396, english: "to listen", word: "escuchar" }
  ,
  { rank: Rank 397, english: "help", word: "ayuda" }
  ,
  { rank: Rank 398, english: "experience", word: "experiencia" }
  ,
  { rank: Rank 399, english: "movement", word: "movimiento" }
  ,
  { rank: Rank 400, english: "to fulfill", word: "cumplir" }
  ,
  { rank: Rank 401, english: "special", word: "especial" }
  ,
  { rank: Rank 402, english: "different", word: "diferente" }
  ,
  { rank: Rank 403, english: "to weigh", word: "pesar" }
  ,
  { rank: Rank 404, english: "possibility", word: "posibilidad" }
  ,
  { rank: Rank 405, english: "to offer", word: "ofrecer" }
  ,
  { rank: Rank 406, english: "up", word: "arriba" }
  ,
  { rank: Rank 407, english: "to discover", word: "descubrir" }
  ,
  { rank: Rank 408, english: "daughter", word: "hija" }
  ,
  { rank: Rank 409, english: "previous", word: "anterior" }
  ,
  { rank: Rank 410, english: "game", word: "juego" }
  ,
  { rank: Rank 411, english: "to lift (to get up)", word: "levantar(se)" }
  ,
  { rank: Rank 412, english: "poor", word: "pobre" }
  ,
  { rank: Rank 413, english: "air", word: "aire" }
  ,
  { rank: Rank 414, english: "six", word: "seis" }
  ,
  { rank: Rank 415, english: "to try", word: "intentar" }
  ,
  { rank: Rank 416, english: "together", word: "junto" }
  ,
  { rank: Rank 417, english: "result", word: "resultado" }
  ,
  { rank: Rank 418, english: "to use", word: "usar" }
  ,
  { rank: Rank 419, english: "to decide", word: "decidir" }
  ,
  { rank: Rank 420, english: "to repeat", word: "repetir" }
  ,
  { rank: Rank 421, english: "to forget", word: "olvidar" }
  ,
  { rank: Rank 422, english: "law", word: "ley" }
  ,
  { rank: Rank 423, english: "appearance", word: "aspecto" }
  ,
  { rank: Rank 424, english: "foot", word: "pie" }
  ,
  { rank: Rank 425, english: "to be worth", word: "valer" }
  ,
  { rank: Rank 426, english: "species", word: "especie" }
  ,
  { rank: Rank 427, english: "to eat", word: "comer" }
  ,
  { rank: Rank 428, english: "service", word: "servicio" }
  ,
  { rank: Rank 429, english: "close", word: "cerca" }
  ,
  { rank: Rank 430, english: "to show", word: "mostrar" }
  ,
  { rank: Rank 431, english: "activity", word: "actividad" }
  ,
  { rank: Rank 432, english: "third", word: "tercero" }
  ,
  { rank: Rank 433, english: "uncle", word: "tío" }
  ,
  { rank: Rank 434, english: "to occupy", word: "ocupar" }
  ,
  { rank: Rank 435, english: "matter, issue", word: "cuestión" }
  ,
  { rank: Rank 436, english: "doubt", word: "duda" }
  ,
  { rank: Rank 437, english: "at least", word: "siquiera" }
  ,
  { rank: Rank 438, english: "difference", word: "diferencia" }
  ,
  { rank: Rank 439, english: "to move", word: "mover" }
  ,
  { rank: Rank 440, english: "to continue", word: "continuar" }
  ,
  { rank: Rank 441, english: "amount", word: "cantidad" }
  ,
  { rank: Rank 442, english: "action", word: "acción" }
  ,
  { rank: Rank 443, english: "to happen", word: "suceder" }
  ,
  { rank: Rank 444, english: "to set", word: "fijar" }
  ,
  { rank: Rank 445, english: "society", word: "sociedad" }
  ,
  { rank: Rank 446, english: "to refer", word: "referir" }
  ,
  { rank: Rank 447, english: "to bring closer", word: "acercar" }
  ,
  { rank: Rank 448, english: "able", word: "capaz" }
  ,
  { rank: Rank 449, english: "free", word: "libre" }
  ,
  { rank: Rank 450, english: "natural", word: "natural" }
  ,
  { rank: Rank 451, english: "to devote", word: "dedicar" }
  ,
  { rank: Rank 452, english: "weight", word: "peso" }
  ,
  { rank: Rank 453, english: "effect", word: "efecto" }
  ,
  { rank: Rank 454, english: "object", word: "objeto" }
  ,
  { rank: Rank 455, english: "doctor", word: "doctor" }
  ,
  { rank: Rank 456, english: "true", word: "verdadero" }
  ,
  { rank: Rank 457, english: "enough", word: "suficiente" }
  ,
  { rank: Rank 458, english: "young", word: "joven" }
  ,
  { rank: Rank 459, english: "political party, match", word: "partido" }
  ,
  { rank: Rank 460, english: "economic", word: "económico" }
  ,
  { rank: Rank 461, english: "below, downstairs", word: "abajo" }
  ,
  { rank: Rank 462, english: "right", word: "derecho" }
  ,
  { rank: Rank 463, english: "first (before a noun)", word: "primer" }
  ,
  { rank: Rank 464, english: "importance", word: "importancia" }
  ,
  { rank: Rank 465, english: "brilliant", word: "genial" }
  ,
  { rank: Rank 466, english: "system", word: "sistema" }
  ,
  { rank: Rank 467, english: "just", word: "justo" }
  ,
  { rank: Rank 468, english: "trip", word: "viaje" }
  ,
  { rank: Rank 469, english: "soil", word: "suelo" }
  ,
  { rank: Rank 470, english: "respect, in regards to", word: "respecto" }
  ,
  { rank: Rank 471, english: "knowledge", word: "conocimiento" }
  ,
  { rank: Rank 472, english: "freedom", word: "libertad" }
  ,
  { rank: Rank 473, english: "above", word: "encima" }
  ,
  { rank: Rank 474, english: "to buy", word: "comprar" }
  ,
  { rank: Rank 475, english: "common", word: "común" }
  ,
  { rank: Rank 476, english: "open", word: "abierto" }
  ,
  { rank: Rank 477, english: "next", word: "próximo" }
  ,
  { rank: Rank 478, english: "strong", word: "fuerte" }
  ,
  { rank: Rank 479, english: "attention", word: "atención" }
  ,
  { rank: Rank 480, english: "to rise", word: "subir" }
  ,
  { rank: Rank 481, english: "effort", word: "esfuerzo" }
  ,
  { rank: Rank 482, english: "to avoid", word: "evitar" }
  ,
  { rank: Rank 483, english: "rest", word: "resto" }
  ,
  { rank: Rank 484, english: "is interesting to (to interest)", word: "interesar" }
  ,
  { rank: Rank 485, english: "back, backwards", word: "atrás" }
  ,
  { rank: Rank 486, english: "area", word: "zona" }
  ,
  { rank: Rank 487, english: "process", word: "proceso" }
  ,
  { rank: Rank 488, english: "alive", word: "vivo" }
  ,
  { rank: Rank 489, english: "to close, shut", word: "cerrar" }
  ,
  { rank: Rank 490, english: "wine", word: "vino" }
  ,
  { rank: Rank 491, english: "to throw, cast", word: "echar" }
  ,
  { rank: Rank 492, english: "to reply", word: "responder" }
  ,
  { rank: Rank 493, english: "to suffer", word: "sufrir" }
  ,
  { rank: Rank 494, english: "complete", word: "completo" }
  ,
  { rank: Rank 495, english: "minute", word: "minuto" }
  ,
  { rank: Rank 496, english: "school", word: "escuela" }
  ,
  { rank: Rank 497, english: "contrary", word: "contrario" }
  ,
  { rank: Rank 498, english: "table (furniture)", word: "mesa" }
  ,
  { rank: Rank 499, english: "real", word: "real" }
  ,
  { rank: Rank 500, english: "occasion", word: "ocasión" }
  ,
  { rank: Rank 501, english: "blood", word: "sangre" }
  ,
  { rank: Rank 502, english: "is important to (to matter)", word: "importar" }
  ,
  { rank: Rank 503, english: "public", word: "público" }
  ,
  { rank: Rank 504, english: "car", word: "coche" }
  ,
  { rank: Rank 505, english: "to obtain", word: "obtener" }
  ,
  { rank: Rank 506, english: "program", word: "programa" }
  ,
  { rank: Rank 507, english: "away", word: "lejos" }
  ,
  { rank: Rank 508, english: "seven", word: "siete" }
  ,
  { rank: Rank 509, english: "huge", word: "enorme" }
  ,
  { rank: Rank 510, english: "response", word: "respuesta" }
  ,
  { rank: Rank 511, english: "line", word: "línea" }
  ,
  { rank: Rank 512, english: "space", word: "espacio" }
  ,
  { rank: Rank 513, english: "level", word: "nivel" }
  ,
  { rank: Rank 514, english: "peace", word: "paz" }
  ,
  { rank: Rank 515, english: "government", word: "gobierno" }
  ,
  { rank: Rank 516, english: "end, cape", word: "cabo" }
  ,
  { rank: Rank 517, english: "return", word: "vuelta" }
  ,
  { rank: Rank 518, english: "to observe", word: "observar" }
  ,
  { rank: Rank 519, english: "to indicate", word: "indicar" }
  ,
  { rank: Rank 520, english: "question", word: "pregunta" }
  ,
  { rank: Rank 521, english: "image", word: "imagen" }
  ,
  { rank: Rank 522, english: "career", word: "carrera" }
  ,
  { rank: Rank 523, english: "fault", word: "culpa" }
  ,
  { rank: Rank 524, english: "to imagine", word: "imaginar" }
  ,
  { rank: Rank 525, english: "to be in the habit of", word: "soler" }
  ,
  { rank: Rank 526, english: "both", word: "ambos" }
  ,
  { rank: Rank 527, english: "to accompany", word: "acompañar" }
  ,
  { rank: Rank 528, english: "deep", word: "profundo" }
  ,
  { rank: Rank 529, english: "to stop", word: "detener" }
  ,
  { rank: Rank 530, english: "to develop", word: "desarrollar" }
  ,
  { rank: Rank 531, english: "eight", word: "ocho" }
  ,
  { rank: Rank 532, english: "easy", word: "fácil" }
  ,
  { rank: Rank 533, english: "to signal", word: "señalar" }
  ,
  { rank: Rank 534, english: "to choose", word: "elegir" }
  ,
  { rank: Rank 535, english: "figure", word: "figura" }
  ,
  { rank: Rank 536, english: "main", word: "principal" }
  ,
  { rank: Rank 537, english: "to sleep", word: "dormir" }
  ,
  { rank: Rank 538, english: "animal", word: "animal" }
  ,
  { rank: Rank 539, english: "base", word: "base" }
  ,
  { rank: Rank 540, english: "to prepare", word: "preparar" }
  ,
  { rank: Rank 541, english: "to propose", word: "proponer" }
  ,
  { rank: Rank 542, english: "to demonstrate, prove", word: "demostrar" }
  ,
  { rank: Rank 543, english: "party, celebration", word: "fiesta" }
  ,
  { rank: Rank 544, english: "to mean", word: "significar" }
  ,
  { rank: Rank 545, english: "position", word: "posición" }
  ,
  { rank: Rank 546, english: "bed", word: "cama" }
  ,
  { rank: Rank 547, english: "motive", word: "motivo" }
  ,
  { rank: Rank 548, english: "test", word: "prueba" }
  ,
  { rank: Rank 549, english: "policy", word: "politica" }
  ,
  { rank: Rank 550, english: "national", word: "nacional" }
  ,
  { rank: Rank 551, english: "full (filled up)", word: "lleno" }
  ,
  { rank: Rank 552, english: "phone", word: "teléfono" }
  ,
  { rank: Rank 553, english: "to gather", word: "reunir" }
  ,
  { rank: Rank 554, english: "is missing to (to lack)", word: "faltar" }
  ,
  { rank: Rank 555, english: "team", word: "equipo" }
  ,
  { rank: Rank 556, english: "datum", word: "dato" }
  ,
  { rank: Rank 557, english: "to wish", word: "desear" }
  ,
  { rank: Rank 558, english: "company, firm", word: "empresa" }
  ,
  { rank: Rank 559, english: "issue", word: "asunto" }
  ,
  { rank: Rank 560, english: "presence", word: "presencia" }
  ,
  { rank: Rank 561, english: "his, hers, theirs", word: "suyo" }
  ,
  { rank: Rank 562, english: "culture", word: "cultura" }
  ,
  { rank: Rank 563, english: "series", word: "serie" }
  ,
  { rank: Rank 564, english: "million", word: "millón" }
  ,
  { rank: Rank 565, english: "to teach", word: "enseñar" }
  ,
  { rank: Rank 566, english: "to build", word: "construir" }
  ,
  { rank: Rank 567, english: "opportunity", word: "oportunidad" }
  ,
  { rank: Rank 568, english: "to sell", word: "vender" }
  ,
  { rank: Rank 569, english: "to kill", word: "matar" }
  ,
  { rank: Rank 570, english: "to represent", word: "representar" }
  ,
  { rank: Rank 571, english: "to disappear", word: "desaparecer" }
  ,
  { rank: Rank 572, english: "to send, to order", word: "mandar" }
  ,
  { rank: Rank 573, english: "character (nature)", word: "carácter" }
  ,
  { rank: Rank 574, english: "where to? (asking)", word: "adónde" }
  ,
  { rank: Rank 575, english: "most", word: "mayoría" }
  ,
  { rank: Rank 576, english: "red", word: "rojo" }
  ,
  { rank: Rank 577, english: "after, behind (formal)", word: "tras" }
  ,
  { rank: Rank 578, english: "top", word: "superior" }
  ,
  { rank: Rank 579, english: "to walk", word: "andar" }
  ,
  { rank: Rank 580, english: "short", word: "corto" }
  ,
  { rank: Rank 581, english: "author", word: "autor" }
  ,
  { rank: Rank 582, english: "fourth", word: "cuarto" }
  ,
  { rank: Rank 583, english: "sky", word: "cielo" }
  ,
  { rank: Rank 584, english: "known", word: "conocido" }
  ,
  { rank: Rank 585, english: "to prefer", word: "preferir" }
  ,
  { rank: Rank 586, english: "memory (a recollection)", word: "recuerdo" }
  ,
  { rank: Rank 587, english: "to ensure", word: "asegurar" }
  ,
  { rank: Rank 588, english: "forgiveness", word: "perdón" }
  ,
  { rank: Rank 589, english: "function", word: "función" }
  ,
  { rank: Rank 590, english: "cause", word: "causa" }
  ,
  { rank: Rank 591, english: "severe", word: "grave" }
  ,
  { rank: Rank 592, english: "decision", word: "decisión" }
  ,
  { rank: Rank 593, english: "music", word: "música" }
  ,
  { rank: Rank 594, english: "strange", word: "extraño" }
  ,
  { rank: Rank 595, english: "to grow", word: "crecer" }
  ,
  { rank: Rank 596, english: "to emerge", word: "surgir" }
  ,
  { rank: Rank 597, english: "movie", word: "película" }
  ,
  { rank: Rank 598, english: "expression", word: "expresión" }
  ,
  { rank: Rank 599, english: "husband", word: "marido" }
  ,
  { rank: Rank 600, english: "around", word: "alrededor" }
  ,
  { rank: Rank 601, english: "dog", word: "perro" }
  ,
  { rank: Rank 602, english: "to deliver", word: "entregar" }
  ,
  { rank: Rank 603, english: "river", word: "río" }
  ,
  { rank: Rank 604, english: "exactly", word: "exactamente" }
  ,
  { rank: Rank 605, english: "security", word: "seguridad" }
  ,
  { rank: Rank 606, english: "king", word: "rey" }
  ,
  { rank: Rank 607, english: "term", word: "término" }
  ,
  { rank: Rank 608, english: "to place", word: "colocar" }
  ,
  { rank: Rank 609, english: "metro", word: "metro" }
  ,
  { rank: Rank 610, english: "doctor", word: "médico" }
  ,
  { rank: Rank 611, english: "room (bedroom)", word: "habitación" }
  ,
  { rank: Rank 612, english: "to establish", word: "establecer" }
  ,
  { rank: Rank 613, english: "to keep, to store", word: "guardar" }
  ,
  { rank: Rank 614, english: "art", word: "arte" }
  ,
  { rank: Rank 615, english: "pair", word: "par" }
  ,
  { rank: Rank 616, english: "to start", word: "iniciar" }
  ,
  { rank: Rank 617, english: "fire", word: "fuego" }
  ,
  { rank: Rank 618, english: "to go down, to lower", word: "bajar" }
  ,
  { rank: Rank 619, english: "consequence", word: "consecuencia" }
  ,
  { rank: Rank 620, english: "to note", word: "notar" }
  ,
  { rank: Rank 621, english: "act", word: "acto" }
  ,
  { rank: Rank 622, english: "to put inside", word: "meter" }
  ,
  { rank: Rank 623, english: "absolute", word: "absoluto" }
  ,
  { rank: Rank 624, english: "penalty", word: "pena" }
  ,
  { rank: Rank 625, english: "to act", word: "actuar" }
  ,
  { rank: Rank 626, english: "height", word: "altura" }
  ,
  { rank: Rank 627, english: "desire", word: "deseo" }
  ,
  { rank: Rank 628, english: "out, outside", word: "afuera" }
  ,
  { rank: Rank 629, english: "precisely", word: "precisamente" }
  ,
  { rank: Rank 630, english: "twenty", word: "veinte" }
  ,
  { rank: Rank 631, english: "dream", word: "sueño" }
  ,
  { rank: Rank 632, english: "to intend, to claim", word: "pretender" }
  ,
  { rank: Rank 633, english: "task", word: "tarea" }
  ,
  { rank: Rank 634, english: "coffee", word: "café" }
  ,
  { rank: Rank 635, english: "letter (you send)", word: "carta" }
  ,
  { rank: Rank 636, english: "barely, just", word: "apenas" }
  ,
  { rank: Rank 637, english: "property", word: "propiedad" }
  ,
  { rank: Rank 638, english: "product", word: "producto" }
  ,
  { rank: Rank 639, english: "personal", word: "personal" }
  ,
  { rank: Rank 640, english: "simply", word: "simplemente" }
  ,
  { rank: Rank 641, english: "impossible", word: "imposible" }
  ,
  { rank: Rank 642, english: "taste", word: "gusto" }
  ,
  { rank: Rank 643, english: "to agree (remember)", word: "acordar(se)" }
  ,
  { rank: Rank 644, english: "site", word: "sitio" }
  ,
  { rank: Rank 645, english: "language, tongue", word: "lengua" }
  ,
  { rank: Rank 646, english: "to cut", word: "cortar" }
  ,
  { rank: Rank 647, english: "plan", word: "plan" }
  ,
  { rank: Rank 648, english: "baby", word: "bebé" }
  ,
  { rank: Rank 649, english: "to correspond", word: "corresponder" }
  ,
  { rank: Rank 650, english: "to break", word: "romper" }
  ,
  { rank: Rank 651, english: "never", word: "jamás" }
  ,
  { rank: Rank 652, english: "to acquire", word: "adquirir" }
  ,
  { rank: Rank 653, english: "weapon", word: "arma" }
  ,
  { rank: Rank 654, english: "project", word: "proyecto" }
  ,
  { rank: Rank 655, english: "memory (the faculty)", word: "memoria" }
  ,
  { rank: Rank 656, english: "origin", word: "origen" }
  ,
  { rank: Rank 657, english: "element", word: "elemento" }
  ,
  { rank: Rank 658, english: "lost", word: "perdido" }
  ,
  { rank: Rank 659, english: "English", word: "inglés" }
  ,
  { rank: Rank 660, english: "market", word: "mercado" }
  ,
  { rank: Rank 661, english: "course", word: "curso" }
  ,
  { rank: Rank 662, english: "to launch", word: "lanzar" }
  ,
  { rank: Rank 663, english: "given", word: "dado" }
  ,
  { rank: Rank 664, english: "to take advantage of", word: "aprovechar" }
  ,
  { rank: Rank 665, english: "interior", word: "interior" }
  ,
  { rank: Rank 666, english: "hard", word: "duro" }
  ,
  { rank: Rank 667, english: "to support", word: "apoyar" }
  ,
  { rank: Rank 668, english: "worse", word: "peor" }
  ,
  { rank: Rank 669, english: "to deny", word: "negar" }
  ,
  { rank: Rank 670, english: "to advance", word: "avanzar" }
  ,
  { rank: Rank 671, english: "usage", word: "uso" }
  ,
  { rank: Rank 672, english: "arm", word: "brazo" }
  ,
  { rank: Rank 673, english: "teacher, professor", word: "profesor" }
  ,
  { rank: Rank 674, english: "to resolve", word: "resolver" }
  ,
  { rank: Rank 675, english: "future", word: "futuro" }
  ,
  { rank: Rank 676, english: "half", word: "mitad" }
  ,
  { rank: Rank 677, english: "clothing", word: "ropa" }
  ,
  { rank: Rank 678, english: "is costly to (to cost)", word: "costar" }
  ,
  { rank: Rank 679, english: "rich", word: "rico" }
  ,
  { rank: Rank 680, english: "total", word: "total" }
  ,
  { rank: Rank 681, english: "to require", word: "exigir" }
  ,
  { rank: Rank 682, english: "opinion", word: "opinión" }
  ,
  { rank: Rank 683, english: "to increase", word: "aumentar" }
  ,
  { rank: Rank 684, english: "to collect", word: "recoger" }
  ,
  { rank: Rank 685, english: "mouth", word: "boca" }
  ,
  { rank: Rank 686, english: "address", word: "dirección" }
  ,
  { rank: Rank 687, english: "pure", word: "puro" }
  ,
  { rank: Rank 688, english: "president", word: "presidente" }
  ,
  { rank: Rank 689, english: "to abandon", word: "abandonar" }
  ,
  { rank: Rank 690, english: "piece", word: "pieza" }
  ,
  { rank: Rank 691, english: "last night", word: "anoche" }
  ,
  { rank: Rank 692, english: "professional", word: "profesional" }
  ,
  { rank: Rank 693, english: "to impose", word: "imponer" }
  ,
  { rank: Rank 694, english: "concerning", word: "acerca" }
  ,
  { rank: Rank 695, english: "to force", word: "obligar" }
  ,
  { rank: Rank 696, english: "physical", word: "físico" }
  ,
  { rank: Rank 697, english: "attitude", word: "actitud" }
  ,
  { rank: Rank 698, english: "sea", word: "mar" }
  ,
  { rank: Rank 699, english: "entry", word: "entrada" }
  ,
  { rank: Rank 700, english: "contact", word: "contacto" }
  ,
  { rank: Rank 701, english: "to apply", word: "aplicar" }
  ,
  { rank: Rank 702, english: "correct", word: "correcto" }
  ,
  { rank: Rank 703, english: "capital", word: "capital" }
  ,
  { rank: Rank 704, english: "title", word: "título" }
  ,
  { rank: Rank 705, english: "behind", word: "detrás" }
  ,
  { rank: Rank 706, english: "post", word: "puesto" }
  ,
  { rank: Rank 707, english: "material", word: "material" }
  ,
  { rank: Rank 708, english: "blow", word: "golpe" }
  ,
  { rank: Rank 709, english: "to dispose", word: "disponer" }
  ,
  { rank: Rank 710, english: "communication", word: "comunicación" }
  ,
  { rank: Rank 711, english: "to express", word: "expresar" }
  ,
  { rank: Rank 712, english: "sorry", word: "disculpe" }
  ,
  { rank: Rank 713, english: "simple", word: "simple" }
  ,
  { rank: Rank 714, english: "completely", word: "totalmente" }
  ,
  { rank: Rank 715, english: "to provoke", word: "provocar" }
  ,
  { rank: Rank 716, english: "normal", word: "normal" }
  ,
  { rank: Rank 717, english: "to defend", word: "defender" }
  ,
  { rank: Rank 718, english: "disease", word: "enfermedad" }
  ,
  { rank: Rank 719, english: "matter", word: "materia" }
  ,
  { rank: Rank 720, english: "to take away", word: "quitar" }
  ,
  { rank: Rank 721, english: "to conserve", word: "conservar" }
  ,
  { rank: Rank 722, english: "modern", word: "moderno" }
  ,
  { rank: Rank 723, english: "hospital", word: "hospital" }
  ,
  { rank: Rank 724, english: "to depend", word: "depender" }
  ,
  { rank: Rank 725, english: "nature", word: "naturaleza" }
  ,
  { rank: Rank 726, english: "capacity", word: "capacidad" }
  ,
  { rank: Rank 727, english: "current, present-day", word: "actual" }
  ,
  { rank: Rank 728, english: "to mark", word: "marcar" }
  ,
  { rank: Rank 729, english: "distance", word: "distancia" }
  ,
  { rank: Rank 730, english: "full, in the middle of", word: "pleno" }
  ,
  { rank: Rank 731, english: "perfect", word: "perfecto" }
  ,
  { rank: Rank 732, english: "closed", word: "cerrado" }
  ,
  { rank: Rank 733, english: "to share", word: "compartir" }
  ,
  { rank: Rank 734, english: "quiet", word: "tranquilo" }
  ,
  { rank: Rank 735, english: "information", word: "información" }
  ,
  { rank: Rank 736, english: "environment", word: "ambiente" }
  ,
  { rank: Rank 737, english: "especially", word: "especialmente" }
  ,
  { rank: Rank 738, english: "development", word: "desarrollo" }
  ,
  { rank: Rank 739, english: "sun", word: "sol" }
  ,
  { rank: Rank 740, english: "to consist", word: "consistir" }
  ,
  { rank: Rank 741, english: "probably", word: "probablemente" }
  ,
  { rank: Rank 742, english: "to constitute", word: "constituir" }
  ,
  { rank: Rank 743, english: "yesterday", word: "ayer" }
  ,
  { rank: Rank 744, english: "ready", word: "dispuesto" }
  ,
  { rank: Rank 745, english: "to cover", word: "cubrir" }
  ,
  { rank: Rank 746, english: "to function", word: "funcionar" }
  ,
  { rank: Rank 747, english: "partner", word: "compañero" }
  ,
  { rank: Rank 748, english: "nice", word: "bonito" }
  ,
  { rank: Rank 749, english: "output", word: "salida" }
  ,
  { rank: Rank 750, english: "to fit", word: "caber" }
  ,
  { rank: Rank 751, english: "awareness", word: "conciencia" }
  ,
  { rank: Rank 752, english: "to meet", word: "atender" }
  ,
  { rank: Rank 753, english: "sick", word: "enfermo" }
  ,
  { rank: Rank 754, english: "incredible", word: "increíble" }
  ,
  { rank: Rank 755, english: "to insist", word: "insistir" }
  ,
  { rank: Rank 756, english: "custom", word: "costumbre" }
  ,
  { rank: Rank 757, english: "silly", word: "tonto" }
  ,
  { rank: Rank 758, english: "news", word: "noticia" }
  ,
  { rank: Rank 759, english: "circumstance", word: "circunstancia" }
  ,
  { rank: Rank 760, english: "is painful to (to hurt)", word: "doler" }
  ,
  { rank: Rank 761, english: "private", word: "privado" }
  ,
  { rank: Rank 762, english: "style", word: "estilo" }
  ,
  { rank: Rank 763, english: "price", word: "precio" }
  ,
  { rank: Rank 764, english: "popular", word: "popular" }
  ,
  { rank: Rank 765, english: "to sit", word: "sentar" }
  ,
  { rank: Rank 766, english: "plant", word: "planta" }
  ,
  { rank: Rank 767, english: "that one (pre-2010 spelling)", word: "ése" }
  ,
  { rank: Rank 768, english: "character (in a story)", word: "personaje" }
  ,
  { rank: Rank 769, english: "famous", word: "famoso" }
  ,
  { rank: Rank 770, english: "hunger", word: "hambre" }
  ,
  { rank: Rank 771, english: "success", word: "éxito" }
  ,
  { rank: Rank 772, english: "to merit", word: "merecer" }
  ,
  { rank: Rank 773, english: "building", word: "edificio" }
  ,
  { rank: Rank 774, english: "authority", word: "autoridad" }
  ,
  { rank: Rank 775, english: "stone", word: "piedra" }
  ,
  { rank: Rank 776, english: "to include", word: "incluir" }
  ,
  { rank: Rank 777, english: "boat", word: "barco" }
  ,
  { rank: Rank 778, english: "set", word: "conjunto" }
  ,
  { rank: Rank 779, english: "hotel", word: "hotel" }
  ,
  { rank: Rank 780, english: "thirty", word: "treinta" }
  ,
  { rank: Rank 781, english: "immediate", word: "inmediato" }
  ,
  { rank: Rank 782, english: "to cross", word: "cruzar" }
  ,
  { rank: Rank 783, english: "yours", word: "tuyo" }
  ,
  { rank: Rank 784, english: "to tend", word: "tender" }
  ,
  { rank: Rank 785, english: "finally", word: "finalmente" }
  ,
  { rank: Rank 786, english: "to advertise", word: "anunciar" }
  ,
  { rank: Rank 787, english: "bath", word: "baño" }
  ,
  { rank: Rank 788, english: "spirit", word: "espíritu" }
  ,
  { rank: Rank 789, english: "member", word: "miembro" }
  ,
  { rank: Rank 790, english: "direct", word: "directo" }
  ,
  { rank: Rank 791, english: "pleasure", word: "placer" }
  ,
  { rank: Rank 792, english: "to wake", word: "despertar" }
  ,
  { rank: Rank 793, english: "resource", word: "recurso" }
  ,
  { rank: Rank 794, english: "wall", word: "pared" }
  ,
  { rank: Rank 795, english: "error", word: "error" }
  ,
  { rank: Rank 796, english: "accurate", word: "preciso" }
  ,
  { rank: Rank 797, english: "miscellaneous", word: "diverso" }
  ,
  { rank: Rank 798, english: "difficulty", word: "dificultad" }
  ,
  { rank: Rank 799, english: "to comment", word: "comentar" }
  ,
  { rank: Rank 800, english: "to publish", word: "publicar" }
  ,
  { rank: Rank 801, english: "relating to family, a relative", word: "familiar" }
  ,
  { rank: Rank 802, english: "will", word: "voluntad" }
  ,
  { rank: Rank 803, english: "meeting", word: "reunión" }
  ,
  { rank: Rank 804, english: "model", word: "modelo" }
  ,
  { rank: Rank 805, english: "secret", word: "secreto" }
  ,
  { rank: Rank 806, english: "to load", word: "cargar" }
  ,
  { rank: Rank 807, english: "date", word: "fecha" }
  ,
  { rank: Rank 808, english: "to participate", word: "participar" }
  ,
  { rank: Rank 809, english: "train", word: "tren" }
  ,
  { rank: Rank 810, english: "to prevent", word: "impedir" }
  ,
  { rank: Rank 811, english: "purpose", word: "propósito" }
  ,
  { rank: Rank 812, english: "to rescue", word: "salvar" }
  ,
  { rank: Rank 813, english: "hurry", word: "prisa" }
  ,
  { rank: Rank 814, english: "degree", word: "grado" }
  ,
  { rank: Rank 815, english: "to escape", word: "escapar" }
  ,
  { rank: Rank 816, english: "deal", word: "negocio" }
  ,
  { rank: Rank 817, english: "fight", word: "lucha" }
  ,
  { rank: Rank 818, english: "to throw", word: "tirar" }
  ,
  { rank: Rank 819, english: "whole", word: "entero" }
  ,
  { rank: Rank 820, english: "interesting", word: "interesante" }
  ,
  { rank: Rank 821, english: "wide", word: "amplio" }
  ,
  { rank: Rank 822, english: "silence", word: "silencio" }
  ,
  { rank: Rank 823, english: "to answer", word: "contestar" }
  ,
  { rank: Rank 824, english: "newspaper", word: "periódico" }
  ,
  { rank: Rank 825, english: "is worrying to (to worry)", word: "preocupar" }
  ,
  { rank: Rank 826, english: "schoolteacher, master", word: "maestro" }
  ,
  { rank: Rank 827, english: "to lend", word: "prestar" }
  ,
  { rank: Rank 828, english: "quality", word: "calidad" }
  ,
  { rank: Rank 829, english: "salt", word: "sal" }
  ,
  { rank: Rank 830, english: "to exhibit", word: "exponer" }
  ,
  { rank: Rank 831, english: "control", word: "control" }
  ,
  { rank: Rank 832, english: "civil", word: "civil" }
  ,
  { rank: Rank 833, english: "rare", word: "raro" }
  ,
  { rank: Rank 834, english: "science", word: "ciencia" }
  ,
  { rank: Rank 835, english: "size", word: "tamaño" }
  ,
  { rank: Rank 836, english: "chart, painting", word: "cuadro" }
  ,
  { rank: Rank 837, english: "horse", word: "caballo" }
  ,
  { rank: Rank 838, english: "responsibility", word: "responsabilidad" }
  ,
  { rank: Rank 839, english: "fifty", word: "cincuenta" }
  ,
  { rank: Rank 840, english: "internal", word: "interno" }
  ,
  { rank: Rank 841, english: "detail", word: "detalle" }
  ,
  { rank: Rank 842, english: "march", word: "marcha" }
  ,
  { rank: Rank 843, english: "nine", word: "nueve" }
  ,
  { rank: Rank 844, english: "meat", word: "carne" }
  ,
  { rank: Rank 845, english: "plane", word: "avión" }
  ,
  { rank: Rank 846, english: "hair", word: "pelo" }
  ,
  { rank: Rank 847, english: "thought", word: "pensamiento" }
  ,
  { rank: Rank 848, english: "to travel", word: "viajar" }
  ,
  { rank: Rank 849, english: "charge", word: "cargo" }
  ,
  { rank: Rank 850, english: "to separate", word: "separar" }
  ,
  { rank: Rank 851, english: "construction", word: "construcción" }
  ,
  { rank: Rank 852, english: "trial", word: "juicio" }
  ,
  { rank: Rank 853, english: "ground", word: "terreno" }
  ,
  { rank: Rank 854, english: "floor", word: "piso" }
  ,
  { rank: Rank 855, english: "companionship, company", word: "compañia" }
  ,
  { rank: Rank 856, english: "gold", word: "oro" }
  ,
  { rank: Rank 857, english: "to return", word: "regresar" }
  ,
  { rank: Rank 858, english: "text", word: "texto" }
  ,
  { rank: Rank 859, english: "source", word: "fuente" }
  ,
  { rank: Rank 860, english: "present", word: "presente" }
  ,
  { rank: Rank 861, english: "official", word: "oficial" }
  ,
  { rank: Rank 862, english: "difinitive", word: "difinitivo" }
  ,
  { rank: Rank 863, english: "magazine", word: "revista" }
  ,
  { rank: Rank 864, english: "damage", word: "daño" }
  ,
  { rank: Rank 865, english: "hope", word: "esperanza" }
  ,
  { rank: Rank 866, english: "machine", word: "máquina" }
  ,
  { rank: Rank 867, english: "to contemplate", word: "contemplar" }
  ,
  { rank: Rank 868, english: "to travel through, cover", word: "recorrer" }
  ,
  { rank: Rank 869, english: "mind", word: "mente" }
  ,
  { rank: Rank 870, english: "phrase", word: "frase" }
  ,
  { rank: Rank 871, english: "exercise", word: "ejercicio" }
  ,
  { rank: Rank 872, english: "hall, living room", word: "sala" }
  ,
  { rank: Rank 873, english: "to last", word: "durar" }
  ,
  { rank: Rank 874, english: "instrument", word: "instrumento" }
  ,
  { rank: Rank 875, english: "that thing", word: "aquello" }
  ,
  { rank: Rank 876, english: "defense", word: "defensa" }
  ,
  { rank: Rank 877, english: "director", word: "director" }
  ,
  { rank: Rank 878, english: "to withdraw", word: "retirar" }
  ,
  { rank: Rank 879, english: "explanation", word: "explicación" }
  ,
  { rank: Rank 880, english: "article", word: "artículo" }
  ,
  { rank: Rank 881, english: "underneath", word: "debajo" }
  ,
  { rank: Rank 882, english: "to remain", word: "permanecer" }
  ,
  { rank: Rank 883, english: "to attend", word: "asistir" }
  ,
  { rank: Rank 884, english: "twelve", word: "doce" }
  ,
  { rank: Rank 885, english: "permission", word: "permiso" }
  ,
  { rank: Rank 886, english: "radio", word: "radio" }
  ,
  { rank: Rank 887, english: "to organize", word: "organizar" }
  ,
  { rank: Rank 888, english: "choice", word: "elección" }
  ,
  { rank: Rank 889, english: "visit", word: "visita" }
  ,
  { rank: Rank 890, english: "funny", word: "divertido" }
  ,
  { rank: Rank 891, english: "to contain", word: "contener" }
  ,
  { rank: Rank 892, english: "support", word: "apoyo" }
  ,
  { rank: Rank 893, english: "tree", word: "árbol" }
  ,
  { rank: Rank 894, english: "to visit", word: "visitar" }
  ,
  { rank: Rank 895, english: "to report", word: "informar" }
  ,
  { rank: Rank 896, english: "encounter", word: "encuentro" }
  ,
  { rank: Rank 897, english: "sex", word: "sexo" }
  ,
  { rank: Rank 898, english: "like", word: "parecido" }
  ,
  { rank: Rank 899, english: "ordinary, current (of water)", word: "corriente" }
  ,
  { rank: Rank 900, english: "friendly", word: "amable" }
  ,
  { rank: Rank 901, english: "reading", word: "lectura" }
  ,
  { rank: Rank 902, english: "message", word: "mensaje" }
  ,
  { rank: Rank 903, english: "existence", word: "existencia" }
  ,
  { rank: Rank 904, english: "language (speech, style)", word: "lenguaje" }
  ,
  { rank: Rank 905, english: "costume", word: "traje" }
  ,
  { rank: Rank 906, english: "to send", word: "enviar" }
  ,
  { rank: Rank 907, english: "soul", word: "alma" }
  ,
  { rank: Rank 908, english: "even, yet, still", word: "aun" }
  ,
  { rank: Rank 909, english: "destination", word: "destino" }
  ,
  { rank: Rank 910, english: "education", word: "educación" }
  ,
  { rank: Rank 911, english: "to care", word: "cuidar" }
  ,
  { rank: Rank 912, english: "to intervene", word: "intervenir" }
  ,
  { rank: Rank 913, english: "dinner", word: "cena" }
  ,
  { rank: Rank 914, english: "operation", word: "operación" }
  ,
  { rank: Rank 915, english: "perfectly", word: "perfectamente" }
  ,
  { rank: Rank 916, english: "to extend", word: "extender" }
  ,
  { rank: Rank 917, english: "to check", word: "comprobar" }
  ,
  { rank: Rank 918, english: "note", word: "nota" }
  ,
  { rank: Rank 919, english: "particular", word: "particular" }
  ,
  { rank: Rank 920, english: "to delay", word: "tardar" }
  ,
  { rank: Rank 921, english: "in, inside", word: "adentro" }
  ,
  { rank: Rank 922, english: "military", word: "militar" }
  ,
  { rank: Rank 923, english: "song", word: "canción" }
  ,
  { rank: Rank 924, english: "attached", word: "unido" }
  ,
  { rank: Rank 925, english: "to discuss", word: "discutir" }
  ,
  { rank: Rank 926, english: "to fear", word: "temer" }
  ,
  { rank: Rank 927, english: "extraordinary", word: "extraordinario" }
  ,
  { rank: Rank 928, english: "theater", word: "teatro" }
  ,
  { rank: Rank 929, english: "to face", word: "enfrentar" }
  ,
  { rank: Rank 930, english: "newly, freshly", word: "recién" }
  ,
  { rank: Rank 931, english: "average", word: "media" }
  ,
  { rank: Rank 932, english: "letter (of the alphabet)", word: "letra" }
  ,
  { rank: Rank 933, english: "feeling", word: "sentimiento" }
  ,
  { rank: Rank 934, english: "to drive", word: "conducir" }
  ,
  { rank: Rank 935, english: "completely", word: "completamente" }
  ,
  { rank: Rank 936, english: "cold", word: "frío" }
  ,
  { rank: Rank 937, english: "to sign", word: "firmar" }
  ,
  { rank: Rank 938, english: "solution", word: "solución" }
  ,
  { rank: Rank 939, english: "health", word: "salud" }
  ,
  { rank: Rank 940, english: "it works", word: "funciona" }
  ,
  { rank: Rank 941, english: "print", word: "impresión" }
  ,
  { rank: Rank 942, english: "to complain", word: "quejarse" }
  ,
  { rank: Rank 943, english: "intention", word: "intención" }
  ,
  { rank: Rank 944, english: "rate", word: "ritmo" }
  ,
  { rank: Rank 945, english: "green", word: "verde" }
  ,
  { rank: Rank 946, english: "exact", word: "exacto" }
  ,
  { rank: Rank 947, english: "to respect", word: "respetar" }
  ,
  { rank: Rank 948, english: "terrible", word: "terrible" }
  ,
  { rank: Rank 949, english: "bank", word: "banco" }
  ,
  { rank: Rank 950, english: "via", word: "vía" }
  ,
  { rank: Rank 951, english: "to hold", word: "sostener" }
  ,
  { rank: Rank 952, english: "moon", word: "luna" }
  ,
  { rank: Rank 953, english: "skin", word: "piel" }
  ,
  { rank: Rank 954, english: "left (direction)", word: "izquierda" }
  ,
  { rank: Rank 955, english: "in front", word: "delante" }
  ,
  { rank: Rank 956, english: "religious", word: "religioso" }
  ,
  { rank: Rank 957, english: "to warn", word: "advertir" }
  ,
  { rank: Rank 958, english: "dark", word: "oscuro" }
  ,
  { rank: Rank 959, english: "research", word: "investigación" }
  ,
  { rank: Rank 960, english: "heat", word: "calor" }
  ,
  { rank: Rank 961, english: "shop", word: "tienda" }
  ,
  { rank: Rank 962, english: "conversation", word: "conversación" }
  ,
  { rank: Rank 963, english: "Christmas", word: "navidad" }
  ,
  { rank: Rank 964, english: "summer", word: "verano" }
  ,
  { rank: Rank 965, english: "respect", word: "respeto" }
  ,
  { rank: Rank 966, english: "grandfather", word: "abuelo" }
  ,
  { rank: Rank 967, english: "north", word: "norte" }
  ,
  { rank: Rank 968, english: "by means of", word: "mediante" }
  ,
  { rank: Rank 969, english: "tradition", word: "tradición" }
  ,
  { rank: Rank 970, english: "is sufficient to (to be enough)", word: "bastar" }
  ,
  { rank: Rank 971, english: "couple", word: "pareja" }
  ,
  { rank: Rank 972, english: "population", word: "población" }
  ,
  { rank: Rank 973, english: "lawyer", word: "abogado" }
  ,
  { rank: Rank 974, english: "daily", word: "diario" }
  ,
  { rank: Rank 975, english: "honor", word: "honor" }
  ,
  { rank: Rank 976, english: "blue", word: "azul" }
  ,
  { rank: Rank 977, english: "to mention", word: "mencionar" }
  ,
  { rank: Rank 978, english: "generation", word: "generación" }
  ,
  { rank: Rank 979, english: "vision", word: "visión" }
  ,
  { rank: Rank 980, english: "concrete", word: "concreto" }
  ,
  { rank: Rank 981, english: "completed", word: "terminado" }
  ,
  { rank: Rank 982, english: "to raise (an issue)", word: "plantear" }
  ,
  { rank: Rank 983, english: "left behind", word: "dejado" }
  ,
  { rank: Rank 984, english: "to test", word: "probar" }
  ,
  { rank: Rank 985, english: "to swear, pledge", word: "jurar" }
  ,
  { rank: Rank 986, english: "beautiful", word: "hermoso" }
  ,
  { rank: Rank 987, english: "danger", word: "peligro" }
  ,
  { rank: Rank 988, english: "confidence", word: "confianza" }
  ,
  { rank: Rank 989, english: "to fill", word: "llenar" }
  ,
  { rank: Rank 990, english: "simple", word: "sencillo" }
  ,
  { rank: Rank 991, english: "to improve", word: "mejorar" }
  ,
  { rank: Rank 992, english: "concept", word: "concepto" }
  ,
  { rank: Rank 993, english: "to highlight", word: "destacar" }
  ,
  { rank: Rank 994, english: "wood", word: "madera" }
  ,
  { rank: Rank 995, english: "to walk", word: "caminar" }
  ,
  { rank: Rank 996, english: "to employ", word: "emplear" }
  ,
  { rank: Rank 997, english: "to agree", word: "convenir" }
  ,
  { rank: Rank 998, english: "energy", word: "energía" }
  ,
  { rank: Rank 999, english: "to admit", word: "admitir" }
  ,
  { rank: Rank 1000, english: "is delightful to (to love)", word: "encantar" }
  ]
