-- | GENERATED by tools/sync-deck.mjs — do not edit.
-- |
-- | Source: data/es-1000.csv (1000 words, ordered by frequency).
module Flashcards.Data.Deck.Spanish
  ( deck
  , fingerprint
  )
  where

import Flashcards.Types.Card (Card, Rank(..))

-- | Content hash of this deck. Progress is keyed by rank, so a deck whose rows
-- | were renumbered is a different deck as far as saved progress is concerned.
fingerprint :: String
fingerprint = "c687d9574f46"

-- | The 1000 most common Spanish words, most frequent first. The index into
-- | this deck is meaningful: it is the curriculum order.
deck :: Array Card
deck =
  [
  { rank: Rank 1, english: "I", spanish: "yo" }
  ,
  { rank: Rank 2, english: "to want", spanish: "querer" }
  ,
  { rank: Rank 3, english: "this", spanish: "este" }
  ,
  { rank: Rank 4, english: "yes", spanish: "sí" }
  ,
  { rank: Rank 5, english: "no", spanish: "no" }
  ,
  { rank: Rank 6, english: "to be able to", spanish: "poder" }
  ,
  { rank: Rank 7, english: "to speak", spanish: "hablar" }
  ,
  { rank: Rank 8, english: "to find", spanish: "encontrar" }
  ,
  { rank: Rank 9, english: "to have (own)", spanish: "tener" }
  ,
  { rank: Rank 10, english: "to need", spanish: "necesitar" }
  ,
  { rank: Rank 11, english: "where (the place that)", spanish: "donde" }
  ,
  { rank: Rank 12, english: "that (linking clauses)", spanish: "que" }
  ,
  { rank: Rank 13, english: "the", spanish: "el / la" }
  ,
  { rank: Rank 14, english: "place", spanish: "lugar" }
  ,
  { rank: Rank 15, english: "home", spanish: "casa" }
  ,
  { rank: Rank 16, english: "something", spanish: "algo" }
  ,
  { rank: Rank 17, english: "that (near you)", spanish: "ese" }
  ,
  { rank: Rank 18, english: "and", spanish: "y" }
  ,
  { rank: Rank 19, english: "to see", spanish: "ver" }
  ,
  { rank: Rank 20, english: "but", spanish: "pero" }
  ,
  { rank: Rank 21, english: "to go (go away/leave)", spanish: "ir(se)" }
  ,
  { rank: Rank 22, english: "to, at", spanish: "a" }
  ,
  { rank: Rank 23, english: "to say", spanish: "decir" }
  ,
  { rank: Rank 24, english: "or", spanish: "o" }
  ,
  { rank: Rank 25, english: "a", spanish: "un" }
  ,
  { rank: Rank 26, english: "more", spanish: "más" }
  ,
  { rank: Rank 27, english: "as, like", spanish: "como" }
  ,
  { rank: Rank 28, english: "is, oneself", spanish: "se" }
  ,
  { rank: Rank 29, english: "to come", spanish: "venir" }
  ,
  { rank: Rank 30, english: "my", spanish: "mi" }
  ,
  { rank: Rank 31, english: "to be (what it is)", spanish: "ser" }
  ,
  { rank: Rank 32, english: "to be (how or where it is)", spanish: "estar" }
  ,
  { rank: Rank 33, english: "to live", spanish: "vivir" }
  ,
  { rank: Rank 34, english: "to pass", spanish: "pasar" }
  ,
  { rank: Rank 35, english: "day", spanish: "día" }
  ,
  { rank: Rank 36, english: "year", spanish: "año" }
  ,
  { rank: Rank 37, english: "week", spanish: "semana" }
  ,
  { rank: Rank 38, english: "month", spanish: "mes" }
  ,
  { rank: Rank 39, english: "each", spanish: "cada" }
  ,
  { rank: Rank 40, english: "time (duration)", spanish: "tiempo" }
  ,
  { rank: Rank 41, english: "to know", spanish: "saber" }
  ,
  { rank: Rank 42, english: "to know (be familiar with)", spanish: "conocer" }
  ,
  { rank: Rank 43, english: "to do", spanish: "hacer" }
  ,
  { rank: Rank 44, english: "to practice", spanish: "practicar" }
  ,
  { rank: Rank 45, english: "to arrive", spanish: "llegar" }
  ,
  { rank: Rank 46, english: "too, also", spanish: "también" }
  ,
  { rank: Rank 47, english: "when", spanish: "cuando" }
  ,
  { rank: Rank 48, english: "until", spanish: "hasta" }
  ,
  { rank: Rank 49, english: "morning", spanish: "mañana" }
  ,
  { rank: Rank 50, english: "he / she", spanish: "él / ella" }
  ,
  { rank: Rank 51, english: "is pleasing to (to like)", spanish: "gustar" }
  ,
  { rank: Rank 52, english: "me", spanish: "me" }
  ,
  { rank: Rank 53, english: "you (one person, object)", spanish: "te" }
  ,
  { rank: Rank 54, english: "you, him, her", spanish: "le" }
  ,
  { rank: Rank 55, english: "us (object)", spanish: "nos" }
  ,
  { rank: Rank 56, english: "them", spanish: "les" }
  ,
  { rank: Rank 57, english: "friend", spanish: "amigo" }
  ,
  { rank: Rank 58, english: "food", spanish: "comida" }
  ,
  { rank: Rank 59, english: "other", spanish: "otro" }
  ,
  { rank: Rank 60, english: "work (job)", spanish: "trabajo" }
  ,
  { rank: Rank 61, english: "for, through", spanish: "por" }
  ,
  { rank: Rank 62, english: "for, in order to", spanish: "para" }
  ,
  { rank: Rank 63, english: "example", spanish: "ejemplo" }
  ,
  { rank: Rank 64, english: "of", spanish: "de" }
  ,
  { rank: Rank 65, english: "in, on", spanish: "en" }
  ,
  { rank: Rank 66, english: "with", spanish: "con" }
  ,
  { rank: Rank 67, english: "to give", spanish: "dar" }
  ,
  { rank: Rank 68, english: "country", spanish: "país" }
  ,
  { rank: Rank 69, english: "man", spanish: "hombre" }
  ,
  { rank: Rank 70, english: "woman", spanish: "mujer" }
  ,
  { rank: Rank 71, english: "to have (done something)", spanish: "haber" }
  ,
  { rank: Rank 72, english: "very", spanish: "muy" }
  ,
  { rank: Rank 73, english: "much", spanish: "mucho" }
  ,
  { rank: Rank 74, english: "large", spanish: "grande" }
  ,
  { rank: Rank 75, english: "less", spanish: "menos" }
  ,
  { rank: Rank 76, english: "little", spanish: "poco" }
  ,
  { rank: Rank 77, english: "thing", spanish: "cosa" }
  ,
  { rank: Rank 78, english: "if", spanish: "si" }
  ,
  { rank: Rank 79, english: "our", spanish: "nuestro" }
  ,
  { rank: Rank 80, english: "always", spanish: "siempre" }
  ,
  { rank: Rank 81, english: "life", spanish: "vida" }
  ,
  { rank: Rank 82, english: "afterwards", spanish: "después" }
  ,
  { rank: Rank 83, english: "then", spanish: "entonces" }
  ,
  { rank: Rank 84, english: "to put, place", spanish: "poner" }
  ,
  { rank: Rank 85, english: "duty", spanish: "deber" }
  ,
  { rank: Rank 86, english: "well (properly)", spanish: "bien" }
  ,
  { rank: Rank 87, english: "between", spanish: "entre" }
  ,
  { rank: Rank 88, english: "word", spanish: "palabra" }
  ,
  { rank: Rank 89, english: "now", spanish: "ahora" }
  ,
  { rank: Rank 90, english: "to learn", spanish: "aprender" }
  ,
  { rank: Rank 91, english: "your", spanish: "tu" }
  ,
  { rank: Rank 92, english: "to believe", spanish: "creer" }
  ,
  { rank: Rank 93, english: "is seeming to (to seem)", spanish: "parecer" }
  ,
  { rank: Rank 94, english: "nothing", spanish: "nada" }
  ,
  { rank: Rank 95, english: "all", spanish: "todo" }
  ,
  { rank: Rank 96, english: "because", spanish: "porque" }
  ,
  { rank: Rank 97, english: "to help", spanish: "ayudar" }
  ,
  { rank: Rank 98, english: "to ask", spanish: "pedir" }
  ,
  { rank: Rank 99, english: "to question", spanish: "preguntar" }
  ,
  { rank: Rank 100, english: "what", spanish: "qué" }
  ,
  { rank: Rank 101, english: "it, the, him", spanish: "lo" }
  ,
  { rank: Rank 102, english: "his, her, their", spanish: "su" }
  ,
  { rank: Rank 103, english: "here", spanish: "aquí" }
  ,
  { rank: Rank 104, english: "already", spanish: "ya" }
  ,
  { rank: Rank 105, english: "without", spanish: "sin" }
  ,
  { rank: Rank 106, english: "time (an occasion)", spanish: "vez" }
  ,
  { rank: Rank 107, english: "there is, there are", spanish: "hay" }
  ,
  { rank: Rank 108, english: "on, about", spanish: "sobre" }
  ,
  { rank: Rank 109, english: "you (informal)", spanish: "tú" }
  ,
  { rank: Rank 110, english: "any, some", spanish: "alguno" }
  ,
  { rank: Rank 111, english: "same", spanish: "mismo" }
  ,
  { rank: Rank 112, english: "like that, so", spanish: "así" }
  ,
  { rank: Rank 113, english: "how", spanish: "cómo" }
  ,
  { rank: Rank 114, english: "two", spanish: "dos" }
  ,
  { rank: Rank 115, english: "only", spanish: "sólo" }
  ,
  { rank: Rank 116, english: "first", spanish: "primero" }
  ,
  { rank: Rank 117, english: "from", spanish: "desde" }
  ,
  { rank: Rank 118, english: "nor", spanish: "ni" }
  ,
  { rank: Rank 119, english: "thanks", spanish: "gracias" }
  ,
  { rank: Rank 120, english: "good", spanish: "bueno" }
  ,
  { rank: Rank 121, english: "one", spanish: "uno" }
  ,
  { rank: Rank 122, english: "you (formal)", spanish: "usted" }
  ,
  { rank: Rank 123, english: "so many, so much", spanish: "tanto" }
  ,
  { rank: Rank 124, english: "Mr.", spanish: "señor" }
  ,
  { rank: Rank 125, english: "such, as, so", spanish: "tan" }
  ,
  { rank: Rank 126, english: "who", spanish: "quién" }
  ,
  { rank: Rank 127, english: "part", spanish: "parte" }
  ,
  { rank: Rank 128, english: "is remaining to (to stay)", spanish: "quedar" }
  ,
  { rank: Rank 129, english: "favor", spanish: "favor" }
  ,
  { rank: Rank 130, english: "where? (asking)", spanish: "dónde" }
  ,
  { rank: Rank 131, english: "never", spanish: "nunca" }
  ,
  { rank: Rank 132, english: "to lead", spanish: "llevar" }
  ,
  { rank: Rank 133, english: "to leave behind, to let", spanish: "dejar" }
  ,
  { rank: Rank 134, english: "truth", spanish: "verdad" }
  ,
  { rank: Rank 135, english: "to follow", spanish: "seguir" }
  ,
  { rank: Rank 136, english: "new", spanish: "nuevo" }
  ,
  { rank: Rank 137, english: "so, then", spanish: "pues" }
  ,
  { rank: Rank 138, english: "to call (be called/name)", spanish: "llamar(se)" }
  ,
  { rank: Rank 139, english: "best", spanish: "mejor" }
  ,
  { rank: Rank 140, english: "to think", spanish: "pensar" }
  ,
  { rank: Rank 141, english: "that (over there)", spanish: "aquel" }
  ,
  { rank: Rank 142, english: "moment", spanish: "momento" }
  ,
  { rank: Rank 143, english: "god", spanish: "dios" }
  ,
  { rank: Rank 144, english: "but, rather", spanish: "sino" }
  ,
  { rank: Rank 145, english: "to go out, to leave", spanish: "salir" }
  ,
  { rank: Rank 146, english: "to return", spanish: "volver" }
  ,
  { rank: Rank 147, english: "form", spanish: "forma" }
  ,
  { rank: Rank 148, english: "before (in time)", spanish: "antes" }
  ,
  { rank: Rank 149, english: "although", spanish: "aunque" }
  ,
  { rank: Rank 150, english: "world", spanish: "mundo" }
  ,
  { rank: Rank 151, english: "three", spanish: "tres" }
  ,
  { rank: Rank 152, english: "such", spanish: "tal" }
  ,
  { rank: Rank 153, english: "there", spanish: "ahí" }
  ,
  { rank: Rank 154, english: "to take, to drink", spanish: "tomar" }
  ,
  { rank: Rank 155, english: "certain", spanish: "cierto" }
  ,
  { rank: Rank 156, english: "to, towards", spanish: "hacia" }
  ,
  { rank: Rank 157, english: "case", spanish: "caso" }
  ,
  { rank: Rank 158, english: "night", spanish: "noche" }
  ,
  { rank: Rank 159, english: "to feel", spanish: "sentir" }
  ,
  { rank: Rank 160, english: "then, later", spanish: "luego" }
  ,
  { rank: Rank 161, english: "someone", spanish: "alguien" }
  ,
  { rank: Rank 162, english: "to treat, deal with", spanish: "tratar" }
  ,
  { rank: Rank 163, english: "person", spanish: "persona" }
  ,
  { rank: Rank 164, english: "higher", spanish: "mayor" }
  ,
  { rank: Rank 165, english: "last", spanish: "último" }
  ,
  { rank: Rank 166, english: "single", spanish: "solo" }
  ,
  { rank: Rank 167, english: "own", spanish: "propio" }
  ,
  { rank: Rank 168, english: "no one", spanish: "nadie" }
  ,
  { rank: Rank 169, english: "whoever", spanish: "quien" }
  ,
  { rank: Rank 170, english: "we", spanish: "nosotros" }
  ,
  { rank: Rank 171, english: "to look", spanish: "mirar" }
  ,
  { rank: Rank 172, english: "father", spanish: "padre" }
  ,
  { rank: Rank 173, english: "time, hour", spanish: "hora" }
  ,
  { rank: Rank 174, english: "people", spanish: "gente" }
  ,
  { rank: Rank 175, english: "none", spanish: "ninguno" }
  ,
  { rank: Rank 176, english: "money", spanish: "dinero" }
  ,
  { rank: Rank 177, english: "almost", spanish: "casi" }
  ,
  { rank: Rank 178, english: "point", spanish: "punto" }
  ,
  { rank: Rank 179, english: "done", spanish: "hecho" }
  ,
  { rank: Rank 180, english: "during", spanish: "durante" }
  ,
  { rank: Rank 181, english: "any", spanish: "cualquier" }
  ,
  { rank: Rank 182, english: "hand", spanish: "mano" }
  ,
  { rank: Rank 183, english: "way", spanish: "manera" }
  ,
  { rank: Rank 184, english: "which", spanish: "cual" }
  ,
  { rank: Rank 185, english: "while", spanish: "mientras" }
  ,
  { rank: Rank 186, english: "to count", spanish: "contar" }
  ,
  { rank: Rank 187, english: "end", spanish: "fin" }
  ,
  { rank: Rank 188, english: "type", spanish: "tipo" }
  ,
  { rank: Rank 189, english: "clear", spanish: "claro" }
  ,
  { rank: Rank 190, english: "also, besides", spanish: "además" }
  ,
  { rank: Rank 191, english: "to start", spanish: "empezar" }
  ,
  { rank: Rank 192, english: "to wait", spanish: "esperar" }
  ,
  { rank: Rank 193, english: "today", spanish: "hoy" }
  ,
  { rank: Rank 194, english: "side", spanish: "lado" }
  ,
  { rank: Rank 195, english: "son", spanish: "hijo" }
  ,
  { rank: Rank 196, english: "there", spanish: "allí" }
  ,
  { rank: Rank 197, english: "this", spanish: "éste" }
  ,
  { rank: Rank 198, english: "problem", spanish: "problema" }
  ,
  { rank: Rank 199, english: "agreement", spanish: "acuerdo" }
  ,
  { rank: Rank 200, english: "account", spanish: "cuenta" }
  ,
  { rank: Rank 201, english: "medium", spanish: "medio" }
  ,
  { rank: Rank 202, english: "against", spanish: "contra" }
  ,
  { rank: Rank 203, english: "out", spanish: "fuera" }
  ,
  { rank: Rank 204, english: "search", spanish: "buscar" }
  ,
  { rank: Rank 205, english: "within", spanish: "dentro" }
  ,
  { rank: Rank 206, english: "long", spanish: "largo" }
  ,
  { rank: Rank 207, english: "safe, secure", spanish: "seguro" }
  ,
  { rank: Rank 208, english: "to exist", spanish: "existir" }
  ,
  { rank: Rank 209, english: "child", spanish: "niño" }
  ,
  { rank: Rank 210, english: "to enter", spanish: "entrar" }
  ,
  { rank: Rank 211, english: "mother", spanish: "madre" }
  ,
  { rank: Rank 212, english: "embargo", spanish: "embargo" }
  ,
  { rank: Rank 213, english: "only one, unique", spanish: "único" }
  ,
  { rank: Rank 214, english: "to work", spanish: "trabajar" }
  ,
  { rank: Rank 215, english: "small", spanish: "pequeño" }
  ,
  { rank: Rank 216, english: "high", spanish: "alto" }
  ,
  { rank: Rank 217, english: "change", spanish: "cambio" }
  ,
  { rank: Rank 218, english: "to write", spanish: "escribir" }
  ,
  { rank: Rank 219, english: "four", spanish: "cuatro" }
  ,
  { rank: Rank 220, english: "to lose", spanish: "perder" }
  ,
  { rank: Rank 221, english: "history", spanish: "historia" }
  ,
  { rank: Rank 222, english: "wait", spanish: "espera" }
  ,
  { rank: Rank 223, english: "idea", spanish: "idea" }
  ,
  { rank: Rank 224, english: "water", spanish: "agua" }
  ,
  { rank: Rank 225, english: "to produce", spanish: "producir" }
  ,
  { rank: Rank 226, english: "city", spanish: "ciudad" }
  ,
  { rank: Rank 227, english: "state", spanish: "estado" }
  ,
  { rank: Rank 228, english: "mode", spanish: "modo" }
  ,
  { rank: Rank 229, english: "name", spanish: "nombre" }
  ,
  { rank: Rank 230, english: "to occur", spanish: "ocurrir" }
  ,
  { rank: Rank 231, english: "family", spanish: "familia" }
  ,
  { rank: Rank 232, english: "reality", spanish: "realidad" }
  ,
  { rank: Rank 233, english: "to understand", spanish: "entender" }
  ,
  { rank: Rank 234, english: "to receive", spanish: "recibir" }
  ,
  { rank: Rank 235, english: "work (of art)", spanish: "obra" }
  ,
  { rank: Rank 236, english: "important", spanish: "importante" }
  ,
  { rank: Rank 237, english: "with me", spanish: "conmigo" }
  ,
  { rank: Rank 238, english: "wrong", spanish: "mal" }
  ,
  { rank: Rank 239, english: "yet", spanish: "todavía" }
  ,
  { rank: Rank 240, english: "reason", spanish: "razón" }
  ,
  { rank: Rank 241, english: "as much as", spanish: "cuanto" }
  ,
  { rank: Rank 242, english: "low", spanish: "bajo" }
  ,
  { rank: Rank 243, english: "to remember", spanish: "recordar" }
  ,
  { rank: Rank 244, english: "group", spanish: "grupo" }
  ,
  { rank: Rank 245, english: "love", spanish: "amor" }
  ,
  { rank: Rank 246, english: "thousand", spanish: "mil" }
  ,
  { rank: Rank 247, english: "mine", spanish: "mío" }
  ,
  { rank: Rank 248, english: "human", spanish: "humano" }
  ,
  { rank: Rank 249, english: "to finish", spanish: "terminar" }
  ,
  { rank: Rank 250, english: "to allow", spanish: "permitir" }
  ,
  { rank: Rank 251, english: "to appear", spanish: "aparecer" }
  ,
  { rank: Rank 252, english: "to get", spanish: "conseguir" }
  ,
  { rank: Rank 253, english: "afternoon", spanish: "tarde" }
  ,
  { rank: Rank 254, english: "to start", spanish: "comenzar" }
  ,
  { rank: Rank 255, english: "several", spanish: "varios" }
  ,
  { rank: Rank 256, english: "possible", spanish: "posible" }
  ,
  { rank: Rank 257, english: "yet", spanish: "aún" }
  ,
  { rank: Rank 258, english: "to serve", spanish: "servir" }
  ,
  { rank: Rank 259, english: "general", spanish: "general" }
  ,
  { rank: Rank 260, english: "to take out", spanish: "sacar" }
  ,
  { rank: Rank 261, english: "relationship", spanish: "relación" }
  ,
  { rank: Rank 262, english: "five", spanish: "cinco" }
  ,
  { rank: Rank 263, english: "body", spanish: "cuerpo" }
  ,
  { rank: Rank 264, english: "with you", spanish: "contigo" }
  ,
  { rank: Rank 265, english: "to maintain", spanish: "mantener" }
  ,
  { rank: Rank 266, english: "faced with", spanish: "ante" }
  ,
  { rank: Rank 267, english: "principle", spanish: "principio" }
  ,
  { rank: Rank 268, english: "to result", spanish: "resultar" }
  ,
  { rank: Rank 269, english: "equal", spanish: "igual" }
  ,
  { rank: Rank 270, english: "too", spanish: "demasiado" }
  ,
  { rank: Rank 271, english: "town", spanish: "pueblo" }
  ,
  { rank: Rank 272, english: "second", spanish: "segundo" }
  ,
  { rank: Rank 273, english: "to read", spanish: "leer" }
  ,
  { rank: Rank 274, english: "to fall", spanish: "caer" }
  ,
  { rank: Rank 275, english: "to change", spanish: "cambiar" }
  ,
  { rank: Rank 276, english: "eye", spanish: "ojo" }
  ,
  { rank: Rank 277, english: "goodbye", spanish: "adiós" }
  ,
  { rank: Rank 278, english: "street", spanish: "calle" }
  ,
  { rank: Rank 279, english: "to present", spanish: "presentar" }
  ,
  { rank: Rank 280, english: "white", spanish: "blanco" }
  ,
  { rank: Rank 281, english: "to create", spanish: "crear" }
  ,
  { rank: Rank 282, english: "to open", spanish: "abrir" }
  ,
  { rank: Rank 283, english: "book", spanish: "libro" }
  ,
  { rank: Rank 284, english: "different", spanish: "distinto" }
  ,
  { rank: Rank 285, english: "force", spanish: "fuerza" }
  ,
  { rank: Rank 286, english: "light", spanish: "luz" }
  ,
  { rank: Rank 287, english: "according to", spanish: "según" }
  ,
  { rank: Rank 288, english: "saint", spanish: "santo" }
  ,
  { rank: Rank 289, english: "front", spanish: "frente" }
  ,
  { rank: Rank 290, english: "to consider", spanish: "considerar" }
  ,
  { rank: Rank 291, english: "really", spanish: "realmente" }
  ,
  { rank: Rank 292, english: "police", spanish: "policía" }
  ,
  { rank: Rank 293, english: "to hear", spanish: "oír" }
  ,
  { rank: Rank 294, english: "whose", spanish: "cuyo" }
  ,
  { rank: Rank 295, english: "sense", spanish: "sentido" }
  ,
  { rank: Rank 296, english: "to end", spanish: "acabar" }
  ,
  { rank: Rank 297, english: "step", spanish: "paso" }
  ,
  { rank: Rank 298, english: "situation", spanish: "situación" }
  ,
  { rank: Rank 299, english: "serious (person)", spanish: "serio" }
  ,
  { rank: Rank 300, english: "head", spanish: "cabeza" }
  ,
  { rank: Rank 301, english: "quite", spanish: "bastante" }
  ,
  { rank: Rank 302, english: "brother", spanish: "hermano" }
  ,
  { rank: Rank 303, english: "to convert", spanish: "convertir" }
  ,
  { rank: Rank 304, english: "grace", spanish: "gracia" }
  ,
  { rank: Rank 305, english: "century", spanish: "siglo" }
  ,
  { rank: Rank 306, english: "last, past", spanish: "pasado" }
  ,
  { rank: Rank 307, english: "bad", spanish: "malo" }
  ,
  { rank: Rank 308, english: "land", spanish: "tierra" }
  ,
  { rank: Rank 309, english: "paper", spanish: "papel" }
  ,
  { rank: Rank 310, english: "affection", spanish: "cariño" }
  ,
  { rank: Rank 311, english: "valid, voucher", spanish: "vale" }
  ,
  { rank: Rank 312, english: "neither", spanish: "tampoco" }
  ,
  { rank: Rank 313, english: "social", spanish: "social" }
  ,
  { rank: Rank 314, english: "old (aged)", spanish: "viejo" }
  ,
  { rank: Rank 315, english: "Mrs.", spanish: "señora" }
  ,
  { rank: Rank 316, english: "topic", spanish: "tema" }
  ,
  { rank: Rank 317, english: "political", spanish: "político" }
  ,
  { rank: Rank 318, english: "Spanish", spanish: "Español" }
  ,
  { rank: Rank 319, english: "dead", spanish: "muerto" }
  ,
  { rank: Rank 320, english: "to win", spanish: "ganar" }
  ,
  { rank: Rank 321, english: "to form", spanish: "formar" }
  ,
  { rank: Rank 322, english: "class", spanish: "clase" }
  ,
  { rank: Rank 323, english: "fast", spanish: "rápido" }
  ,
  { rank: Rank 324, english: "to bring", spanish: "traer" }
  ,
  { rank: Rank 325, english: "to start from, to divide", spanish: "partir" }
  ,
  { rank: Rank 326, english: "to die", spanish: "morir" }
  ,
  { rank: Rank 327, english: "even", spanish: "incluso" }
  ,
  { rank: Rank 328, english: "luck", spanish: "suerte" }
  ,
  { rank: Rank 329, english: "field, country", spanish: "campo" }
  ,
  { rank: Rank 330, english: "care", spanish: "cuidado" }
  ,
  { rank: Rank 331, english: "to accept", spanish: "aceptar" }
  ,
  { rank: Rank 332, english: "perhaps", spanish: "quizás" }
  ,
  { rank: Rank 333, english: "to perform", spanish: "realizar" }
  ,
  { rank: Rank 334, english: "hundred", spanish: "ciento" }
  ,
  { rank: Rank 335, english: "fear", spanish: "miedo" }
  ,
  { rank: Rank 336, english: "order", spanish: "orden" }
  ,
  { rank: Rank 337, english: "door", spanish: "puerta" }
  ,
  { rank: Rank 338, english: "soon", spanish: "pronto" }
  ,
  { rank: Rank 339, english: "to suppose", spanish: "suponer" }
  ,
  { rank: Rank 340, english: "to understand", spanish: "comprender" }
  ,
  { rank: Rank 341, english: "final", spanish: "final" }
  ,
  { rank: Rank 342, english: "interest", spanish: "interés" }
  ,
  { rank: Rank 343, english: "following", spanish: "siguiente" }
  ,
  { rank: Rank 344, english: "view", spanish: "vista" }
  ,
  { rank: Rank 345, english: "to achieve", spanish: "lograr" }
  ,
  { rank: Rank 346, english: "other, the rest", spanish: "demás" }
  ,
  { rank: Rank 347, english: "you (several people, object)", spanish: "os" }
  ,
  { rank: Rank 348, english: "boy", spanish: "chico" }
  ,
  { rank: Rank 349, english: "difficult", spanish: "difícil" }
  ,
  { rank: Rank 350, english: "how much", spanish: "cuánto" }
  ,
  { rank: Rank 351, english: "number", spanish: "número" }
  ,
  { rank: Rank 352, english: "to explain", spanish: "explicar" }
  ,
  { rank: Rank 353, english: "come", spanish: "venga" }
  ,
  { rank: Rank 354, english: "black", spanish: "negro" }
  ,
  { rank: Rank 355, english: "road", spanish: "camino" }
  ,
  { rank: Rank 356, english: "background", spanish: "fondo" }
  ,
  { rank: Rank 357, english: "voice", spanish: "voz" }
  ,
  { rank: Rank 358, english: "study", spanish: "estudio" }
  ,
  { rank: Rank 359, english: "necessary", spanish: "necesario" }
  ,
  { rank: Rank 360, english: "there", spanish: "allá" }
  ,
  { rank: Rank 361, english: "to touch", spanish: "tocar" }
  ,
  { rank: Rank 362, english: "value", spanish: "valor" }
  ,
  { rank: Rank 363, english: "to recognize", spanish: "reconocer" }
  ,
  { rank: Rank 364, english: "to study", spanish: "estudiar" }
  ,
  { rank: Rank 365, english: "to reach", spanish: "alcanzar" }
  ,
  { rank: Rank 366, english: "to be born", spanish: "nacer" }
  ,
  { rank: Rank 367, english: "to direct", spanish: "dirigir" }
  ,
  { rank: Rank 368, english: "to run", spanish: "correr" }
  ,
  { rank: Rank 369, english: "happy", spanish: "feliz" }
  ,
  { rank: Rank 370, english: "measure", spanish: "medida" }
  ,
  { rank: Rank 371, english: "lesser, younger", spanish: "menor" }
  ,
  { rank: Rank 372, english: "war", spanish: "guerra" }
  ,
  { rank: Rank 373, english: "only", spanish: "solamente" }
  ,
  { rank: Rank 374, english: "wife", spanish: "esposa" }
  ,
  { rank: Rank 375, english: "to utilize", spanish: "utilizar" }
  ,
  { rank: Rank 376, english: "forward", spanish: "adelante" }
  ,
  { rank: Rank 377, english: "center", spanish: "centro" }
  ,
  { rank: Rank 378, english: "which one", spanish: "cuál" }
  ,
  { rank: Rank 379, english: "need", spanish: "necesidad" }
  ,
  { rank: Rank 380, english: "condition", spanish: "condición" }
  ,
  { rank: Rank 381, english: "to pay", spanish: "pagar" }
  ,
  { rank: Rank 382, english: "it", spanish: "ello" }
  ,
  { rank: Rank 383, english: "lack", spanish: "falta" }
  ,
  { rank: Rank 384, english: "death", spanish: "muerte" }
  ,
  { rank: Rank 385, english: "ten", spanish: "diez" }
  ,
  { rank: Rank 386, english: "through, across", spanish: "través" }
  ,
  { rank: Rank 387, english: "ancient, former", spanish: "antiguo" }
  ,
  { rank: Rank 388, english: "supposed", spanish: "supuesto" }
  ,
  { rank: Rank 389, english: "age", spanish: "edad" }
  ,
  { rank: Rank 390, english: "to play", spanish: "jugar" }
  ,
  { rank: Rank 391, english: "heart", spanish: "corazón" }
  ,
  { rank: Rank 392, english: "face", spanish: "cara" }
  ,
  { rank: Rank 393, english: "boss, chief", spanish: "jefe" }
  ,
  { rank: Rank 394, english: "era, time", spanish: "época" }
  ,
  { rank: Rank 395, english: "color", spanish: "color" }
  ,
  { rank: Rank 396, english: "to listen", spanish: "escuchar" }
  ,
  { rank: Rank 397, english: "help", spanish: "ayuda" }
  ,
  { rank: Rank 398, english: "experience", spanish: "experiencia" }
  ,
  { rank: Rank 399, english: "movement", spanish: "movimiento" }
  ,
  { rank: Rank 400, english: "to fulfill", spanish: "cumplir" }
  ,
  { rank: Rank 401, english: "special", spanish: "especial" }
  ,
  { rank: Rank 402, english: "different", spanish: "diferente" }
  ,
  { rank: Rank 403, english: "sorrow", spanish: "pesar" }
  ,
  { rank: Rank 404, english: "possibility", spanish: "posibilidad" }
  ,
  { rank: Rank 405, english: "to offer", spanish: "ofrecer" }
  ,
  { rank: Rank 406, english: "up", spanish: "arriba" }
  ,
  { rank: Rank 407, english: "to discover", spanish: "descubrir" }
  ,
  { rank: Rank 408, english: "daughter", spanish: "hija" }
  ,
  { rank: Rank 409, english: "previous", spanish: "anterior" }
  ,
  { rank: Rank 410, english: "game", spanish: "juego" }
  ,
  { rank: Rank 411, english: "to lift (to get up)", spanish: "levantar(se)" }
  ,
  { rank: Rank 412, english: "poor", spanish: "pobre" }
  ,
  { rank: Rank 413, english: "air", spanish: "aire" }
  ,
  { rank: Rank 414, english: "six", spanish: "seis" }
  ,
  { rank: Rank 415, english: "to try", spanish: "intentar" }
  ,
  { rank: Rank 416, english: "together", spanish: "junto" }
  ,
  { rank: Rank 417, english: "result", spanish: "resultado" }
  ,
  { rank: Rank 418, english: "to use", spanish: "usar" }
  ,
  { rank: Rank 419, english: "to decide", spanish: "decidir" }
  ,
  { rank: Rank 420, english: "to repeat", spanish: "repetir" }
  ,
  { rank: Rank 421, english: "to forget", spanish: "olvidar" }
  ,
  { rank: Rank 422, english: "law", spanish: "ley" }
  ,
  { rank: Rank 423, english: "appearance", spanish: "aspecto" }
  ,
  { rank: Rank 424, english: "foot", spanish: "pie" }
  ,
  { rank: Rank 425, english: "worth", spanish: "valer" }
  ,
  { rank: Rank 426, english: "species", spanish: "especie" }
  ,
  { rank: Rank 427, english: "to eat", spanish: "comer" }
  ,
  { rank: Rank 428, english: "service", spanish: "servicio" }
  ,
  { rank: Rank 429, english: "close", spanish: "cerca" }
  ,
  { rank: Rank 430, english: "to show", spanish: "mostrar" }
  ,
  { rank: Rank 431, english: "activity", spanish: "actividad" }
  ,
  { rank: Rank 432, english: "third", spanish: "tercero" }
  ,
  { rank: Rank 433, english: "uncle", spanish: "tío" }
  ,
  { rank: Rank 434, english: "to occupy", spanish: "ocupar" }
  ,
  { rank: Rank 435, english: "matter, issue", spanish: "cuestión" }
  ,
  { rank: Rank 436, english: "doubt", spanish: "duda" }
  ,
  { rank: Rank 437, english: "at least", spanish: "siquiera" }
  ,
  { rank: Rank 438, english: "difference", spanish: "diferencia" }
  ,
  { rank: Rank 439, english: "to move", spanish: "mover" }
  ,
  { rank: Rank 440, english: "to continue", spanish: "continuar" }
  ,
  { rank: Rank 441, english: "amount", spanish: "cantidad" }
  ,
  { rank: Rank 442, english: "action", spanish: "acción" }
  ,
  { rank: Rank 443, english: "to happen", spanish: "suceder" }
  ,
  { rank: Rank 444, english: "to set", spanish: "fijar" }
  ,
  { rank: Rank 445, english: "society", spanish: "sociedad" }
  ,
  { rank: Rank 446, english: "to refer", spanish: "referir" }
  ,
  { rank: Rank 447, english: "to bring closer", spanish: "acercar" }
  ,
  { rank: Rank 448, english: "able", spanish: "capaz" }
  ,
  { rank: Rank 449, english: "free", spanish: "libre" }
  ,
  { rank: Rank 450, english: "natural", spanish: "natural" }
  ,
  { rank: Rank 451, english: "to devote", spanish: "dedicar" }
  ,
  { rank: Rank 452, english: "weight", spanish: "peso" }
  ,
  { rank: Rank 453, english: "effect", spanish: "efecto" }
  ,
  { rank: Rank 454, english: "object", spanish: "objeto" }
  ,
  { rank: Rank 455, english: "doctor", spanish: "doctor" }
  ,
  { rank: Rank 456, english: "TRUE", spanish: "verdadero" }
  ,
  { rank: Rank 457, english: "enough", spanish: "suficiente" }
  ,
  { rank: Rank 458, english: "young", spanish: "joven" }
  ,
  { rank: Rank 459, english: "political party, match", spanish: "partido" }
  ,
  { rank: Rank 460, english: "economic", spanish: "económico" }
  ,
  { rank: Rank 461, english: "below, downstairs", spanish: "abajo" }
  ,
  { rank: Rank 462, english: "right", spanish: "derecho" }
  ,
  { rank: Rank 463, english: "first (before a noun)", spanish: "primer" }
  ,
  { rank: Rank 464, english: "importance", spanish: "importancia" }
  ,
  { rank: Rank 465, english: "brilliant", spanish: "genial" }
  ,
  { rank: Rank 466, english: "system", spanish: "sistema" }
  ,
  { rank: Rank 467, english: "just", spanish: "justo" }
  ,
  { rank: Rank 468, english: "trip", spanish: "viaje" }
  ,
  { rank: Rank 469, english: "soil", spanish: "suelo" }
  ,
  { rank: Rank 470, english: "respect, in regards to", spanish: "respecto" }
  ,
  { rank: Rank 471, english: "knowledge", spanish: "conocimiento" }
  ,
  { rank: Rank 472, english: "freedom", spanish: "libertad" }
  ,
  { rank: Rank 473, english: "above", spanish: "encima" }
  ,
  { rank: Rank 474, english: "to buy", spanish: "comprar" }
  ,
  { rank: Rank 475, english: "common", spanish: "común" }
  ,
  { rank: Rank 476, english: "open", spanish: "abierto" }
  ,
  { rank: Rank 477, english: "next", spanish: "próximo" }
  ,
  { rank: Rank 478, english: "strong", spanish: "fuerte" }
  ,
  { rank: Rank 479, english: "attention", spanish: "atención" }
  ,
  { rank: Rank 480, english: "to rise", spanish: "subir" }
  ,
  { rank: Rank 481, english: "effort", spanish: "esfuerzo" }
  ,
  { rank: Rank 482, english: "to avoid", spanish: "evitar" }
  ,
  { rank: Rank 483, english: "rest", spanish: "resto" }
  ,
  { rank: Rank 484, english: "is interesting to (to interest)", spanish: "interesar" }
  ,
  { rank: Rank 485, english: "back, backwards", spanish: "atrás" }
  ,
  { rank: Rank 486, english: "area", spanish: "zona" }
  ,
  { rank: Rank 487, english: "process", spanish: "proceso" }
  ,
  { rank: Rank 488, english: "alive", spanish: "vivo" }
  ,
  { rank: Rank 489, english: "to close, shut", spanish: "cerrar" }
  ,
  { rank: Rank 490, english: "wine", spanish: "vino" }
  ,
  { rank: Rank 491, english: "to throw, cast", spanish: "echar" }
  ,
  { rank: Rank 492, english: "to reply", spanish: "responder" }
  ,
  { rank: Rank 493, english: "to suffer", spanish: "sufrir" }
  ,
  { rank: Rank 494, english: "complete", spanish: "completo" }
  ,
  { rank: Rank 495, english: "minute", spanish: "minuto" }
  ,
  { rank: Rank 496, english: "school", spanish: "escuela" }
  ,
  { rank: Rank 497, english: "contrary", spanish: "contrario" }
  ,
  { rank: Rank 498, english: "table (furniture)", spanish: "mesa" }
  ,
  { rank: Rank 499, english: "real", spanish: "real" }
  ,
  { rank: Rank 500, english: "occasion", spanish: "ocasión" }
  ,
  { rank: Rank 501, english: "blood", spanish: "sangre" }
  ,
  { rank: Rank 502, english: "is important to (to matter)", spanish: "importar" }
  ,
  { rank: Rank 503, english: "public", spanish: "público" }
  ,
  { rank: Rank 504, english: "car", spanish: "coche" }
  ,
  { rank: Rank 505, english: "to obtain", spanish: "obtener" }
  ,
  { rank: Rank 506, english: "program", spanish: "programa" }
  ,
  { rank: Rank 507, english: "away", spanish: "lejos" }
  ,
  { rank: Rank 508, english: "seven", spanish: "siete" }
  ,
  { rank: Rank 509, english: "huge", spanish: "enorme" }
  ,
  { rank: Rank 510, english: "response", spanish: "respuesta" }
  ,
  { rank: Rank 511, english: "line", spanish: "línea" }
  ,
  { rank: Rank 512, english: "space", spanish: "espacio" }
  ,
  { rank: Rank 513, english: "level", spanish: "nivel" }
  ,
  { rank: Rank 514, english: "peace", spanish: "paz" }
  ,
  { rank: Rank 515, english: "government", spanish: "gobierno" }
  ,
  { rank: Rank 516, english: "end, cape", spanish: "cabo" }
  ,
  { rank: Rank 517, english: "return", spanish: "vuelta" }
  ,
  { rank: Rank 518, english: "to observe", spanish: "observar" }
  ,
  { rank: Rank 519, english: "to indicate", spanish: "indicar" }
  ,
  { rank: Rank 520, english: "question", spanish: "pregunta" }
  ,
  { rank: Rank 521, english: "image", spanish: "imagen" }
  ,
  { rank: Rank 522, english: "career", spanish: "carrera" }
  ,
  { rank: Rank 523, english: "fault", spanish: "culpa" }
  ,
  { rank: Rank 524, english: "to imagine", spanish: "imaginar" }
  ,
  { rank: Rank 525, english: "to be in the habit of", spanish: "soler" }
  ,
  { rank: Rank 526, english: "both", spanish: "ambos" }
  ,
  { rank: Rank 527, english: "to accompany", spanish: "acompañar" }
  ,
  { rank: Rank 528, english: "deep", spanish: "profundo" }
  ,
  { rank: Rank 529, english: "to stop", spanish: "detener" }
  ,
  { rank: Rank 530, english: "to develop", spanish: "desarrollar" }
  ,
  { rank: Rank 531, english: "eight", spanish: "ocho" }
  ,
  { rank: Rank 532, english: "easy", spanish: "fácil" }
  ,
  { rank: Rank 533, english: "to signal", spanish: "señalar" }
  ,
  { rank: Rank 534, english: "to choose", spanish: "elegir" }
  ,
  { rank: Rank 535, english: "figure", spanish: "figura" }
  ,
  { rank: Rank 536, english: "main", spanish: "principal" }
  ,
  { rank: Rank 537, english: "to sleep", spanish: "dormir" }
  ,
  { rank: Rank 538, english: "animal", spanish: "animal" }
  ,
  { rank: Rank 539, english: "base", spanish: "base" }
  ,
  { rank: Rank 540, english: "to prepare", spanish: "preparar" }
  ,
  { rank: Rank 541, english: "to propose", spanish: "proponer" }
  ,
  { rank: Rank 542, english: "to demonstrate, prove", spanish: "demostrar" }
  ,
  { rank: Rank 543, english: "party, celebration", spanish: "fiesta" }
  ,
  { rank: Rank 544, english: "to mean", spanish: "significar" }
  ,
  { rank: Rank 545, english: "position", spanish: "posición" }
  ,
  { rank: Rank 546, english: "bed", spanish: "cama" }
  ,
  { rank: Rank 547, english: "motive", spanish: "motivo" }
  ,
  { rank: Rank 548, english: "test", spanish: "prueba" }
  ,
  { rank: Rank 549, english: "policy", spanish: "politica" }
  ,
  { rank: Rank 550, english: "national", spanish: "nacional" }
  ,
  { rank: Rank 551, english: "full (filled up)", spanish: "lleno" }
  ,
  { rank: Rank 552, english: "phone", spanish: "teléfono" }
  ,
  { rank: Rank 553, english: "to gather", spanish: "reunir" }
  ,
  { rank: Rank 554, english: "Is missing to (to lack)", spanish: "faltar" }
  ,
  { rank: Rank 555, english: "team", spanish: "equipo" }
  ,
  { rank: Rank 556, english: "datum", spanish: "dato" }
  ,
  { rank: Rank 557, english: "to wish", spanish: "desear" }
  ,
  { rank: Rank 558, english: "company, firm", spanish: "empresa" }
  ,
  { rank: Rank 559, english: "issue", spanish: "asunto" }
  ,
  { rank: Rank 560, english: "presence", spanish: "presencia" }
  ,
  { rank: Rank 561, english: "his, hers, theirs", spanish: "suyo" }
  ,
  { rank: Rank 562, english: "culture", spanish: "cultura" }
  ,
  { rank: Rank 563, english: "series", spanish: "serie" }
  ,
  { rank: Rank 564, english: "million", spanish: "millón" }
  ,
  { rank: Rank 565, english: "to teach", spanish: "enseñar" }
  ,
  { rank: Rank 566, english: "to build", spanish: "construir" }
  ,
  { rank: Rank 567, english: "opportunity", spanish: "oportunidad" }
  ,
  { rank: Rank 568, english: "to sell", spanish: "vender" }
  ,
  { rank: Rank 569, english: "to kill", spanish: "matar" }
  ,
  { rank: Rank 570, english: "to represent", spanish: "representar" }
  ,
  { rank: Rank 571, english: "to disappear", spanish: "desaparecer" }
  ,
  { rank: Rank 572, english: "to send, to order", spanish: "mandar" }
  ,
  { rank: Rank 573, english: "character (nature)", spanish: "carácter" }
  ,
  { rank: Rank 574, english: "where to? (asking)", spanish: "adónde" }
  ,
  { rank: Rank 575, english: "most", spanish: "mayoría" }
  ,
  { rank: Rank 576, english: "red", spanish: "rojo" }
  ,
  { rank: Rank 577, english: "after, behind", spanish: "tras" }
  ,
  { rank: Rank 578, english: "top", spanish: "superior" }
  ,
  { rank: Rank 579, english: "to walk", spanish: "andar" }
  ,
  { rank: Rank 580, english: "short", spanish: "corto" }
  ,
  { rank: Rank 581, english: "author", spanish: "autor" }
  ,
  { rank: Rank 582, english: "fourth", spanish: "cuarto" }
  ,
  { rank: Rank 583, english: "sky", spanish: "cielo" }
  ,
  { rank: Rank 584, english: "known", spanish: "conocido" }
  ,
  { rank: Rank 585, english: "to prefer", spanish: "preferir" }
  ,
  { rank: Rank 586, english: "memory (a recollection)", spanish: "recuerdo" }
  ,
  { rank: Rank 587, english: "to ensure", spanish: "asegurar" }
  ,
  { rank: Rank 588, english: "forgiveness", spanish: "perdón" }
  ,
  { rank: Rank 589, english: "function", spanish: "función" }
  ,
  { rank: Rank 590, english: "cause", spanish: "causa" }
  ,
  { rank: Rank 591, english: "grave, severe", spanish: "grave" }
  ,
  { rank: Rank 592, english: "decision", spanish: "decisión" }
  ,
  { rank: Rank 593, english: "music", spanish: "música" }
  ,
  { rank: Rank 594, english: "strange", spanish: "extraño" }
  ,
  { rank: Rank 595, english: "to grow", spanish: "crecer" }
  ,
  { rank: Rank 596, english: "to emerge", spanish: "surgir" }
  ,
  { rank: Rank 597, english: "movie", spanish: "película" }
  ,
  { rank: Rank 598, english: "expression", spanish: "expresión" }
  ,
  { rank: Rank 599, english: "husband", spanish: "marido" }
  ,
  { rank: Rank 600, english: "around", spanish: "alrededor" }
  ,
  { rank: Rank 601, english: "dog", spanish: "perro" }
  ,
  { rank: Rank 602, english: "to deliver", spanish: "entregar" }
  ,
  { rank: Rank 603, english: "river", spanish: "río" }
  ,
  { rank: Rank 604, english: "exactly", spanish: "exactamente" }
  ,
  { rank: Rank 605, english: "security", spanish: "seguridad" }
  ,
  { rank: Rank 606, english: "king", spanish: "rey" }
  ,
  { rank: Rank 607, english: "term", spanish: "término" }
  ,
  { rank: Rank 608, english: "to place", spanish: "colocar" }
  ,
  { rank: Rank 609, english: "metro", spanish: "metro" }
  ,
  { rank: Rank 610, english: "physician", spanish: "médico" }
  ,
  { rank: Rank 611, english: "room (bedroom)", spanish: "habitación" }
  ,
  { rank: Rank 612, english: "to establish", spanish: "establecer" }
  ,
  { rank: Rank 613, english: "to keep, to store", spanish: "guardar" }
  ,
  { rank: Rank 614, english: "art", spanish: "arte" }
  ,
  { rank: Rank 615, english: "pair", spanish: "par" }
  ,
  { rank: Rank 616, english: "to start", spanish: "iniciar" }
  ,
  { rank: Rank 617, english: "fire", spanish: "fuego" }
  ,
  { rank: Rank 618, english: "to lower", spanish: "bajar" }
  ,
  { rank: Rank 619, english: "consequence", spanish: "consecuencia" }
  ,
  { rank: Rank 620, english: "to note", spanish: "notar" }
  ,
  { rank: Rank 621, english: "act", spanish: "acto" }
  ,
  { rank: Rank 622, english: "to put inside", spanish: "meter" }
  ,
  { rank: Rank 623, english: "absolute", spanish: "absoluto" }
  ,
  { rank: Rank 624, english: "penalty", spanish: "pena" }
  ,
  { rank: Rank 625, english: "to act", spanish: "actuar" }
  ,
  { rank: Rank 626, english: "height", spanish: "altura" }
  ,
  { rank: Rank 627, english: "desire", spanish: "deseo" }
  ,
  { rank: Rank 628, english: "out, outside", spanish: "afuera" }
  ,
  { rank: Rank 629, english: "precisely", spanish: "precisamente" }
  ,
  { rank: Rank 630, english: "twenty", spanish: "veinte" }
  ,
  { rank: Rank 631, english: "dream", spanish: "sueño" }
  ,
  { rank: Rank 632, english: "claim", spanish: "pretender" }
  ,
  { rank: Rank 633, english: "task", spanish: "tarea" }
  ,
  { rank: Rank 634, english: "coffee", spanish: "café" }
  ,
  { rank: Rank 635, english: "letter (you send)", spanish: "carta" }
  ,
  { rank: Rank 636, english: "barely, just", spanish: "apenas" }
  ,
  { rank: Rank 637, english: "property", spanish: "propiedad" }
  ,
  { rank: Rank 638, english: "product", spanish: "producto" }
  ,
  { rank: Rank 639, english: "personal", spanish: "personal" }
  ,
  { rank: Rank 640, english: "simply", spanish: "simplemente" }
  ,
  { rank: Rank 641, english: "impossible", spanish: "imposible" }
  ,
  { rank: Rank 642, english: "taste", spanish: "gusto" }
  ,
  { rank: Rank 643, english: "to agree (remember)", spanish: "acordar(se)" }
  ,
  { rank: Rank 644, english: "site", spanish: "sitio" }
  ,
  { rank: Rank 645, english: "language, tongue", spanish: "lengua" }
  ,
  { rank: Rank 646, english: "to cut", spanish: "cortar" }
  ,
  { rank: Rank 647, english: "plan", spanish: "plan" }
  ,
  { rank: Rank 648, english: "baby", spanish: "bebé" }
  ,
  { rank: Rank 649, english: "to correspond", spanish: "corresponder" }
  ,
  { rank: Rank 650, english: "to break", spanish: "romper" }
  ,
  { rank: Rank 651, english: "never", spanish: "jamás" }
  ,
  { rank: Rank 652, english: "to acquire", spanish: "adquirir" }
  ,
  { rank: Rank 653, english: "weapon", spanish: "arma" }
  ,
  { rank: Rank 654, english: "project", spanish: "proyecto" }
  ,
  { rank: Rank 655, english: "memory (the faculty)", spanish: "memoria" }
  ,
  { rank: Rank 656, english: "origin", spanish: "origen" }
  ,
  { rank: Rank 657, english: "element", spanish: "elemento" }
  ,
  { rank: Rank 658, english: "lost", spanish: "perdido" }
  ,
  { rank: Rank 659, english: "English", spanish: "inglés" }
  ,
  { rank: Rank 660, english: "market", spanish: "mercado" }
  ,
  { rank: Rank 661, english: "course", spanish: "curso" }
  ,
  { rank: Rank 662, english: "to launch", spanish: "lanzar" }
  ,
  { rank: Rank 663, english: "given", spanish: "dado" }
  ,
  { rank: Rank 664, english: "to take advantage of", spanish: "aprovechar" }
  ,
  { rank: Rank 665, english: "interior", spanish: "interior" }
  ,
  { rank: Rank 666, english: "hard", spanish: "duro" }
  ,
  { rank: Rank 667, english: "to support", spanish: "apoyar" }
  ,
  { rank: Rank 668, english: "worse", spanish: "peor" }
  ,
  { rank: Rank 669, english: "deny", spanish: "negar" }
  ,
  { rank: Rank 670, english: "advance", spanish: "avanzar" }
  ,
  { rank: Rank 671, english: "usage", spanish: "uso" }
  ,
  { rank: Rank 672, english: "arm", spanish: "brazo" }
  ,
  { rank: Rank 673, english: "teacher, professor", spanish: "profesor" }
  ,
  { rank: Rank 674, english: "resolve", spanish: "resolver" }
  ,
  { rank: Rank 675, english: "future", spanish: "futuro" }
  ,
  { rank: Rank 676, english: "half", spanish: "mitad" }
  ,
  { rank: Rank 677, english: "clothing", spanish: "ropa" }
  ,
  { rank: Rank 678, english: "is costly to (to cost)", spanish: "costar" }
  ,
  { rank: Rank 679, english: "rich", spanish: "rico" }
  ,
  { rank: Rank 680, english: "total", spanish: "total" }
  ,
  { rank: Rank 681, english: "to require", spanish: "exigir" }
  ,
  { rank: Rank 682, english: "opinion", spanish: "opinión" }
  ,
  { rank: Rank 683, english: "to increase", spanish: "aumentar" }
  ,
  { rank: Rank 684, english: "to collect", spanish: "recoger" }
  ,
  { rank: Rank 685, english: "mouth", spanish: "boca" }
  ,
  { rank: Rank 686, english: "address", spanish: "dirección" }
  ,
  { rank: Rank 687, english: "pure", spanish: "puro" }
  ,
  { rank: Rank 688, english: "president", spanish: "presidente" }
  ,
  { rank: Rank 689, english: "to abandon", spanish: "abandonar" }
  ,
  { rank: Rank 690, english: "piece", spanish: "pieza" }
  ,
  { rank: Rank 691, english: "last night", spanish: "anoche" }
  ,
  { rank: Rank 692, english: "professional", spanish: "profesional" }
  ,
  { rank: Rank 693, english: "to impose", spanish: "imponer" }
  ,
  { rank: Rank 694, english: "concerning", spanish: "acerca" }
  ,
  { rank: Rank 695, english: "to force", spanish: "obligar" }
  ,
  { rank: Rank 696, english: "physical", spanish: "físico" }
  ,
  { rank: Rank 697, english: "attitude", spanish: "actitud" }
  ,
  { rank: Rank 698, english: "sea", spanish: "mar" }
  ,
  { rank: Rank 699, english: "entry", spanish: "entrada" }
  ,
  { rank: Rank 700, english: "contact", spanish: "contacto" }
  ,
  { rank: Rank 701, english: "to apply", spanish: "aplicar" }
  ,
  { rank: Rank 702, english: "correct", spanish: "correcto" }
  ,
  { rank: Rank 703, english: "capital", spanish: "capital" }
  ,
  { rank: Rank 704, english: "title", spanish: "título" }
  ,
  { rank: Rank 705, english: "behind", spanish: "detrás" }
  ,
  { rank: Rank 706, english: "post", spanish: "puesto" }
  ,
  { rank: Rank 707, english: "material", spanish: "material" }
  ,
  { rank: Rank 708, english: "blow", spanish: "golpe" }
  ,
  { rank: Rank 709, english: "to dispose", spanish: "disponer" }
  ,
  { rank: Rank 710, english: "communication", spanish: "comunicación" }
  ,
  { rank: Rank 711, english: "to express", spanish: "expresar" }
  ,
  { rank: Rank 712, english: "sorry", spanish: "disculpe" }
  ,
  { rank: Rank 713, english: "simple", spanish: "simple" }
  ,
  { rank: Rank 714, english: "completely", spanish: "totalmente" }
  ,
  { rank: Rank 715, english: "to provoke", spanish: "provocar" }
  ,
  { rank: Rank 716, english: "normal", spanish: "normal" }
  ,
  { rank: Rank 717, english: "to defend", spanish: "defender" }
  ,
  { rank: Rank 718, english: "disease", spanish: "enfermedad" }
  ,
  { rank: Rank 719, english: "matter", spanish: "materia" }
  ,
  { rank: Rank 720, english: "to take away", spanish: "quitar" }
  ,
  { rank: Rank 721, english: "to conserve", spanish: "conservar" }
  ,
  { rank: Rank 722, english: "modern", spanish: "moderno" }
  ,
  { rank: Rank 723, english: "hospital", spanish: "hospital" }
  ,
  { rank: Rank 724, english: "to depend", spanish: "depender" }
  ,
  { rank: Rank 725, english: "nature", spanish: "naturaleza" }
  ,
  { rank: Rank 726, english: "capacity", spanish: "capacidad" }
  ,
  { rank: Rank 727, english: "current, present-day", spanish: "actual" }
  ,
  { rank: Rank 728, english: "mark", spanish: "marcar" }
  ,
  { rank: Rank 729, english: "distance", spanish: "distancia" }
  ,
  { rank: Rank 730, english: "full, in the middle of", spanish: "pleno" }
  ,
  { rank: Rank 731, english: "perfect", spanish: "perfecto" }
  ,
  { rank: Rank 732, english: "closed", spanish: "cerrado" }
  ,
  { rank: Rank 733, english: "to share", spanish: "compartir" }
  ,
  { rank: Rank 734, english: "quiet", spanish: "tranquilo" }
  ,
  { rank: Rank 735, english: "information", spanish: "información" }
  ,
  { rank: Rank 736, english: "environment", spanish: "ambiente" }
  ,
  { rank: Rank 737, english: "especially", spanish: "especialmente" }
  ,
  { rank: Rank 738, english: "development", spanish: "desarrollo" }
  ,
  { rank: Rank 739, english: "sun", spanish: "sol" }
  ,
  { rank: Rank 740, english: "to consist", spanish: "consistir" }
  ,
  { rank: Rank 741, english: "probably", spanish: "probablemente" }
  ,
  { rank: Rank 742, english: "to constitute", spanish: "constituir" }
  ,
  { rank: Rank 743, english: "yesterday", spanish: "ayer" }
  ,
  { rank: Rank 744, english: "ready", spanish: "dispuesto" }
  ,
  { rank: Rank 745, english: "to cover", spanish: "cubrir" }
  ,
  { rank: Rank 746, english: "to function", spanish: "funcionar" }
  ,
  { rank: Rank 747, english: "partner", spanish: "compañero" }
  ,
  { rank: Rank 748, english: "nice", spanish: "bonito" }
  ,
  { rank: Rank 749, english: "output", spanish: "salida" }
  ,
  { rank: Rank 750, english: "to fit", spanish: "caber" }
  ,
  { rank: Rank 751, english: "awareness", spanish: "conciencia" }
  ,
  { rank: Rank 752, english: "to meet", spanish: "atender" }
  ,
  { rank: Rank 753, english: "sick", spanish: "enfermo" }
  ,
  { rank: Rank 754, english: "incredible", spanish: "increíble" }
  ,
  { rank: Rank 755, english: "to insist", spanish: "insistir" }
  ,
  { rank: Rank 756, english: "custom", spanish: "costumbre" }
  ,
  { rank: Rank 757, english: "silly", spanish: "tonto" }
  ,
  { rank: Rank 758, english: "news", spanish: "noticia" }
  ,
  { rank: Rank 759, english: "circumstance", spanish: "circunstancia" }
  ,
  { rank: Rank 760, english: "is painful to (to hurt)", spanish: "doler" }
  ,
  { rank: Rank 761, english: "private", spanish: "privado" }
  ,
  { rank: Rank 762, english: "style", spanish: "estilo" }
  ,
  { rank: Rank 763, english: "price", spanish: "precio" }
  ,
  { rank: Rank 764, english: "popular", spanish: "popular" }
  ,
  { rank: Rank 765, english: "to sit", spanish: "sentar" }
  ,
  { rank: Rank 766, english: "plant", spanish: "planta" }
  ,
  { rank: Rank 767, english: "that", spanish: "ése" }
  ,
  { rank: Rank 768, english: "character (in a story)", spanish: "personaje" }
  ,
  { rank: Rank 769, english: "famous", spanish: "famoso" }
  ,
  { rank: Rank 770, english: "hunger", spanish: "hambre" }
  ,
  { rank: Rank 771, english: "success", spanish: "éxito" }
  ,
  { rank: Rank 772, english: "to merit", spanish: "merecer" }
  ,
  { rank: Rank 773, english: "building", spanish: "edificio" }
  ,
  { rank: Rank 774, english: "authority", spanish: "autoridad" }
  ,
  { rank: Rank 775, english: "stone", spanish: "piedra" }
  ,
  { rank: Rank 776, english: "to include", spanish: "incluir" }
  ,
  { rank: Rank 777, english: "boat", spanish: "barco" }
  ,
  { rank: Rank 778, english: "set", spanish: "conjunto" }
  ,
  { rank: Rank 779, english: "hotel", spanish: "hotel" }
  ,
  { rank: Rank 780, english: "thirty", spanish: "treinta" }
  ,
  { rank: Rank 781, english: "immediate", spanish: "inmediato" }
  ,
  { rank: Rank 782, english: "to cross", spanish: "cruzar" }
  ,
  { rank: Rank 783, english: "yours", spanish: "tuyo" }
  ,
  { rank: Rank 784, english: "to tend", spanish: "tender" }
  ,
  { rank: Rank 785, english: "finally", spanish: "finalmente" }
  ,
  { rank: Rank 786, english: "to advertise", spanish: "anunciar" }
  ,
  { rank: Rank 787, english: "bath", spanish: "baño" }
  ,
  { rank: Rank 788, english: "spirit", spanish: "espíritu" }
  ,
  { rank: Rank 789, english: "member", spanish: "miembro" }
  ,
  { rank: Rank 790, english: "direct", spanish: "directo" }
  ,
  { rank: Rank 791, english: "pleasure", spanish: "placer" }
  ,
  { rank: Rank 792, english: "to wake", spanish: "despertar" }
  ,
  { rank: Rank 793, english: "resource", spanish: "recurso" }
  ,
  { rank: Rank 794, english: "wall", spanish: "pared" }
  ,
  { rank: Rank 795, english: "error", spanish: "error" }
  ,
  { rank: Rank 796, english: "accurate", spanish: "preciso" }
  ,
  { rank: Rank 797, english: "miscellaneous", spanish: "diverso" }
  ,
  { rank: Rank 798, english: "difficulty", spanish: "dificultad" }
  ,
  { rank: Rank 799, english: "to comment", spanish: "comentar" }
  ,
  { rank: Rank 800, english: "to publish", spanish: "publicar" }
  ,
  { rank: Rank 801, english: "family, familiar", spanish: "familiar" }
  ,
  { rank: Rank 802, english: "will", spanish: "voluntad" }
  ,
  { rank: Rank 803, english: "meeting", spanish: "reunión" }
  ,
  { rank: Rank 804, english: "model", spanish: "modelo" }
  ,
  { rank: Rank 805, english: "secret", spanish: "secreto" }
  ,
  { rank: Rank 806, english: "to load", spanish: "cargar" }
  ,
  { rank: Rank 807, english: "date", spanish: "fecha" }
  ,
  { rank: Rank 808, english: "to participate", spanish: "participar" }
  ,
  { rank: Rank 809, english: "train", spanish: "tren" }
  ,
  { rank: Rank 810, english: "to prevent", spanish: "impedir" }
  ,
  { rank: Rank 811, english: "purpose", spanish: "propósito" }
  ,
  { rank: Rank 812, english: "to rescue", spanish: "salvar" }
  ,
  { rank: Rank 813, english: "hurry", spanish: "prisa" }
  ,
  { rank: Rank 814, english: "degree", spanish: "grado" }
  ,
  { rank: Rank 815, english: "to escape", spanish: "escapar" }
  ,
  { rank: Rank 816, english: "deal", spanish: "negocio" }
  ,
  { rank: Rank 817, english: "fight", spanish: "lucha" }
  ,
  { rank: Rank 818, english: "to throw", spanish: "tirar" }
  ,
  { rank: Rank 819, english: "whole", spanish: "entero" }
  ,
  { rank: Rank 820, english: "interesting", spanish: "interesante" }
  ,
  { rank: Rank 821, english: "wide", spanish: "amplio" }
  ,
  { rank: Rank 822, english: "silence", spanish: "silencio" }
  ,
  { rank: Rank 823, english: "to answer", spanish: "contestar" }
  ,
  { rank: Rank 824, english: "newspaper", spanish: "periódico" }
  ,
  { rank: Rank 825, english: "is worrying to (to worry)", spanish: "preocupar" }
  ,
  { rank: Rank 826, english: "schoolteacher, master", spanish: "maestro" }
  ,
  { rank: Rank 827, english: "provide", spanish: "prestar" }
  ,
  { rank: Rank 828, english: "quality", spanish: "calidad" }
  ,
  { rank: Rank 829, english: "salt", spanish: "sal" }
  ,
  { rank: Rank 830, english: "to exhibit", spanish: "exponer" }
  ,
  { rank: Rank 831, english: "control", spanish: "control" }
  ,
  { rank: Rank 832, english: "civil", spanish: "civil" }
  ,
  { rank: Rank 833, english: "rare", spanish: "raro" }
  ,
  { rank: Rank 834, english: "science", spanish: "ciencia" }
  ,
  { rank: Rank 835, english: "size", spanish: "tamaño" }
  ,
  { rank: Rank 836, english: "chart, painting", spanish: "cuadro" }
  ,
  { rank: Rank 837, english: "horse", spanish: "caballo" }
  ,
  { rank: Rank 838, english: "responsibility", spanish: "responsabilidad" }
  ,
  { rank: Rank 839, english: "fifty", spanish: "cincuenta" }
  ,
  { rank: Rank 840, english: "internal", spanish: "interno" }
  ,
  { rank: Rank 841, english: "detail", spanish: "detalle" }
  ,
  { rank: Rank 842, english: "march", spanish: "marcha" }
  ,
  { rank: Rank 843, english: "nine", spanish: "nueve" }
  ,
  { rank: Rank 844, english: "meat", spanish: "carne" }
  ,
  { rank: Rank 845, english: "plane", spanish: "avión" }
  ,
  { rank: Rank 846, english: "hair", spanish: "pelo" }
  ,
  { rank: Rank 847, english: "thought", spanish: "pensamiento" }
  ,
  { rank: Rank 848, english: "to travel", spanish: "viajar" }
  ,
  { rank: Rank 849, english: "charge", spanish: "cargo" }
  ,
  { rank: Rank 850, english: "to separate", spanish: "separar" }
  ,
  { rank: Rank 851, english: "construction", spanish: "construcción" }
  ,
  { rank: Rank 852, english: "trial", spanish: "juicio" }
  ,
  { rank: Rank 853, english: "ground", spanish: "terreno" }
  ,
  { rank: Rank 854, english: "floor", spanish: "piso" }
  ,
  { rank: Rank 855, english: "companionship, company", spanish: "compañia" }
  ,
  { rank: Rank 856, english: "gold", spanish: "oro" }
  ,
  { rank: Rank 857, english: "to return", spanish: "regresar" }
  ,
  { rank: Rank 858, english: "text", spanish: "texto" }
  ,
  { rank: Rank 859, english: "source", spanish: "fuente" }
  ,
  { rank: Rank 860, english: "present", spanish: "presente" }
  ,
  { rank: Rank 861, english: "official", spanish: "oficial" }
  ,
  { rank: Rank 862, english: "difinitive", spanish: "difinitivo" }
  ,
  { rank: Rank 863, english: "magazine", spanish: "revista" }
  ,
  { rank: Rank 864, english: "damage", spanish: "daño" }
  ,
  { rank: Rank 865, english: "hope", spanish: "esperanza" }
  ,
  { rank: Rank 866, english: "machine", spanish: "máquina" }
  ,
  { rank: Rank 867, english: "to contemplate", spanish: "contemplar" }
  ,
  { rank: Rank 868, english: "to travel through, cover", spanish: "recorrer" }
  ,
  { rank: Rank 869, english: "mind", spanish: "mente" }
  ,
  { rank: Rank 870, english: "phrase", spanish: "frase" }
  ,
  { rank: Rank 871, english: "exercise", spanish: "ejercicio" }
  ,
  { rank: Rank 872, english: "hall, living room", spanish: "sala" }
  ,
  { rank: Rank 873, english: "to last", spanish: "durar" }
  ,
  { rank: Rank 874, english: "instrument", spanish: "instrumento" }
  ,
  { rank: Rank 875, english: "that thing", spanish: "aquello" }
  ,
  { rank: Rank 876, english: "defense", spanish: "defensa" }
  ,
  { rank: Rank 877, english: "director", spanish: "director" }
  ,
  { rank: Rank 878, english: "to withdraw", spanish: "retirar" }
  ,
  { rank: Rank 879, english: "explanation", spanish: "explicación" }
  ,
  { rank: Rank 880, english: "article", spanish: "artículo" }
  ,
  { rank: Rank 881, english: "underneath", spanish: "debajo" }
  ,
  { rank: Rank 882, english: "to remain", spanish: "permanecer" }
  ,
  { rank: Rank 883, english: "to attend", spanish: "asistir" }
  ,
  { rank: Rank 884, english: "twelve", spanish: "doce" }
  ,
  { rank: Rank 885, english: "permission", spanish: "permiso" }
  ,
  { rank: Rank 886, english: "radio", spanish: "radio" }
  ,
  { rank: Rank 887, english: "to organize", spanish: "organizar" }
  ,
  { rank: Rank 888, english: "choice", spanish: "elección" }
  ,
  { rank: Rank 889, english: "visit", spanish: "visita" }
  ,
  { rank: Rank 890, english: "funny", spanish: "divertido" }
  ,
  { rank: Rank 891, english: "to contain", spanish: "contener" }
  ,
  { rank: Rank 892, english: "support", spanish: "apoyo" }
  ,
  { rank: Rank 893, english: "tree", spanish: "árbol" }
  ,
  { rank: Rank 894, english: "to visit", spanish: "visitar" }
  ,
  { rank: Rank 895, english: "to report", spanish: "informar" }
  ,
  { rank: Rank 896, english: "encounter", spanish: "encuentro" }
  ,
  { rank: Rank 897, english: "sex", spanish: "sexo" }
  ,
  { rank: Rank 898, english: "like", spanish: "parecido" }
  ,
  { rank: Rank 899, english: "ordinary, current (of water)", spanish: "corriente" }
  ,
  { rank: Rank 900, english: "friendly", spanish: "amable" }
  ,
  { rank: Rank 901, english: "reading", spanish: "lectura" }
  ,
  { rank: Rank 902, english: "message", spanish: "mensaje" }
  ,
  { rank: Rank 903, english: "existence", spanish: "existencia" }
  ,
  { rank: Rank 904, english: "language (speech, style)", spanish: "lenguaje" }
  ,
  { rank: Rank 905, english: "costume", spanish: "traje" }
  ,
  { rank: Rank 906, english: "to send", spanish: "enviar" }
  ,
  { rank: Rank 907, english: "soul", spanish: "alma" }
  ,
  { rank: Rank 908, english: "even, yet, still", spanish: "aun" }
  ,
  { rank: Rank 909, english: "destination", spanish: "destino" }
  ,
  { rank: Rank 910, english: "education", spanish: "educación" }
  ,
  { rank: Rank 911, english: "to care", spanish: "cuidar" }
  ,
  { rank: Rank 912, english: "to intervene", spanish: "intervenir" }
  ,
  { rank: Rank 913, english: "dinner", spanish: "cena" }
  ,
  { rank: Rank 914, english: "operation", spanish: "operación" }
  ,
  { rank: Rank 915, english: "perfectly", spanish: "perfectamente" }
  ,
  { rank: Rank 916, english: "to extend", spanish: "extender" }
  ,
  { rank: Rank 917, english: "to check", spanish: "comprobar" }
  ,
  { rank: Rank 918, english: "note", spanish: "nota" }
  ,
  { rank: Rank 919, english: "particular", spanish: "particular" }
  ,
  { rank: Rank 920, english: "to delay", spanish: "tardar" }
  ,
  { rank: Rank 921, english: "in, inside", spanish: "adentro" }
  ,
  { rank: Rank 922, english: "military", spanish: "militar" }
  ,
  { rank: Rank 923, english: "song", spanish: "canción" }
  ,
  { rank: Rank 924, english: "attached", spanish: "unido" }
  ,
  { rank: Rank 925, english: "to discuss", spanish: "discutir" }
  ,
  { rank: Rank 926, english: "to fear", spanish: "temer" }
  ,
  { rank: Rank 927, english: "extraordinary", spanish: "extraordinario" }
  ,
  { rank: Rank 928, english: "theater", spanish: "teatro" }
  ,
  { rank: Rank 929, english: "to face", spanish: "enfrentar" }
  ,
  { rank: Rank 930, english: "newly, freshly", spanish: "recién" }
  ,
  { rank: Rank 931, english: "average", spanish: "media" }
  ,
  { rank: Rank 932, english: "letter (of the alphabet)", spanish: "letra" }
  ,
  { rank: Rank 933, english: "feeling", spanish: "sentimiento" }
  ,
  { rank: Rank 934, english: "to drive", spanish: "conducir" }
  ,
  { rank: Rank 935, english: "completely", spanish: "completamente" }
  ,
  { rank: Rank 936, english: "cold", spanish: "frío" }
  ,
  { rank: Rank 937, english: "to sign", spanish: "firmar" }
  ,
  { rank: Rank 938, english: "solution", spanish: "solución" }
  ,
  { rank: Rank 939, english: "health", spanish: "salud" }
  ,
  { rank: Rank 940, english: "works", spanish: "funciona" }
  ,
  { rank: Rank 941, english: "print", spanish: "impresión" }
  ,
  { rank: Rank 942, english: "to complain", spanish: "quejarse" }
  ,
  { rank: Rank 943, english: "intention", spanish: "intención" }
  ,
  { rank: Rank 944, english: "rate", spanish: "ritmo" }
  ,
  { rank: Rank 945, english: "green", spanish: "verde" }
  ,
  { rank: Rank 946, english: "exact", spanish: "exacto" }
  ,
  { rank: Rank 947, english: "to respect", spanish: "respetar" }
  ,
  { rank: Rank 948, english: "terrible", spanish: "terrible" }
  ,
  { rank: Rank 949, english: "bank", spanish: "banco" }
  ,
  { rank: Rank 950, english: "via", spanish: "vía" }
  ,
  { rank: Rank 951, english: "to hold", spanish: "sostener" }
  ,
  { rank: Rank 952, english: "moon", spanish: "luna" }
  ,
  { rank: Rank 953, english: "skin", spanish: "piel" }
  ,
  { rank: Rank 954, english: "left (direction)", spanish: "izquierda" }
  ,
  { rank: Rank 955, english: "in front", spanish: "delante" }
  ,
  { rank: Rank 956, english: "religious", spanish: "religioso" }
  ,
  { rank: Rank 957, english: "to warn", spanish: "advertir" }
  ,
  { rank: Rank 958, english: "dark", spanish: "oscuro" }
  ,
  { rank: Rank 959, english: "research", spanish: "investigación" }
  ,
  { rank: Rank 960, english: "heat", spanish: "calor" }
  ,
  { rank: Rank 961, english: "shop", spanish: "tienda" }
  ,
  { rank: Rank 962, english: "conversation", spanish: "conversación" }
  ,
  { rank: Rank 963, english: "Christmas", spanish: "navidad" }
  ,
  { rank: Rank 964, english: "summer", spanish: "verano" }
  ,
  { rank: Rank 965, english: "respect", spanish: "respeto" }
  ,
  { rank: Rank 966, english: "grandfather", spanish: "abuelo" }
  ,
  { rank: Rank 967, english: "north", spanish: "norte" }
  ,
  { rank: Rank 968, english: "by means of", spanish: "mediante" }
  ,
  { rank: Rank 969, english: "tradition", spanish: "tradición" }
  ,
  { rank: Rank 970, english: "is sufficient to (to be enough)", spanish: "bastar" }
  ,
  { rank: Rank 971, english: "couple", spanish: "pareja" }
  ,
  { rank: Rank 972, english: "population", spanish: "población" }
  ,
  { rank: Rank 973, english: "lawyer", spanish: "abogado" }
  ,
  { rank: Rank 974, english: "daily", spanish: "diario" }
  ,
  { rank: Rank 975, english: "honor", spanish: "honor" }
  ,
  { rank: Rank 976, english: "blue", spanish: "azul" }
  ,
  { rank: Rank 977, english: "to mention", spanish: "mencionar" }
  ,
  { rank: Rank 978, english: "generation", spanish: "generación" }
  ,
  { rank: Rank 979, english: "vision", spanish: "visión" }
  ,
  { rank: Rank 980, english: "concrete", spanish: "concrete" }
  ,
  { rank: Rank 981, english: "completed", spanish: "terminado" }
  ,
  { rank: Rank 982, english: "to raise (an issue)", spanish: "plantear" }
  ,
  { rank: Rank 983, english: "left behind", spanish: "dejado" }
  ,
  { rank: Rank 984, english: "to test", spanish: "probar" }
  ,
  { rank: Rank 985, english: "to swear, pledge", spanish: "jurar" }
  ,
  { rank: Rank 986, english: "beautiful", spanish: "hermoso" }
  ,
  { rank: Rank 987, english: "danger", spanish: "peligro" }
  ,
  { rank: Rank 988, english: "confidence", spanish: "confianza" }
  ,
  { rank: Rank 989, english: "to fill", spanish: "llenar" }
  ,
  { rank: Rank 990, english: "simple", spanish: "sencillo" }
  ,
  { rank: Rank 991, english: "to improve", spanish: "mejorar" }
  ,
  { rank: Rank 992, english: "concept", spanish: "concepto" }
  ,
  { rank: Rank 993, english: "to highlight", spanish: "destacar" }
  ,
  { rank: Rank 994, english: "wood", spanish: "madera" }
  ,
  { rank: Rank 995, english: "to walk", spanish: "caminar" }
  ,
  { rank: Rank 996, english: "to employ", spanish: "emplear" }
  ,
  { rank: Rank 997, english: "to agree", spanish: "convenir" }
  ,
  { rank: Rank 998, english: "energy", spanish: "energía" }
  ,
  { rank: Rank 999, english: "to admit", spanish: "admitir" }
  ,
  { rank: Rank 1000, english: "is delightful to (to love)", spanish: "encantar" }
  ]
