-- | GENERATED by tools/sync-paraphrase.mjs - do not edit.
-- |
-- | Source: data/es-paraphrase.csv (41 prompts).
module Flashcards.Data.Paraphrase.Spanish
  ( prompts
  )
  where

import Flashcards.Verbs.Paraphrase (Prompt, Trap(..))
import Flashcards.Verbs.Table (Person(..), Tense(..))

-- | In the corpus's order, which is the order their items are first asked in.
prompts :: Array Prompt
prompts =
  [ { id: "door-open", asked: "How would you tell me the door is open?"
    , model: "La puerta está abierta."
    , verb: "estar", tense: Present, person: Sg3
    , trap: OnVerb, against: "ser"
    }
  , { id: "sick-today", asked: "How might you say you're sick today?"
    , model: "Hoy estoy enfermo."
    , verb: "estar", tense: Present, person: Sg1
    , trap: OnVerb, against: "ser"
    }
  , { id: "brother-tall", asked: "How would you tell me your brother is tall?"
    , model: "Mi hermano es alto."
    , verb: "ser", tense: Present, person: Sg3
    , trap: OnVerb, against: "estar"
    }
  , { id: "party-house", asked: "How would you say the party is at your house?"
    , model: "La fiesta es en mi casa."
    , verb: "ser", tense: Present, person: Sg3
    , trap: OnVerb, against: "estar"
    }
  , { id: "at-home", asked: "How would you tell me you're at home?"
    , model: "Estoy en casa."
    , verb: "estar", tense: Present, person: Sg1
    , trap: OnVerb, against: "ser"
    }
  , { id: "where-am-i", asked: "How might you ask me where I am?"
    , model: "¿Dónde estás?"
    , verb: "estar", tense: Present, person: Sg2
    , trap: OnVerb, against: "ser"
    }
  , { id: "sister-doctor", asked: "How would you tell me your sister is a doctor?"
    , model: "Mi hermana es médica."
    , verb: "ser", tense: Present, person: Sg3
    , trap: OnVerb, against: "estar"
    }
  , { id: "children-bored", asked: "How might you say the children are bored?"
    , model: "Los niños están aburridos."
    , verb: "estar", tense: Present, person: Pl3
    , trap: OnVerb, against: "ser"
    }
  , { id: "we-ready", asked: "How would you tell me we're ready?"
    , model: "Estamos listos."
    , verb: "estar", tense: Present, person: Pl1
    , trap: OnVerb, against: "ser"
    }
  , { id: "one-o-clock", asked: "How would you say it's one o'clock?"
    , model: "Es la una."
    , verb: "ser", tense: Present, person: Sg3
    , trap: OnVerb, against: "estar"
    }
  , { id: "from-mexico", asked: "How would you tell me you're from Mexico?"
    , model: "Soy de México."
    , verb: "ser", tense: Present, person: Sg1
    , trap: OnVerb, against: "estar"
    }
  , { id: "food-good", asked: "How might you say the food is really good today?"
    , model: "Hoy la comida está muy buena."
    , verb: "estar", tense: Present, person: Sg3
    , trap: OnVerb, against: "ser"
    }
  , { id: "city-far", asked: "How would you tell me the city is far from here?"
    , model: "La ciudad está lejos de aquí."
    , verb: "estar", tense: Present, person: Sg3
    , trap: OnVerb, against: "ser"
    }
  , { id: "went-store-weekly", asked: "How would you tell me you went to the store every week?"
    , model: "Iba a la tienda cada semana."
    , verb: "ir", tense: Imperfect, person: Sg1
    , trap: OnTense, against: "preterite"
    }
  , { id: "went-mexico", asked: "How might you say you went to Mexico last year?"
    , model: "El año pasado fui a México."
    , verb: "ir", tense: Preterite, person: Sg1
    , trap: OnTense, against: "imperfect"
    }
  , { id: "had-dog", asked: "How would you tell me you had a dog as a kid?"
    , model: "De niño, tenía un perro."
    , verb: "tener", tense: Imperfect, person: Sg1
    , trap: OnTense, against: "preterite"
    }
  , { id: "sister-had-son", asked: "How would you say your sister had a son yesterday?"
    , model: "Ayer mi hermana tuvo un hijo."
    , verb: "tener", tense: Preterite, person: Sg3
    , trap: OnTense, against: "imperfect"
    }
  , { id: "played-street", asked: "How would you tell me you played in the street every day as a kid?"
    , model: "De niño, jugaba en la calle todos los días."
    , verb: "jugar", tense: Imperfect, person: Sg1
    , trap: OnTense, against: "preterite"
    }
  , { id: "played-two-hours", asked: "How might you say you played for two hours yesterday?"
    , model: "Ayer jugué dos horas."
    , verb: "jugar", tense: Preterite, person: Sg1
    , trap: OnTense, against: "imperfect"
    }
  , { id: "reading-when-called", asked: "How would you tell me you were reading when I called?"
    , model: "Leía cuando me llamaste."
    , verb: "leer", tense: Imperfect, person: Sg1
    , trap: OnTense, against: "preterite"
    }
  , { id: "read-whole-book", asked: "How would you tell me you read the whole book last night?"
    , model: "Anoche leí todo el libro."
    , verb: "leer", tense: Preterite, person: Sg1
    , trap: OnTense, against: "imperfect"
    }
  , { id: "slept-badly", asked: "How would you say you slept badly last night?"
    , model: "Anoche dormí mal."
    , verb: "dormir", tense: Preterite, person: Sg1
    , trap: OnTense, against: "imperfect"
    }
  , { id: "found-out-truth", asked: "How would you tell me you found out the truth yesterday?"
    , model: "Ayer supe la verdad."
    , verb: "saber", tense: Preterite, person: Sg1
    , trap: OnTense, against: "imperfect"
    }
  , { id: "already-knew-answer", asked: "How might you say you already knew the answer?"
    , model: "Ya sabía la respuesta."
    , verb: "saber", tense: Imperfect, person: Sg1
    , trap: OnTense, against: "preterite"
    }
  , { id: "met-brother-party", asked: "How would you tell me you met my brother at a party?"
    , model: "Conocí a tu hermano en una fiesta."
    , verb: "conocer", tense: Preterite, person: Sg1
    , trap: OnTense, against: "imperfect"
    }
  , { id: "grandparents-came", asked: "How would you tell me your grandparents always came on Sundays?"
    , model: "Mis abuelos siempre venían los domingos."
    , verb: "venir", tense: Imperfect, person: Pl3
    , trap: OnTense, against: "preterite"
    }
  , { id: "want-brother-come", asked: "How might you say you want your brother to come?"
    , model: "Quiero que venga mi hermano."
    , verb: "venir", tense: Subjunctive, person: Sg3
    , trap: OnTense, against: "present"
    }
  , { id: "hope-we-can-go", asked: "How would you tell me you hope we can go?"
    , model: "Espero que podamos ir."
    , verb: "poder", tense: Subjunctive, person: Pl1
    , trap: OnTense, against: "present"
    }
  , { id: "tell-me-truth", asked: "How would you ask me to tell you the truth?"
    , model: "Quiero que me digas la verdad."
    , verb: "decir", tense: Subjunctive, person: Sg2
    , trap: OnTense, against: "present"
    }
  , { id: "call-when-home", asked: "How would you say you'll call me when you get home?"
    , model: "Te llamo cuando llegue a casa."
    , verb: "llegar", tense: Subjunctive, person: Sg1
    , trap: OnTense, against: "present"
    }
  , { id: "important-homework", asked: "How would you tell me it's important that they do their homework?"
    , model: "Es importante que hagan la tarea."
    , verb: "hacer", tense: Subjunctive, person: Pl3
    , trap: OnTense, against: "present"
    }
  , { id: "dont-think-true", asked: "How might you say you don't think it's true?"
    , model: "No creo que sea verdad."
    , verb: "ser", tense: Subjunctive, person: Sg3
    , trap: OnTense, against: "present"
    }
  , { id: "want-him-set", asked: "How would you tell me you want him to set the table?"
    , model: "Quiero que ponga la mesa."
    , verb: "poner", tense: Subjunctive, person: Sg3
    , trap: OnTense, against: "present"
    }
  , { id: "do-when-time", asked: "How would you tell me you'll do it when you have time?"
    , model: "Lo hago cuando tenga tiempo."
    , verb: "tener", tense: Subjunctive, person: Sg1
    , trap: OnTense, against: "present"
    }
  , { id: "know-this-city", asked: "How might you say you know this city?"
    , model: "Conozco esta ciudad."
    , verb: "conocer", tense: Present, person: Sg1
    , trap: OnVerb, against: "saber"
    }
  , { id: "know-drive", asked: "How would you tell me you know how to drive?"
    , model: "Sé conducir."
    , verb: "saber", tense: Present, person: Sg1
    , trap: OnVerb, against: "conocer"
    }
  , { id: "know-sister", asked: "How would you ask me if I know your sister?"
    , model: "¿Conoces a mi hermana?"
    , verb: "conocer", tense: Present, person: Sg2
    , trap: OnVerb, against: "saber"
    }
  , { id: "know-where-hotel", asked: "How might you ask me if I know where the hotel is?"
    , model: "¿Sabes dónde está el hotel?"
    , verb: "saber", tense: Present, person: Sg2
    , trap: OnVerb, against: "conocer"
    }
  , { id: "nobody-knows-name", asked: "How would you tell me nobody knows his name?"
    , model: "Nadie sabe su nombre."
    , verb: "saber", tense: Present, person: Sg3
    , trap: OnVerb, against: "conocer"
    }
  , { id: "parents-know-family", asked: "How would you say my parents know your family?"
    , model: "Tus padres conocen a mi familia."
    , verb: "conocer", tense: Present, person: Pl3
    , trap: OnVerb, against: "saber"
    }
  , { id: "we-know-late", asked: "How would you tell me we know it's late?"
    , model: "Sabemos que es tarde."
    , verb: "saber", tense: Present, person: Pl1
    , trap: OnVerb, against: "conocer"
    }
  ]
