// Generates the conjugation module from its committed CSV.
//
//   node tools/sync-verbs.mjs
//
// Refuses a table with a gap, a duplicate or a cell out of place. Whether the
// forms are *right* is tools/check-verbs.mjs, which is a review to read rather
// than a gate to pass, so it is not run here.

import fs from "fs"
import crypto from "crypto"
import { CSV, TENSES, PERSONS, loadTable } from "./verb-source.mjs"

const { verbs, errors } = loadTable()
if (errors.length) {
  for (const e of errors) console.error(`x ${e}`)
  console.error(`${errors.length} structural problem(s) in ${CSV}; nothing written`)
  process.exit(1)
}

const cells = verbs.flatMap(verb =>
  TENSES.flatMap(tense =>
    PERSONS.map(person => ({
      infinitive: verb.infinitive,
      tense,
      person,
      form: verb.cells.get(`${tense.name}.${person.name}`),
    }))))

// Changes when any cell does, and only then. Nothing depends on it yet: it is
// here so that a payload graded against this table can later say which one.
const fingerprint = crypto.createHash("sha256")
  .update(cells.map(c => `${c.infinitive}\u0000${c.tense.name}\u0000${c.person.name}\u0000${c.form}`).join("\n"))
  .digest("hex").slice(0, 12)

// Leading commas, as the deck modules write them.
const entries = cells
  .map(c => `{ infinitive: "${c.infinitive}", tense: ${c.tense.constructor}`
           + `, person: ${c.person.constructor}, form: "${c.form}" }`)
  .join("\n  , ")

const out = "src/Flashcards/Data/Verbs/Spanish.purs"
fs.mkdirSync("src/Flashcards/Data/Verbs", { recursive: true })
fs.writeFileSync(out, `-- | GENERATED by tools/sync-verbs.mjs - do not edit.
-- |
-- | Source: ${CSV} (${verbs.length} verbs, ${cells.length} cells, irregular verbs only).
module Flashcards.Data.Verbs.Spanish
  ( fingerprint
  , table
  )
  where

import Flashcards.Verbs.Table (Cell, Person(..), Tense(..))

-- | Content hash of every cell.
fingerprint :: String
fingerprint = "${fingerprint}"

-- | One entry per cell, grouped by verb, then tense, then person.
table :: Array Cell
table =
  [ ${entries}
  ]
`)

console.log(`wrote ${out} (${verbs.length} verbs, ${cells.length} cells, fingerprint ${fingerprint})`)
