// Generates src/Flashcards/Data/Deck/Spanish.purs from data/es-1000.csv.
//
//   node tools/sync-deck.mjs           regenerate the module from the committed CSV
//   node tools/sync-deck.mjs --fetch   pull the sheet first, then regenerate
//
// The sheet is the authoring tool; the app never talks to it at runtime.

import fs from "fs"
import crypto from "crypto"

const SHEET_ID = "1vz4CgmSxP7fFmoa-uzjXPmHckkjSfl2evmRyG5EsH5w"
const CSV_PATH = "data/es-1000.csv"
const OUT_PATH = "src/Flashcards/Data/Deck/Spanish.purs"

// RFC 4180: fields may be quoted, quotes escape as "".
const parseCsv = text => {
  const rows = []
  let row = [], field = "", quoted = false

  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++ }
      else if (c === '"') quoted = false
      else field += c
    } else if (c === '"') quoted = true
    else if (c === ",") { row.push(field); field = "" }
    else if (c === "\n") { row.push(field); rows.push(row); row = []; field = "" }
    else if (c !== "\r") field += c
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row) }

  return rows
}

const fail = msg => { console.error(`✗ ${msg}`); process.exit(1) }

if (process.argv.includes("--fetch")) {
  const url = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv`
  console.log(`↓ fetching ${url}`)
  const res = await fetch(url)
  if (!res.ok) fail(`sheet fetch failed: ${res.status} ${res.statusText}`)
  const body = await res.text()
  if (!body.startsWith("Order,")) fail("sheet did not return the expected CSV header")
  fs.writeFileSync(CSV_PATH, body)
  console.log(`✓ wrote ${CSV_PATH}`)
}

const [header, ...rows] = parseCsv(fs.readFileSync(CSV_PATH, "utf-8"))

if (header.join(",") !== "Order,English,Español") fail(`unexpected header: ${header.join(",")}`)

const cards = rows.map((cells, i) => {
  if (cells.length !== 3) fail(`row ${i + 2} has ${cells.length} fields, expected 3`)
  const [order, english, spanish] = cells.map(c => c.trim())
  const rank = Number(order)
  if (!Number.isInteger(rank)) fail(`row ${i + 2} has a non-integer Order: ${order}`)
  if (!english) fail(`row ${i + 2} has an empty English side`)
  if (!spanish) fail(`row ${i + 2} has an empty Spanish side`)
  return { rank, english, spanish }
})

// Invariants the app depends on.
cards.forEach((c, i) => {
  if (c.rank !== i + 1) fail(`Order is not contiguous: expected ${i + 1}, got ${c.rank}`)
})

const bySpanish = new Map()
for (const c of cards) {
  if (bySpanish.has(c.spanish)) {
    fail(`duplicate Spanish side ${JSON.stringify(c.spanish)} at #${bySpanish.get(c.spanish)} and #${c.rank}. `
       + `ES→EN prompting assumes the Spanish side is unique.`)
  }
  bySpanish.set(c.spanish, c.rank)
}

// Not an error — EN→ES is a v2 concern — but worth surfacing on every sync.
const byEnglish = new Map()
for (const c of cards) byEnglish.set(c.english, [...(byEnglish.get(c.english) ?? []), c.spanish])
const collisions = [...byEnglish.entries()].filter(([, v]) => v.length > 1)

const escape = s => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')

// Identifies this exact deck content. Exports carry it so a progress file made
// against a renumbered deck is rejected instead of silently remapping onto the
// wrong words.
const fingerprint = crypto
  .createHash("sha256")
  .update(cards.map(c => `${c.rank}\u0000${c.english}\u0000${c.spanish}`).join("\n"))
  .digest("hex")
  .slice(0, 12)

const entries = cards
  .map(c => `  { rank: Rank ${c.rank}, english: "${escape(c.english)}", spanish: "${escape(c.spanish)}" }`)
  .join("\n  ,\n")

fs.writeFileSync(OUT_PATH, `-- | GENERATED by tools/sync-deck.mjs — do not edit.
-- |
-- | Source: ${CSV_PATH} (${cards.length} words, ordered by frequency).
module Flashcards.Data.Deck.Spanish
  ( deck
  , fingerprint
  )
  where

import Flashcards.Types.Card (Card, Rank(..))

-- | Content hash of this deck. Progress is keyed by rank, so a deck whose rows
-- | were renumbered is a different deck as far as saved progress is concerned.
fingerprint :: String
fingerprint = "${fingerprint}"

-- | The 1000 most common Spanish words, most frequent first. The index into
-- | this deck is meaningful: it is the curriculum order.
deck :: Array Card
deck =
  [
${entries}
  ]
`)

console.log(`✓ wrote ${OUT_PATH} (${cards.length} cards, fingerprint ${fingerprint})`)
console.log(`  ${cards.filter(c => c.english.startsWith("to ")).length} verbs`)
console.log(`  ${collisions.length} English sides map to >1 Spanish word `
          + `(${collisions.reduce((n, [, v]) => n + v.length, 0)} rows) — relevant when EN→ES lands in v2`)
