// Generates the conjugation module from its committed CSV.
//
//   node tools/sync-verbs.mjs
//
// Refuses a table with a gap, a duplicate or a cell out of place. Whether the
// forms are *right* is tools/check-verbs.mjs, which is a review to read rather
// than a gate to pass, so it is not run here.
//
// It does write out what check-verbs prints: every cell that differs from the
// regular pattern, with the form the pattern would have given. The error
// correction drill is built from that list (#26), and generating it with the
// same `regular` check-verbs uses is what stops the drill and the review
// disagreeing about what a regularised form is.

import fs from "fs"
import crypto from "crypto"
import { CSV, TENSES, PERSONS, loadTable, regular } from "./verb-source.mjs"

const { verbs, errors } = loadTable()
if (errors.length) {
  for (const e of errors) console.error(`x ${e}`)
  console.error(`${errors.length} structural problem(s) in ${CSV}; nothing written`)
  process.exit(1)
}

const cells = verbs.flatMap(verb =>
  TENSES.flatMap(tense =>
    PERSONS.map(person => ({
      infinitive: verb.infinitive,
      tense,
      person,
      form: verb.cells.get(`${tense.name}.${person.name}`),
    }))))

// Changes when any cell does, and only then. Nothing depends on it yet: it is
// here so that a payload graded against this table can later say which one.
const fingerprint = crypto.createHash("sha256")
  .update(cells.map(c => `${c.infinitive}\u0000${c.tense.name}\u0000${c.person.name}\u0000${c.form}`).join("\n"))
  .digest("hex").slice(0, 12)

// Leading commas, as the deck modules write them.
const entries = cells
  .map(c => `{ infinitive: "${c.infinitive}", tense: ${c.tense.constructor}`
           + `, person: ${c.person.constructor}, form: "${c.form}" }`)
  .join("\n  , ")

// The cells check-verbs reports, in table order.
const deviations = cells
  .map(c => ({ ...c, regular: regular(c.infinitive, c.tense.name, c.person.name) }))
  .filter(c => c.regular !== null && c.regular !== c.form)

const deviating = deviations
  .map(c => `{ infinitive: "${c.infinitive}", tense: ${c.tense.constructor}`
           + `, person: ${c.person.constructor}, regular: "${c.regular}" }`)
  .join("\n  , ")

const out = "src/Flashcards/Data/Verbs/Spanish.purs"
fs.mkdirSync("src/Flashcards/Data/Verbs", { recursive: true })
fs.writeFileSync(out, `-- | GENERATED by tools/sync-verbs.mjs - do not edit.
-- |
-- | Source: ${CSV} (${verbs.length} verbs, ${cells.length} cells, irregular verbs only).
module Flashcards.Data.Verbs.Spanish
  ( deviations
  , fingerprint
  , table
  )
  where

import Flashcards.Verbs.Table (Cell, Deviation, Person(..), Tense(..))

-- | Content hash of every cell.
fingerprint :: String
fingerprint = "${fingerprint}"

-- | One entry per cell, grouped by verb, then tense, then person.
table :: Array Cell
table =
  [ ${entries}
  ]

-- | Every cell that differs from the regular pattern, and what the pattern
-- | would have given: what \`npm run check-verbs\` prints. ${deviations.length} of them.
deviations :: Array Deviation
deviations =
  [ ${deviating}
  ]
`)

console.log(`wrote ${out} (${verbs.length} verbs, ${cells.length} cells, fingerprint ${fingerprint})`)
