-- | GENERATED by tools/sync-sentences.mjs - do not edit.
-- |
-- | Source: data/es-sentences.csv (155 sentences).
module Flashcards.Data.Sentences.Spanish
  ( sentences
  )
  where

import Flashcards.Verbs.Shift (Sentence)
import Flashcards.Verbs.Table (Person(..), Tense(..))

-- | In the bank's order, which is the order their items are first asked in.
sentences :: Array Sentence
sentences =
  [ { before: "", form: "tengo", after: " mucho trabajo", infinitive: "tener", tense: Present, person: Sg1, personShift: true }
  , { before: "mis padres ", form: "tienen", after: " una casa grande", infinitive: "tener", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "hacemos", after: " la comida", infinitive: "hacer", tense: Present, person: Pl1, personShift: true }
  , { before: "ella ", form: "hace", after: " la cena", infinitive: "hacer", tense: Present, person: Sg3, personShift: false }
  , { before: "no ", form: "puedo", after: " dormir", infinitive: "poder", tense: Present, person: Sg1, personShift: true }
  , { before: "ellos no ", form: "pueden", after: " entrar", infinitive: "poder", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "dices", after: " la verdad", infinitive: "decir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi hermano ", form: "dice", after: " que no", infinitive: "decir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "vamos", after: " al mercado", infinitive: "ir", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "voy", after: " a la ciudad", infinitive: "ir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "estoy", after: " muy enfermo", infinitive: "estar", tense: Present, person: Sg1, personShift: false }
  , { before: "los niños ", form: "están", after: " en la escuela", infinitive: "estar", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "quieres", after: " ayudar", infinitive: "querer", tense: Present, person: Sg2, personShift: true }
  , { before: "ella ", form: "quiere", after: " salir", infinitive: "querer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "tienes", after: " mucho tiempo", infinitive: "tener", tense: Present, person: Sg2, personShift: true }
  , { before: "", form: "tenemos", after: " un problema", infinitive: "tener", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "hago", after: " la cama", infinitive: "hacer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "hacen", after: " el trabajo", infinitive: "hacer", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "podemos", after: " ir", infinitive: "poder", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "puedes", after: " venir", infinitive: "poder", tense: Present, person: Sg2, personShift: true }
  , { before: "", form: "digo", after: " que sí", infinitive: "decir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "dicen", after: " muchas cosas", infinitive: "decir", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "van", after: " a la escuela", infinitive: "ir", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "quiero", after: " comer", infinitive: "querer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "queremos", after: " trabajar", infinitive: "querer", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "estamos", after: " en casa", infinitive: "estar", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "estoy", after: " aquí", infinitive: "estar", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "estás", after: " en el trabajo", infinitive: "estar", tense: Present, person: Sg2, personShift: true }
  , { before: "", form: "veo", after: " la casa", infinitive: "ver", tense: Present, person: Sg1, personShift: true }
  , { before: "no ", form: "ves", after: " el problema", infinitive: "ver", tense: Present, person: Sg2, personShift: true }
  , { before: "mi padre ", form: "ve", after: " a su hermano", infinitive: "ver", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "vemos", after: " a los niños", infinitive: "ver", tense: Present, person: Pl1, personShift: true }
  , { before: "ellos no ", form: "ven", after: " nada", infinitive: "ver", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "vengo", after: " aquí a trabajar", infinitive: "venir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "vienes", after: " de la escuela", infinitive: "venir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "viene", after: " a comer", infinitive: "venir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "venimos", after: " del trabajo", infinitive: "venir", tense: Present, person: Pl1, personShift: true }
  , { before: "mis amigos ", form: "vienen", after: " a la fiesta", infinitive: "venir", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "soy", after: " parte de la familia", infinitive: "ser", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "eres", after: " la razón de todo", infinitive: "ser", tense: Present, person: Sg2, personShift: true }
  , { before: "la fiesta ", form: "es", after: " en mi casa", infinitive: "ser", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "somos", after: " parte del problema", infinitive: "ser", tense: Present, person: Pl1, personShift: true }
  , { before: "las preguntas ", form: "son", after: " muy difíciles", infinitive: "ser", tense: Present, person: Pl3, personShift: false }
  , { before: "no ", form: "sé", after: " nada", infinitive: "saber", tense: Present, person: Sg1, personShift: true }
  , { before: "no ", form: "sabes", after: " la verdad", infinitive: "saber", tense: Present, person: Sg2, personShift: true }
  , { before: "mi hermana ", form: "sabe", after: " la respuesta", infinitive: "saber", tense: Present, person: Sg3, personShift: false }
  , { before: "no ", form: "sabemos", after: " su nombre", infinitive: "saber", tense: Present, person: Pl1, personShift: true }
  , { before: "mis padres ", form: "saben", after: " la noticia", infinitive: "saber", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "pongo", after: " la mesa", infinitive: "poner", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "pones", after: " la ropa en la cama", infinitive: "poner", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "pone", after: " la comida en la mesa", infinitive: "poner", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "ponemos", after: " los libros aquí", infinitive: "poner", tense: Present, person: Pl1, personShift: true }
  , { before: "los niños ", form: "ponen", after: " sus cosas en el coche", infinitive: "poner", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "caigo", after: " al suelo", infinitive: "caer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "caes", after: " en el mismo error", infinitive: "caer", tense: Present, person: Sg2, personShift: true }
  , { before: "la noche ", form: "cae", after: " sobre el pueblo", infinitive: "caer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "caemos", after: " al agua", infinitive: "caer", tense: Present, person: Pl1, personShift: true }
  , { before: "los libros ", form: "caen", after: " de la mesa", infinitive: "caer", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "oigo", after: " una voz", infinitive: "oír", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "oyes", after: " la música", infinitive: "oír", tense: Present, person: Sg2, personShift: true }
  , { before: "mi abuela no ", form: "oye", after: " bien", infinitive: "oír", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "oímos", after: " las noticias", infinitive: "oír", tense: Present, person: Pl1, personShift: true }
  , { before: "mis padres ", form: "oyen", after: " la radio", infinitive: "oír", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "traigo", after: " el pan", infinitive: "traer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "traes", after: " buenas noticias", infinitive: "traer", tense: Present, person: Sg2, personShift: true }
  , { before: "mi tío ", form: "trae", after: " el vino", infinitive: "traer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "traemos", after: " agua", infinitive: "traer", tense: Present, person: Pl1, personShift: true }
  , { before: "mis amigos ", form: "traen", after: " la cena", infinitive: "traer", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "empiezo", after: " a trabajar", infinitive: "empezar", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "empiezas", after: " a entender", infinitive: "empezar", tense: Present, person: Sg2, personShift: true }
  , { before: "la fiesta ", form: "empieza", after: " a las nueve", infinitive: "empezar", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "empezábamos", after: " a comer", infinitive: "empezar", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "empiezan", after: " a hablar", infinitive: "empezar", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "empezaba", after: " el libro", infinitive: "empezar", tense: Imperfect, person: Sg1, personShift: false }
  , { before: "", form: "juego", after: " con los niños", infinitive: "jugar", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "juegas", after: " muy bien", infinitive: "jugar", tense: Present, person: Sg2, personShift: true }
  , { before: "mi hija ", form: "juega", after: " en la calle", infinitive: "jugar", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "jugábamos", after: " juntos", infinitive: "jugar", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "juegan", after: " en la escuela", infinitive: "jugar", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "jugaba", after: " con mis amigos", infinitive: "jugar", tense: Imperfect, person: Sg1, personShift: false }
  , { before: "", form: "duermo", after: " ocho horas", infinitive: "dormir", tense: Present, person: Sg1, personShift: true }
  , { before: "no ", form: "duermes", after: " bien", infinitive: "dormir", tense: Present, person: Sg2, personShift: true }
  , { before: "el niño ", form: "duerme", after: " en su cama", infinitive: "dormir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "dormíamos", after: " poco", infinitive: "dormir", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "duermen", after: " mucho", infinitive: "dormir", tense: Present, person: Pl3, personShift: true }
  , { before: "mis padres ", form: "dormían", after: " en otra casa", infinitive: "dormir", tense: Imperfect, person: Pl3, personShift: false }
  , { before: "", form: "siento", after: " mucho frío", infinitive: "sentir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "sientes", after: " miedo", infinitive: "sentir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "siente", after: " el frío", infinitive: "sentir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "sentíamos", after: " el calor del sol", infinitive: "sentir", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "sienten", after: " mucho calor", infinitive: "sentir", tense: Present, person: Pl3, personShift: true }
  , { before: "los niños ", form: "sentían", after: " miedo", infinitive: "sentir", tense: Imperfect, person: Pl3, personShift: false }
  , { before: "", form: "conozco", after: " a tu hermano", infinitive: "conocer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "conoces", after: " bien la ciudad", infinitive: "conocer", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "conoce", after: " a mucha gente", infinitive: "conocer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "conocemos", after: " a su familia", infinitive: "conocer", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "conocen", after: " este lugar", infinitive: "conocer", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "doy", after: " un libro a mi amigo", infinitive: "dar", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "das", after: " dinero a tu madre", infinitive: "dar", tense: Present, person: Sg2, personShift: true }
  , { before: "mi padre ", form: "da", after: " clases en la escuela", infinitive: "dar", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "damos", after: " las gracias a todos", infinitive: "dar", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "dan", after: " una fiesta", infinitive: "dar", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "pienso", after: " en mi familia", infinitive: "pensar", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "piensas", after: " mucho en el trabajo", infinitive: "pensar", tense: Present, person: Sg2, personShift: true }
  , { before: "mi hermana ", form: "piensa", after: " en su casa", infinitive: "pensar", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "pensábamos", after: " en el futuro", infinitive: "pensar", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "piensan", after: " en la fiesta", infinitive: "pensar", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "pensaba", after: " mucho en mi trabajo", infinitive: "pensar", tense: Imperfect, person: Sg1, personShift: false }
  , { before: "", form: "salgo", after: " de casa a las ocho", infinitive: "salir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "sales", after: " del trabajo muy tarde", infinitive: "salir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "sale", after: " de la escuela", infinitive: "salir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "salíamos", after: " de la ciudad", infinitive: "salir", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "salen", after: " de la casa", infinitive: "salir", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "salía", after: " muy tarde de casa", infinitive: "salir", tense: Imperfect, person: Sg1, personShift: false }
  , { before: "", form: "vuelvo", after: " tarde a casa", infinitive: "volver", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "vuelves", after: " a tu trabajo", infinitive: "volver", tense: Present, person: Sg2, personShift: true }
  , { before: "mi padre ", form: "vuelve", after: " del trabajo", infinitive: "volver", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "volvemos", after: " a nuestra casa", infinitive: "volver", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "vuelven", after: " a su casa", infinitive: "volver", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "valgo", after: " mucho para mi familia", infinitive: "valer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "vales", after: " más que nadie", infinitive: "valer", tense: Present, person: Sg2, personShift: true }
  , { before: "este libro ", form: "vale", after: " mucho dinero", infinitive: "valer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "valemos", after: " más juntos", infinitive: "valer", tense: Present, person: Pl1, personShift: true }
  , { before: "las casas ", form: "valen", after: " mucho", infinitive: "valer", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "leo", after: " un libro en casa", infinitive: "leer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "lees", after: " mucho en casa", infinitive: "leer", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "lee", after: " el periódico", infinitive: "leer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "leemos", after: " en nuestra casa", infinitive: "leer", tense: Present, person: Pl1, personShift: true }
  , { before: "los niños ", form: "leen", after: " muchos libros", infinitive: "leer", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "pido", after: " ayuda a mi madre", infinitive: "pedir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "pides", after: " mucho dinero", infinitive: "pedir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi padre ", form: "pide", after: " la cuenta", infinitive: "pedir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "pedíamos", after: " ayuda a todos", infinitive: "pedir", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "piden", after: " ayuda a su padre", infinitive: "pedir", tense: Present, person: Pl3, personShift: true }
  , { before: "los niños ", form: "pedían", after: " agua", infinitive: "pedir", tense: Imperfect, person: Pl3, personShift: false }
  , { before: "", form: "sigo", after: " a mi hermano", infinitive: "seguir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "sigues", after: " este camino", infinitive: "seguir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "sigue", after: " en casa", infinitive: "seguir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "seguíamos", after: " el camino", infinitive: "seguir", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "siguen", after: " a sus padres", infinitive: "seguir", tense: Present, person: Pl3, personShift: true }
  , { before: "los niños ", form: "seguían", after: " a su padre", infinitive: "seguir", tense: Imperfect, person: Pl3, personShift: false }
  , { before: "", form: "muero", after: " de sueño", infinitive: "morir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "mueres", after: " de miedo", infinitive: "morir", tense: Present, person: Sg2, personShift: true }
  , { before: "el perro ", form: "muere", after: " en la casa", infinitive: "morir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "moríamos", after: " de frío", infinitive: "morir", tense: Imperfect, person: Pl1, personShift: false }
  , { before: "", form: "mueren", after: " de hambre", infinitive: "morir", tense: Present, person: Pl3, personShift: true }
  , { before: "los niños ", form: "morían", after: " de calor", infinitive: "morir", tense: Imperfect, person: Pl3, personShift: false }
  , { before: "mi madre ", form: "está", after: " en la escuela", infinitive: "estar", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "vas", after: " a mi casa", infinitive: "ir", tense: Present, person: Sg2, personShift: false }
  , { before: "mi padre ", form: "va", after: " al trabajo", infinitive: "ir", tense: Present, person: Sg3, personShift: false }
  , { before: "mi hermana ", form: "tiene", after: " un libro", infinitive: "tener", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "haces", after: " mucho por tu familia", infinitive: "hacer", tense: Present, person: Sg2, personShift: false }
  , { before: "mi padre ", form: "puede", after: " venir", infinitive: "poder", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "decimos", after: " que no", infinitive: "decir", tense: Present, person: Pl1, personShift: false }
  , { before: "mis padres ", form: "quieren", after: " comer", infinitive: "querer", tense: Present, person: Pl3, personShift: false }
  ]
