-- | GENERATED by tools/sync-sentences.mjs - do not edit.
-- |
-- | Source: data/es-sentences.csv (68 sentences).
module Flashcards.Data.Sentences.Spanish
  ( sentences
  )
  where

import Flashcards.Verbs.Shift (Sentence)
import Flashcards.Verbs.Table (Person(..), Tense(..))

-- | In the bank's order, which is the order their items are first asked in.
sentences :: Array Sentence
sentences =
  [ { before: "", form: "tengo", after: " mucho trabajo", infinitive: "tener", tense: Present, person: Sg1, personShift: true }
  , { before: "mis padres ", form: "tienen", after: " una casa grande", infinitive: "tener", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "hacemos", after: " la comida", infinitive: "hacer", tense: Present, person: Pl1, personShift: true }
  , { before: "ella ", form: "hace", after: " la cena", infinitive: "hacer", tense: Present, person: Sg3, personShift: false }
  , { before: "no ", form: "puedo", after: " dormir", infinitive: "poder", tense: Present, person: Sg1, personShift: true }
  , { before: "ellos no ", form: "pueden", after: " entrar", infinitive: "poder", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "dices", after: " la verdad", infinitive: "decir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi hermano ", form: "dice", after: " que no", infinitive: "decir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "vamos", after: " al mercado", infinitive: "ir", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "voy", after: " a la ciudad", infinitive: "ir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "estoy", after: " muy enfermo", infinitive: "estar", tense: Present, person: Sg1, personShift: false }
  , { before: "los niños ", form: "están", after: " en la escuela", infinitive: "estar", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "quieres", after: " ayudar", infinitive: "querer", tense: Present, person: Sg2, personShift: true }
  , { before: "ella ", form: "quiere", after: " salir", infinitive: "querer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "tienes", after: " mucho tiempo", infinitive: "tener", tense: Present, person: Sg2, personShift: true }
  , { before: "", form: "tenemos", after: " un problema", infinitive: "tener", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "hago", after: " la cama", infinitive: "hacer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "hacen", after: " el trabajo", infinitive: "hacer", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "podemos", after: " ir", infinitive: "poder", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "puedes", after: " venir", infinitive: "poder", tense: Present, person: Sg2, personShift: true }
  , { before: "", form: "digo", after: " que sí", infinitive: "decir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "dicen", after: " muchas cosas", infinitive: "decir", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "van", after: " a la escuela", infinitive: "ir", tense: Present, person: Pl3, personShift: true }
  , { before: "", form: "quiero", after: " comer", infinitive: "querer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "queremos", after: " trabajar", infinitive: "querer", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "estamos", after: " en casa", infinitive: "estar", tense: Present, person: Pl1, personShift: true }
  , { before: "", form: "estoy", after: " aquí", infinitive: "estar", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "estás", after: " en el trabajo", infinitive: "estar", tense: Present, person: Sg2, personShift: true }
  , { before: "", form: "veo", after: " la casa", infinitive: "ver", tense: Present, person: Sg1, personShift: true }
  , { before: "no ", form: "ves", after: " el problema", infinitive: "ver", tense: Present, person: Sg2, personShift: true }
  , { before: "mi padre ", form: "ve", after: " a su hermano", infinitive: "ver", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "vemos", after: " a los niños", infinitive: "ver", tense: Present, person: Pl1, personShift: true }
  , { before: "ellos no ", form: "ven", after: " nada", infinitive: "ver", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "vengo", after: " aquí a trabajar", infinitive: "venir", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "vienes", after: " de la escuela", infinitive: "venir", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "viene", after: " a comer", infinitive: "venir", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "venimos", after: " del trabajo", infinitive: "venir", tense: Present, person: Pl1, personShift: true }
  , { before: "mis amigos ", form: "vienen", after: " a la fiesta", infinitive: "venir", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "soy", after: " parte de la familia", infinitive: "ser", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "eres", after: " la razón de todo", infinitive: "ser", tense: Present, person: Sg2, personShift: true }
  , { before: "la fiesta ", form: "es", after: " en mi casa", infinitive: "ser", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "somos", after: " parte del problema", infinitive: "ser", tense: Present, person: Pl1, personShift: true }
  , { before: "las preguntas ", form: "son", after: " muy difíciles", infinitive: "ser", tense: Present, person: Pl3, personShift: false }
  , { before: "no ", form: "sé", after: " nada", infinitive: "saber", tense: Present, person: Sg1, personShift: true }
  , { before: "no ", form: "sabes", after: " la verdad", infinitive: "saber", tense: Present, person: Sg2, personShift: true }
  , { before: "mi hermana ", form: "sabe", after: " la respuesta", infinitive: "saber", tense: Present, person: Sg3, personShift: false }
  , { before: "no ", form: "sabemos", after: " su nombre", infinitive: "saber", tense: Present, person: Pl1, personShift: true }
  , { before: "mis padres ", form: "saben", after: " la noticia", infinitive: "saber", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "pongo", after: " la mesa", infinitive: "poner", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "pones", after: " la ropa en la cama", infinitive: "poner", tense: Present, person: Sg2, personShift: true }
  , { before: "mi madre ", form: "pone", after: " la comida en la mesa", infinitive: "poner", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "ponemos", after: " los libros aquí", infinitive: "poner", tense: Present, person: Pl1, personShift: true }
  , { before: "los niños ", form: "ponen", after: " sus cosas en el coche", infinitive: "poner", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "caigo", after: " al suelo", infinitive: "caer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "caes", after: " en el mismo error", infinitive: "caer", tense: Present, person: Sg2, personShift: true }
  , { before: "la noche ", form: "cae", after: " sobre el pueblo", infinitive: "caer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "caemos", after: " al agua", infinitive: "caer", tense: Present, person: Pl1, personShift: true }
  , { before: "los libros ", form: "caen", after: " de la mesa", infinitive: "caer", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "oigo", after: " una voz", infinitive: "oír", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "oyes", after: " la música", infinitive: "oír", tense: Present, person: Sg2, personShift: true }
  , { before: "mi abuela no ", form: "oye", after: " bien", infinitive: "oír", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "oímos", after: " las noticias", infinitive: "oír", tense: Present, person: Pl1, personShift: true }
  , { before: "mis padres ", form: "oyen", after: " la radio", infinitive: "oír", tense: Present, person: Pl3, personShift: false }
  , { before: "", form: "traigo", after: " el pan", infinitive: "traer", tense: Present, person: Sg1, personShift: true }
  , { before: "", form: "traes", after: " buenas noticias", infinitive: "traer", tense: Present, person: Sg2, personShift: true }
  , { before: "mi tío ", form: "trae", after: " el vino", infinitive: "traer", tense: Present, person: Sg3, personShift: false }
  , { before: "", form: "traemos", after: " agua", infinitive: "traer", tense: Present, person: Pl1, personShift: true }
  , { before: "mis amigos ", form: "traen", after: " la cena", infinitive: "traer", tense: Present, person: Pl3, personShift: false }
  ]
