-- | GENERATED by tools/sync-sentences.mjs - do not edit.
-- |
-- | Source: data/es-sentences.csv (14 sentences).
module Flashcards.Data.Sentences.Spanish
  ( sentences
  )
  where

import Flashcards.Verbs.Shift (Sentence)
import Flashcards.Verbs.Table (Person(..), Tense(..))

-- | In the bank's order, which is the order their items are first asked in.
sentences :: Array Sentence
sentences =
  [ { before: "", form: "tengo", after: " mucho trabajo", infinitive: "tener", tense: Present, person: Sg1 }
  , { before: "mis padres ", form: "tienen", after: " una casa grande", infinitive: "tener", tense: Present, person: Pl3 }
  , { before: "", form: "hacemos", after: " la comida", infinitive: "hacer", tense: Present, person: Pl1 }
  , { before: "ella ", form: "hace", after: " la cena", infinitive: "hacer", tense: Present, person: Sg3 }
  , { before: "no ", form: "puedo", after: " dormir", infinitive: "poder", tense: Present, person: Sg1 }
  , { before: "ellos no ", form: "pueden", after: " entrar", infinitive: "poder", tense: Present, person: Pl3 }
  , { before: "", form: "dices", after: " la verdad", infinitive: "decir", tense: Present, person: Sg2 }
  , { before: "mi hermano ", form: "dice", after: " que no", infinitive: "decir", tense: Present, person: Sg3 }
  , { before: "", form: "vamos", after: " al mercado", infinitive: "ir", tense: Present, person: Pl1 }
  , { before: "", form: "voy", after: " a la ciudad", infinitive: "ir", tense: Present, person: Sg1 }
  , { before: "", form: "estoy", after: " muy enfermo", infinitive: "estar", tense: Present, person: Sg1 }
  , { before: "los niños ", form: "están", after: " en la escuela", infinitive: "estar", tense: Present, person: Pl3 }
  , { before: "", form: "quieres", after: " ayudar", infinitive: "querer", tense: Present, person: Sg2 }
  , { before: "ella ", form: "quiere", after: " salir", infinitive: "querer", tense: Present, person: Sg3 }
  ]
